source/develop/release-management/features/index.html.md
source/develop/release-management/releases/4.2/feature.html.md
source/develop/release-management/releases/4.3/feature.md
source/develop/release-management/releases/4.3/release-management.html.md

Adding 4.3 features link

---

source/release/4.2.7/index.html.md

- Added 4.2.7 RC1 Release notes

4.2.7 RC1 Release notes

---

source/develop/release-management/releases/4.2.z/release-management.html.md

Add 4.2.7 schedule

---

source/documentation/how-to/guest-agent/install-the-guest-agent-in-ubuntu.html.md

Once the systemd service has been created, the ovirtagent user does not have the required access to log files and the ovirt virtio-ports in /dev. 
The latest version of Ubuntu (18.04), also requires that we include python in the installed dependencies.
- Add python dependency for Ubuntu 18.04
- Add instructions for systemd
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @mention yourself to sign) 

Add instructions for systemd.

---

source/community/index.html.md

little typo fix

---

source/develop/release-management/releases/4.2.z/release-management.html.md

Add rc2 to 4.2.7 Schedule

---

source/release/4.2.6/index.html.md

removed TL; DR tags from source

---

source/release/4.2.7/index.html.md

- Update release notes for 4.2.7 RC3
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@lveyde)

Update release notes for 4.2.7 RC3

---

source/develop/release-management/releases/4.2.z/release-management.html.md

Updated 4.2.7 schedule

---

source/develop/release-management/releases/4.2.z/release-management.html.md

Update 4.2.7 schedule

---

source/release/4.2.7/index.html.md

- Update 4.2.7 release notes with GA content

Update 4.2.7 release notes

---

source/index.html.haml

Update home with 4.2.7

---

source/download/index.html.haml

- Update download page with 4.2.7

Update download page with 4.2.7

---

source/documentation/index.html.haml

- Update documentation with 4.2.7

Update documentation with 4.2.7

---

source/documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html.md

- current page points to older version of ovrt hyperconverged howto
@jasonbrooks 

update link to howto post

---

source/documentation/metrics-install-guide/Introduction.html.md
source/documentation/metrics-install-guide/Setting_Up_OpenShift_Aggregated_Logging.html.md
source/documentation/metrics-install-guide/Setting_Up_the_oVirt_Engine_and_Hosts.html.md

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1646154
Fixes issue #1796 
- Update metrics installation guide.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco

Update metrics installation guide

---

source/documentation/ovirt-orb/index.html.md

- Reference latest version instead of 4.2.4 release.

Update oVirt Orb documentation

---

source/release/4.2.7/index.html.md

- Update 4.2.7 release notes with async 1 content

Update 4.2.7 release notes with async 1 content

---

source/develop/release-management/features/network/networking-api-security-groups.html.md

- fix the acl direction in the deny-all group
- explain the default security group concept, and its rules
@maiqueb 
@mmirecki 
@dominikholler

Add default group info

---

source/develop/release-management/features/storage/incremental-backup.html.md

- Updated 'Engine database changes' section.

incremental-backup: update db changes

---

source/develop/developer-guide/engine/otopi.html.md

developer-guide/engine/otopi: Users: Add imageio

---

source/develop/release-management/releases/4.3/release-management.html.md

Update 4.3 schedule

---

source/release/4.3.0/index.html.md

Add 4.3.0 Alpha release notes

---

source/release/4.2.8/index.html.md

- 4.2.8 RC1 release notes: add oVirt Engine Metrics bugs
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @tiraboschi 

4.2.8 RC1 release notes: add oVirt Engine Metrics

---

source/feature/openvswitch/native-openvswitch.html.md

@dominikholler @dankenigsberg @EdDev

Native OVS feature page add limitations

---

source/node/faq.md

- Update oVirt Node Next FAQ
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @sandrobonazzola 
This pull request needs review by: @yuvalturg

Update oVirt Node Next FAQ

---

source/release/4.3.0/index.html.md

- Update 4.3.0 release notes with alpha2 content

Update 4.3.0 release notes with alpha2 content

---

source/develop/release-management/features/network/networking-api-security-groups.html.md

- set feature state to released
@maiqueb 
@mmirecki

Security group feature is released

---

source/documentation/self-hosted/chap-Maintenance_and_Upgrading_Resources.html.md

Removal of Self-Hosted Engine, it should select UNDEPLOY

---

source/release/4.2.8/index.html.md

- Update 4.2.8 release notes with rc2 content

Update 4.2.8 release notes with rc2 content

---

source/documentation/index.html.haml

documentation: use absolute links for root books

documentation: use absolute links for root books

---

CONTRIBUTING.md
MAINTAINING.md
README.md

- update names of maintainers
- update local run instructions to help people with the current Ruby crash
- add instructions about using apache locally

update site metadata - how to run, info about contributors

---

source/develop/release-management/releases/4.3/release-management.html.md

Update 4.3.0 schedule

---

source/develop/release-management/releases/4.2.z/release-management.html.md

Update 4.2.8 schedule

---

source/documentation/vmm-guide/appe-Reference_Settings_in_Administration_Portal_and_User_Portal_Windows.html.md

Fix a slew of HTML-in-Markdown issues

---

source/download/index.html.md

download: language cleanup on download page
This pull request needs review by: @gregsheremeta

download: language cleanup on download page

---

source/download/browsers_and_mobile.html.md
source/download/index.html.md

download: download page enhancements
- add more detail to download page, essentially making it a
nice quickstart but with lots of links to official docs.
Added console information, browser support information,
and more details about installing VMs overall
- add Browser Support and Mobile Clients page

download: download page enhancements

---

source/download/index.html.md

download: cleanup css and add a clarification about hosted engine
- remove old unused css classes
- clarify that hosted engine vm is highly available only after
a second host is added

download: cleanup css and add a clarification about hosted engine

---

source/documentation/self-hosted/chap-Troubleshooting.html.md

documentation: typo fix 'and and' -> 'and'

documentation: typo fix 'and and' -> 'and'

---

source/download/index.html.md

download: cleanup and enhancements
- cleanup capitalization for Hosts
- clarify and and cockpit instructions
- cleanup language around enabling repositories

download: cleanup and enhancements

---

source/develop/release-management/features/storage/incremental-backup.html.md

incremental-backup: update API
@nirs @rollandf

incremental-backup: update API

---

source/develop/release-management/features/storage/incremental-backup.html.md

Change threads links into hyperlinks.
@nirs

Overview of libvirt incremental backup API

---

source/develop/release-management/features/network/ipv6_subnets.html.md

@maiqueb 
@mburman5 
@mmirecki

[feature] Ipv6 subnets

---

source/release/4.2.8/index.html.md

- Update 4.2.8 release notes with rc3 content

Update 4.2.8 release notes with rc3 content

---

source/documentation/install-guide/chap-Enterprise_Linux_Hosts.html.md

- Fix md link typo in line 26.

fix link typo

---

source/release/4.3.0/index.html.md

- Update 4.3.0 release notes with RC1 content

Update 4.3.0 release notes with RC1 content

---

source/blog/2019-01-06-ovirt-openshift-part-1.html.md

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rgolan
This pull request needs review by: @frolland

Replace the image credit button with text

---

source/develop/release-management/releases/4.3/release-management.html.md

- Add RC2 to 4.3.0 release schedule

Add RC2 to 4.3.0 release schedule

---

source/download/index.html.md

- Update download page with 4.2.8 GA

Update download page with 4.2.8 GA

---

source/documentation/index.html.haml

- Update documentation page with new releases

Update documentation page with new releases

---

source/index.html.haml

- Update home page with 4.2.8 GA

Update home page with 4.2.8 GA

---

source/develop/release-management/releases/4.2.z/release-management.html.md

- Add EOL notice for 4.2 series

Add EOL notice for 4.2 series

---

source/release/4.2.8/index.html.md

- Update release notes with 4.2.8 GA content

Update release notes with 4.2.8 GA content

---

source/develop/release-management/releases/4.3/release-management.html.md

- Add 4.3.0 RC3 to release schedule

Add 4.3.0 RC3 to schedule

---

source/develop/release-management/releases/4.3/release-management.html.md

- Postponing 4.3 GA one day for addressing blocker

Postponing 4.3 GA one day for addressing blocker

---

source/develop/release-management/releases/4.3/release-management.html.md

- rc5 has been delayed and we won't release over the weekend.
postponed the GA to next Monday.

Postponing 4.3.0 GA to next Monday

---

source/release/4.3.0/index.html.md

- Update notes with rc5 content

Update notes with rc5 content

---

source/documentation/index.html.haml

- Update documentation with 4.3.0 GA

Update documentation pointing to 4.3.0

---

source/download/index.html.md

- Update Download page pointing to 4.3.0

Update Download page pointing to 4.3.0

---

source/index.html.haml

- Update home pointing to 4.3.0

Update home pointing to 4.3.0

---

source/release/4.3.0/index.html.md

- Update 4.3.0 release with GA content

Update 4.3.0 release with GA content

---

source/release/4.3.0/index.html.md

Update upgrade instructions

---

source/release/4.3.0/index.html.md

release notes: add Known Issues for 4.3.0 release notes
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @gregsheremeta 

release notes: add Known Issues for 4.3.0 release notes

---

source/download/index.html.md

download: add Fedora 28 as a platform, tech preview

download: add Fedora 28 as a platform, tech preview

---

source/develop/developer-guide/db-issues/helperutilities.html.md

The page mention various tools but forget to tell where they are hidden.

dbutils: Document the secret dbutils directory

---

source/develop/release-management/releases/4.3.z/release-management.html.md

- Add release management for 4.3.z
- Add 4.3.1 schedule

Add release management for 4.3.z

---

source/blog/2019-01-06-ovirt-openshift-part-1.html.md

- Add READMORE
- Fix typos
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rollandf 
This pull request needs review by: @rgolangh @gregsheremeta

Add READMORE and some typo fixes

---

source/download/index.html.md

download: set font to Open Sans on headings

download: set font to Open Sans on headings

---

source/blog/2018-02-20-your-container-volumes-served-by-ovirt.html.md

Follow-up to issue [oVirt/ovirt-openshift-extensions#86](https://github.com/oVirt/ovirt-openshift-extensions/issues/86).
* Mention `ovirtDiskFormat` in the example of `StorageClass`.
@jan-zmeskal
@rgolangh

Adding ovirtDiskFormat to blog post about ovirt-openshift-extenstions

---

source/develop/api/rest-api/rest-api.html.md

- Example showing SSO w/ more complex user:dom
@slmingol

Adds example showing SSO w/ more complex DOM name

---

.github/ISSUE_TEMPLATE/issue_template_documentation.md
source/layouts/_footer.haml

enhance the default issue template with better instructions.
create a new issue template specifically for documentation.

issue templates enhancements

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/issue_template_documentation.md

fix some formatting issues in the issue templates

update issue templates

---

source/index.html.haml
source/stylesheets/_application-custom.css.sass

homepage cleanup
- remove twitter widget
- remove blog preview
- move embedded css to style block
- set font to OpenSans everywhere
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @gregsheremeta 
Fixes: #1902

homepage cleanup

---

source/develop/release-management/features/metrics/hypervisors-and-engine-setup.md
source/develop/release-management/features/metrics/metrics-store-collected-metrics.html.md
source/develop/release-management/features/metrics/metrics-store-installation.html.md
source/develop/release-management/features/metrics/metrics-store-schema.html.md
source/develop/release-management/features/metrics/metrics-store.html.md
source/develop/release-management/features/metrics/setting-up-viaq-logging.html.md

Signed-off-by: Shirly Radco <sradco@redhat.com>
- Update the oVirt metrics store documentation
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco 

Update oVirt metrics store documentation

---

source/develop/release-management/features/storage/cinderlib-integration.html.md

- Update VDSM APIs and update the page.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rollandf 
This pull request needs review by: @shenitzky @bennyz

Update MBS feature page

---

source/develop/release-management/features/index.html.erb

feature: add 4.3 metrics feature pages to feature index

feature: add 4.3 metrics feature pages to feature index

---

source/documentation/vmm-guide/chap-Administrative_Tasks.html.md

Documentation: change UserVmEngine to UserVmManager
Fixes #1919
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @gregsheremeta 
Thanks to @prstaniforth for reporting!

Documentation: change UserVmEngine to UserVmManager

---

source/release/4.3.1/index.html.md

Add 4.3.1 RC1 release notes

---

source/documentation/admin-guide/chap-Pools.html.md

documentation: fix bad formatting on admin guide > pools chapter
Fixes #1876

documentation: fix bad formatting on admin guide > pools chapter

---

source/documentation/admin-guide/chap-Global_Configuration.html.md
source/documentation/admin-guide/chap-Pools.html.md

documentation: formatting fixes in admin guide > Pools and Roles

documentation: formatting fixes in admin guide > Pools and Roles

---

source/release/4.3.1/index.html.md

- Update 4.3.1 release notes with RC2 content
This pull request needs review by: @gzaidman

Update 4.3.1 release notes with RC2 content

---

source/documentation/upgrade-guide/appe-Manually_Updating_Hosts.html.md

- update command fixed.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@NirLevyRH)

fix update command

---

source/release/4.3.1/index.html.md

- Update release notes with 4.3.1 GA content

Update release notes with 4.3.1 GA content

---

source/download/alternate_downloads.html.md

- Update alternate dowload with 4.3.1 GA

Update alternate dowload with 4.3.1 GA

---

source/documentation/index.html.haml

- Update documentation home with 4.3.1 GA

Update documentation home with 4.3.1 GA

---

source/download/index.html.md

- Update download page with 4.3.1 GA

Update download page with 4.3.1 GA

---

source/index.html.haml

- Update home page with 4.3.1 GA

Update home page with 4.3.1 GA

---

source/release/4.3.2/index.html.md

- Create 4.3.2 release notes with RC1 content

Create 4.3.2 release notes

---

source/release/4.3.2/index.html.md

- Update 4.3.2 release notes with RC2 content

Update 4.3.2 release notes

---

source/develop/release-management/releases/4.3.z/release-management.html.md

- Updated 4.3.2 schedule adding RC2

Update 4.3.2 schedule

---

source/download/index.html.md

- Update download page with 4.3.2 GA

Update download page with 4.3.2 GA

---

source/index.html.haml

- Update home page with 4.3.2 GA

Update home with 4.3.2 GA

---

source/documentation/index.html.haml

- Update documentation page with 4.3.2 GA

Update documentation page with 4.3.2 GA

---

source/release/4.3.3/index.html.md

Add 4.3.3 RC1 release notes

---

source/develop/release-management/features/storage/cinderlib-integration.html.md

- Add manual steps needed to install the cinderlib libraries
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rollandf 
This pull request needs review by: @bennyz @shenitzky

Cinderlib: Add manual steps for installation

---

source/develop/release-management/features/storage/cinderlib-integration.html.md

This pull request needs review by: @rollandf

Add example for ceph

---

source/release/4.3.3/index.html.md

- Update 4.3.3 Release notes with RC2 content

Update 4.3.3 Release notes with RC2 content

---

source/documentation/install-guide/chap-System_Requirements.html.md

- Update requirements for 4.3 within Install Guide
This pull request needs review by: @tiraboschi

Update requirements for 4.3

---

source/release/4.3.3/index.html.md

- Update 4.3.3 release notes with RC3 content

Update 4.3.3 release notes

---

source/documentation/index.html.haml

Signed-off-by: Shirly Radco <sradco@redhat.com>
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco 
This pull request needs review by: @sandrobonazzola @didib @gregsheremeta

Update oVirt Metrics Store Installation Guide link

---

source/release/4.3.3/index.html.md

- Update 4.3.3 wit RC4 content

Update 4.3.3 wit RC4 content

---

source/release/4.3.3/index.html.md

- Update 4.3.3 release notes with GA content

Update 4.3.3 release notes with GA content

---

source/download/index.html.md

- Update download page with 4.3.3

Update download page with 4.3.3

---

source/documentation/index.html.haml

- Update documentation page with 4.3.3

Update documentation page with 4.3.3

---

source/documentation/admin-guide/chap-Users_and_Roles.html.md

See also:
https://bugzilla.redhat.com/1693816
https://bugzilla.redhat.com/1700655
-
-
-

Admin guide: Note about engine-backup and SSO files

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.4 schedule

---

source/release/4.3.4/index.html.md

Add 4.3.4 rc1 release notes

---

source/community/index.html.md
source/develop/infra/donate-hardware.html.md

Signed-off-by: Evgheni Dereveanchin <ederevea@redhat.com>
- add hardware donation page describing specs that we can use in oVirt infra
- add new chapter to the community index page linking to various ways to contribute
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jekader 
This pull request needs review by: @sandrobonazzola @eedri

Add hardware donation page

---

source/release/4.3.4/index.html.md

Update 4.3.4 release notes

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.4 RC2 schedule

---

source/develop/release-management/features/storage/incremental-backup.html.md
source/documentation/incremental-backup-guide/incremental-backup-guide.html.md

Updated feature page and guide:
Changed API for disk creation using diskattachments.
@rollandf

incremental backup: update API for disk creation

---

source/develop/developer-guide/vdsm/block-storage-domains.html.md

- added xleases
- fix description of metadata
- fix for description of leases
- fix description of ids
@rollandf, @vjuranek please review.

Update information about special volume on block storage

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.4 3rd RC

---

source/release/4.3.4/index.html.md

- Update 4.3.4 release notes with rc3 content

Update 4.3.4 release notes with rc3 content

---

source/blog/2019-04-15-ovn-security-groups.html.md

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @maiqueb 
This pull request needs review by: 
@mmirecki

blog: security groups on ovn networks

---

source/blog/2019-04-15-ovn-security-groups.html.md

- looking at https://www.ovirt.org/blog.html, it can be seen the thumbnail of the video is 
not properly placed. This commit addresses that.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @maiqueb 
@mmirecki

The thumbnail appears next to the sentence, not below

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.4 RC4 to schedule

---

source/documentation/ovirt-orb/index.html.md

- Update ovirt-orb page pointing to 4.3 repos

Update ovirt-orb page

---

source/release/4.3.4/index.html.md

- Update release notes with 4.3.4 rc4 content

Update notes with 4.3.4 rc4 content

---

source/documentation/install-guide/chap-oVirt_Nodes.html.md

-Fix bad link to older version  ISO
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @derbbre

Bad link to old version

---

source/documentation/index.html.haml

- Update documentation home with version 4.3.4

Update documentation with 4.3.4

---

source/download/index.html.md

- Update download page with version 4.3.4

Update download page with version 4.3.4

---

source/index.html.haml

- Update home page with version 4.3.4

Update home with version 4.3.4

---

source/release/4.3.4/index.html.md

- Update 4.3.4 release notes with GA content

Update 4.3.4 release notes with GA content

---

source/release/4.3.5/index.html.md

Add 4.3.5 RC1 release notes

---

source/release/4.3.4/index.html.md

- Update 4.3.4 with async 1 content

Update 4.3.4 with async 1 content

---

source/release/4.3.5/index.html.md

- Update 4.3.5 with rc2 content

Update 4.3.5 with rc2 content

---

source/release/4.3.4/index.html.md

- Update 4.3.4 with async content

Update 4.3.4 with async content

---

source/develop/release-management/releases/4.3.z/release-management.html.md

- Update 4.3.5 release schedule

Update 4.3.5 schedule

---

source/release/4.3.5/index.html.md

- Update 4.3.5 release notes with rc3 content

Update 4.3.5 release notes with rc3 content

---

source/develop/release-management/features/virt/coreos-ignition-support.html.md

Adding a feature page for CoreOS ignition support.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rgolan
This pull request needs review by: @evol262

Add ignition support feature page

---

source/documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html.md

- Missing / for top-level link in docs
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @derbbre

Bad link (missing top level /)

---

source/release/4.3.5/index.html.md

- Update 4.3.5 release notes with rc4 content

Update 4.3.5 release notes with rc4 content

---

source/release/4.3.5/index.html.md

- Update 4.3.5 release notes with rc5 content

Update 4.3.5 release notes with rc5 content

---

source/develop/release-management/features/storage/incremental-backup.html.md

Change-Id: I445d049911cb9616a8362827ad86dc2f1de02d89
Signed-off-by: Eyal Shenitzky <eshenitz@redhat.com>
@sandrobonazzola - please review

Incremental Backup: add Eyal Shenitzky as feature owner

---

source/community/about/board.html.md

- Updating oVirt Board members list following official announcement at
https://lists.ovirt.org/archives/list/board@ovirt.org/thread/NZ7CMRNPFAJAXTMGATO3ZNOYFA2SGP4Y/

Update oVirt Board members

---

source/release/4.3.5/index.html.md

- Update 4.3.5 release notes with GA content

Update 4.3.5 release notes with GA content

---

source/download/index.html.md

- Update download page with 4.3.5 GA

Update download page with 4.3.5 GA

---

source/index.html.haml

- Update home page with 4.3.5 GA

Update home page with 4.3.5 GA

---

source/release/4.3.5/index.html.md

- Update 4.3.5 with async 1 content

Update 4.3.5 with async 1 content

---

source/release/4.3.6/index.html.md

- Create 4.3.6 rc1 release notes

Create 4.3.6 rc1 release notes

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.6 schedule

---

source/release/4.3.5/index.html.md

- Update 4.3.5 with async 2 content

Update 4.3.5 with async 2 content

---

source/develop/release-management/features/virt/coreos-ignition-support.html.md

Updated version of the python script that creates and run
a Fedora CoreOS VM with ignition.
This pull request needs review by: @evol262

Update the example script for the ignition page

---

source/develop/release-management/releases/4.3.z/release-management.html.md

Add 4.3.6 rc2 to schedule

---

source/release/4.3.6/index.html.md

Update 4.2.6 notes with RC2

---

source/community/index.html.md

- Adding community projects to community page to get them some visibility.
This pull request needs review by: @nkovacne @zipurman @doron-fediuck @yuvalturg

Add community projects to community page

---

source/release/4.3.6/index.html.md

- disabling gpgcheck since packages are not signed

fix 4.3.6 workaround for 7.7

---

source/develop/release-management/features/network/copy-host-networking.html.md

Add feature page for Copy Host Networking

---

data/authors.yml

per https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md
- added my name to the author information.
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rolfedh

Added my author information to data/authors.yml

---

source/release/4.3.6/index.md

- Update 4.3.6 notes with rc3 content
- Use new release notes template

Update 4.3.6 notes with rc3 content

---

source/develop/release-management/releases/4.3.z/release-management.md

Add 4.3.6 rc4 to schedule

---

source/release/4.3.6/index.md

- Update 4.3.6 notes with rc4 content

Update 4.3.6 notes with rc4 content

---

source/release/4.3.6/index.md

- Updated 4.3.6 notes with RC5 content

Update 4.3.6 notes

---

Gemfile.lock
source/index.haml

Reverts oVirt/ovirt-site#2094, didn't work

Revert "Banner for Rome event"

---

source/index.haml

- Adding 50px of margin to the banner in home page avoiding to overlap
the section with grey background.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @sandrobonazzola
This pull request needs review by: @lwrigh

Add margin to home page banner

---

Gemfile
Gemfile.lock
_config.yml

Fixes issue #2086
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @duck-rh 
This pull request needs review by: ???

WIP: add asciidoc support

---

source/develop/release-management/releases/4.3.z/release-management.md

- Update 4.3.6 with rc6 schedule

Update 4.3.6 with rc6 schedule

---

source/release/4.3.6/index.md

- Updated 4.3.6 notes with rc6 content

Updated 4.3.6 notes with rc6 content

---

source/develop/release-management/releases/4.3.z/release-management.md

- Update 4.3.6 schedule with GA

Update 4.3.6 schedule with GA

---

source/download/alternate_downloads.md

- Update alternate download with 4.3.6 GA

Update alternate download with 4.3.6 GA

---

source/download/index.md

- Update download page with 4.3.6 GA

Update download page with 4.3.6 GA

---

source/documentation/index.haml

- Update documentation for 4.3.6 GA

Update documentation for 4.3.6 GA

---

source/index.haml

Update home for 4.3.6 GA

---

source/release/4.3.6/index.md

- Update 4.3.6 with GA content

Update 4.3.6 with GA content

---

source/download/node.md

download/node: misssing frontmatter

---

source/documentation/install-guide/chap-oVirt_Nodes.md

- Update Node Install Guide pointing to 4.3.6 ISO

Update Node Install Guide pointing to 4.3.6 ISO

---

source/download/node.md

- Update Node page links to 4.3.6 ISO

Update Node page links to 4.3.6 ISO

---

source/release/4.3.6/index.md

- Update 4.3.6 release notes with async content

Update 4.3.6 release notes with async content

---

source/develop/release-management/features/network/copy-host-networking.html.md

state that labels should be copied from source interfaces to destination ones
This pull request needs review by: @almusil @mburman5

copy-host-networking: labels

---

source/develop/release-management/features/network/copy-host-networking.html.md

copy-host-networking: Add REST API call definition

---

source/release/4.3.7/index.md

Add 4.3.7 rc1 release notes

---

source/release/4.3.7/index.md

Update 4.3.7 release notes

---

source/develop/release-management/features/network/copy-host-networking.html.md

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @almusil 
@mburman5 
@rolfedh

copy-host-networking: Fix some wrong assumptions

---

source/download/browsers_and_mobile.md

Fixes issue #2133
- Add missing frontmatter to download/browsers_and_mobile, solving error 404.

download/browsers_and_mobile: misssing frontmatter

---

source/develop/release-management/releases/4.3.z/release-management.md

Add 4.3.7 rc3 to schedule

---

source/release/4.3.7/index.md

- Update 4.3.7 release notes with rc3 content

Update 4.3.7 release notes with rc3 content

---

source/release/4.3.6/index.md

- Add bug #1749202 to 4.3.6 release notes. Bug was fixed in 4.3.6 and moved to QE for 4.3.7

Add bug #1749202 to 4.3.6 release notes

---

source/community/user-stories/users-and-providers.md

- Drop companies not in the board anymore

Drop companies not in the board anymore

---

source/release/4.3.7/index.md

- Update 4.3.7 release notes with rc4 content

Update 4.3.7 release notes with rc4 content

---

source/develop/release-management/releases/4.3.z/release-management.md
source/documentation/index.haml
source/documentation/install-guide/chap-oVirt_Nodes.md
source/documentation/upgrade-guide/appe-Manually_Updating_Hosts.md
source/download/alternate_downloads.md
source/download/index.md
source/download/node.md
source/index.haml
source/release/4.3.7/index.md

Release ovirt 4.3.7 GA

---

source/release/4.3.8/index.md

Release notes for 4.3.8 RC1

---

source/documentation/install-guide/chap-System_Requirements.md

Update the required CPU list for oVirt engine
Signed-off-by: Asaf Rachmani arachman@redhat.com

Update CPU list

---

source/release/4.3.8/index.md

Update release notes for oVirt 4.3.8 rc2

---

source/release/4.4.0/index.md

- Create 4.4.0 Alpha release notes

Create 4.4.0 Alpha release notes

---

source/documentation/index.haml
source/download/alpha.md
source/index.haml

- Add links for 4.4 alpha
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):

Add links for 4.4 alpha

---

source/documentation/admin-guide/chap-Storage.md

Fixes issue #1597
- Fixed chap-Storage markdown solving also some 404 error due to wrong way to reference internal anchors.

admin guide: fix chap-Storage markdown

---

source/documentation/vmm-guide/chap-Installing_Linux_Virtual_Machines.md

Fixes issue #2144
- Fixed chap-Installing_Linux_Virtual_Machines markdown solving also some 404 error due to wrong references to other pages sections.

vmms guide: fix chap-Installing_Linux_Virtual_Machines markdown

---

source/documentation/upgrade-guide/chap-Updates_between_Minor_Releases.md

Fixes issue #1938
- adapted chap-Updates_between_Minor_Releases to oVirt

upgrade guide: adapt to oVirt

---

source/documentation/index.haml

Fixes issue #1670
- Added links to REST API, SDK and Ansible for oVirt.
This pull request needs review by: @gregsheremeta , @mwperina

documentation: add links to coding docs

---

source/release/4.3.8/index.md

Update release notes for 4.3.8 rc3

---

source/documentation/vmm-guide/chap-Introduction.md

- Fix broken image.
* before
```
$ cat ovirt-site/source/documentation/vmm-guide/chap-Introduction.md
...
<td><center><img src="../images/greencheck.png"></center></td>
...
```
* after
```
$ cat ovirt-site/source/documentation/vmm-guide/chap-Introduction.md
...
<td><center><img src="/images/vmm-guide/greencheck.png"></center></td>
...
```
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): ( @chhanz )

Fix broken image : vmm-guide/chap-Introduction.md

---

source/documentation/index.haml
source/documentation/upgrade-guide/appe-Manually_Updating_Hosts.md
source/documentation/upgrade-guide/chap-Updates_between_Minor_Releases.md
source/download/alternate_downloads.md
source/download/index.md
source/download/node.md
source/index.haml
source/release/4.3.8/index.md

Release 4.3.8

---

source/release/4.3.9/index.md

Add 4.3.9 rc1 release notes

---

source/release/4.4.0/index.md

Update index.md for 4.4.0 alpha 5

---

source/release/4.3.9/index.md

Update index.md for 4.3.9 RC2

---

source/develop/release-management/features/virt/hot-unplug-memory.md

- Memory hot unplug guest configuration for el8 mentioned.

Add memory hot unplug instructions for el8

---

source/release/4.3.9/index.md

Update index.md for 4.3.9 rc3

---

source/release/4.4.0/index.md

Update index.md for 4.4.0 alpha7

---

source/release/4.3.9/index.md

Update index.md w/ release notes for 4.3.9 RC4

---

source/release/4.3.9/index.md

Update w/ release notes for 4.3.9 GA

---

source/index.haml

Update info for 4.3.9

---

source/release/4.3.9/index.md

- Add missing bugs to 4.3.9 release notes

4.3.9: add missing bugs in release notes

---

source/develop/release-management/features/storage/incremental-backup.md

- Fix edit disk request from POST to PUT in the incremental backup feature page
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @shenitzky 

Incremental backup: Fix edit disk request from POST to PUT

---

source/download/beta.md
source/index.haml
source/release/4.4.0/index.md

Release 4.4.0_beta1

---

source/release/4.4.0/index.md

- explain how to upload / download images via REST API/SDK

Update 4.4.0 beta release notes

---

source/release/4.4.0/index.md

Update 4.4.0 release notes for beta2

---

source/release/4.4.0/index.md

Update release notes for 4.4.0 beta2 re-spin

---

source/release/4.4.0/index.md

- Update 4.4.0 beta3 release notes

Update 4.4.0 beta3 release notes

---

source/download/beta.md
source/download/beta_alternate_downloads.md
source/release/4.4.0/index.md

- Update website with 4.4 beta 4

4.4.0 beta4: update website

---

source/release/4.3.10/index.md

Create release notes for 4.3.10 RC1

---

source/release/4.3.10/index.md

Update release notes for 4.3.10 RC2

---

_config.yml
source/develop/index.md

- fix broken link to develop/resources
- fix broken link to develop/reports

Fix some broken links

---

source/release/4.3.10/index.md

Update index.md for 4.3.10 rc3 release

---

source/release/4.4.0/index.md

Update index.md for 4.4.0 rc1 release

---

source/documentation/index.haml
source/download/beta.md
source/download/beta_alternate_downloads.md
source/download/node.md
source/index.haml

- Update references to 4.4.0 RC

Update references to 4.4.0 RC

---

source/release/4.3.10/index.md

Update index.md for 4.3.10 rc4

---

source/release/4.4.0/index.md

Update imdex.md for oVirt 4.4.0 rc2

---

source/documentation/common/collateral_files/ovirt-attributes.adoc
source/documentation/common/install/assembly-Installing_Hosts_for_RHV.adoc
source/documentation/common/install/assembly-Installing_the_self-hosted_engine_deployment_host.adoc
source/documentation/common/install/con-Recommended_practices_for_configuring_host_networks.adoc
source/documentation/common/install/proc-Adding_self-hosted_engine_nodes_to_the_Manager.adoc
source/documentation/common/install/proc-Adding_standard_hosts_to_the_Manager.adoc
source/documentation/common/install/proc-Automating_RHVH_Deployment.adoc
source/documentation/common/install/proc-Configuring_a_Host_for_PCI_Passthrough.adoc
source/documentation/common/install/proc-Configuring_the_Red_Hat_Virtualization_Manager.adoc
source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_Cockpit.adoc
source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc
source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/install/proc-Installing_Red_Hat_Enterprise_Linux_Hosts.adoc
source/documentation/common/install/proc-Installing_Red_Hat_Virtualization_Hosts.adoc
source/documentation/common/install/proc-Installing_the_Websocket_Proxy_on_a_different_host.adoc
source/documentation/common/install/proc-Reinstalling_Hosts.adoc
source/documentation/common/install/ref-Custom_Partitioning_RHVH.adoc
source/documentation/common/install/ref-Red_Hat_Virtualization_Guest_Agents_and_Drivers.adoc
source/documentation/common/prereqs/ref-Database_Server_Firewall_Requirements.adoc
source/documentation/common/she/proc_Manually_installing_the_appliance.adoc
source/documentation/common/upgrade/snip-RHV_upgrade_prerequisites.adoc
source/documentation/index.haml
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/index.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc
source/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/index.adoc

Sync with latest downstream install guides for 4.4.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @pmkovar 

Sync with downstream install guides for 4.4

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc

- Added documentation on modules to be enabled on oVirt Engine side
This pull request needs review by: @pmkovar @stoobie

docs: install: document modules on ovirt engine

---

source/documentation/common/admin/proc-Removing_Red_Hat_Virtualization_Manager.adoc
source/documentation/common/arch/con-RHV_key_components.adoc
source/documentation/common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc
source/documentation/common/database/proc-Installing_and_Configuring_Data_Warehouse_on_a_Separate_Machine.adoc
source/documentation/common/database/proc-Migrating_the_Data_Warehouse_Database_to_a_Separate_Machine.adoc
source/documentation/common/database/proc-Migrating_the_Data_Warehouse_Service_to_a_Separate_Machine.adoc
source/documentation/common/database/proc-Migrating_the_self-hosted_engine_database_to_a_remote_server.adoc
source/documentation/common/database/proc-Preparing_a_Local_Manually-Configured_PostgreSQL_Database.adoc
source/documentation/common/database/proc-Preparing_a_Remote_PostgreSQL_Database.adoc
source/documentation/common/prereqs/ref-DNS_Requirements.adoc
source/documentation/common/prereqs/ref-Database_Server_Firewall_Requirements.adoc
source/documentation/common/prereqs/ref-Host_CPU_Requirements.adoc
source/documentation/common/prereqs/ref-Host_Device_Assignment_Requirements.adoc
source/documentation/common/prereqs/ref-Host_Firewall_Requirements.adoc
source/documentation/common/prereqs/ref-Host_PCI_Device_Requirements.adoc
source/documentation/common/prereqs/ref-Host_Storage_Requirements.adoc
source/documentation/common/prereqs/ref-Manager_Browser_Requirements.adoc
source/documentation/common/prereqs/ref-Manager_Client_Requirements.adoc
source/documentation/common/prereqs/ref-Manager_Firewall_Requirements.adoc
source/documentation/common/prereqs/ref-Manager_Hardware_Requirements.adoc
source/documentation/common/prereqs/ref-Manager_Operating_System_Requirements.adoc
source/documentation/common/storage/assembly-Preparing_Storage_for_RHV.adoc
source/documentation/common/storage/proc-Adding_iSCSI_Storage.adoc
source/documentation/common/storage/proc-Customizing_Multipath_Configurations_for_SAN_Vendors.adoc
source/documentation/common/storage/proc-Preparing_Local_Storage.adoc
source/documentation/common/storage/ref-Preparing_FCP_Storage.adoc
source/documentation/common/storage/ref-Preparing_Red_Hat_Gluster_Storage.adoc
source/documentation/common/storage/ref-Preparing_iSCSI_Storage.adoc
source/documentation/common/storage/ref-Recommended_Settings_for_Multipath.conf.adoc

- Additional install updates for 4.4 based on @sandrobonazzola's review
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @pmkovar 

Additional install updates for 4.4

---

source/release/4.4.0/index.md

Update index.md for 4.4.0 GA

---

source/release/4.3.10/index.md

Update index.md for 4.3.10 rc5

---

source/download/node.md

Update node.md for 4.4 GA

---

source/download/node.md

Signed-off-by: Nir Levy <nlevy@redhat.com>
-
-
-

Update references to 4.4.1 RC

---

source/release/4.4.1/index.md

- Added 4.4.1 rc1 release notes

Create index.md for 4.4.1 rc1

---

source/release/4.4.1/index.md

- Update 4.4.1 release notes with RC2 content

Update index.md for 4.4.1 rc2

---

source/develop/release-management/features/grafana/grafana.md

I am mainly pushing this because I want a link I can use in engine-setup for providing more information. Later on we'll obviously need to actually add this information...

Add grafana feature page/dir

---

source/release/4.3.10/index.md

- Updated release notes for 4.3.10 GA

Update index.md for 4.3.10 GA

---

source/.htaccess

Gives better control over redirects to website maintainers.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @duck-rh 

move vhost redirects inside .htaccess

---

source/release/4.4.1/index.md

- Update release notes with 4.4.1 rc3 content

Update index.md for 4.4.1 rc3

---

source/documentation/index.haml

- Update Documentation to point to the new release notes

Update Documentation to point to the new release notes

---

source/release/4.4.1/index.md

- Update 4.4.1 release notes with rc4 content

Update 4.4.1 release notes with rc4 content

---

setup.sh

add missing imagemagick dep in setup script

---

source/develop/release-management/features/storage/incremental-backup.md

1. Add new suggested checkpoints API
2. Update the existing documentation according to latest changes.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @shenitzky 

incremental-backup.md: add checkpoints API and update documentation

---

source/release/4.4.1/index.md

-  Update 4.4.1 notes with rc5 content

Update 4.4.1 notes with rc5 content

---

source/documentation/common/upgrade/proc-Changing_Virtual_Machine_Cluster_Compatibility.adoc
source/documentation/common/upgrade/proc-Changing_the_Cluster_Compatibility_Version.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_all_hosts_in_a_cluster.adoc

- fix broken links to images within upgrade guide
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sandrobonazzola  

upgrade guide: fix broken images

---

.travis.yml
source/develop/internal/guest-agent/windows.md
source/develop/release-management/features/infra/command-coordinator-flows-and-events.md
source/develop/release-management/features/infra/foremanintegration.md
source/develop/release-management/features/infra/python-sdk.md
source/develop/release-management/features/infra/testingframework.md
source/develop/release-management/features/network/directhostaddress.md
source/develop/release-management/features/network/ethtool-options.md
source/develop/release-management/features/network/ipv6-support.md
source/develop/release-management/features/network/network-custom-properties.md
source/develop/release-management/features/network/networklinking.md
source/develop/release-management/features/network/openvswitch/native-openvswitch.md
source/develop/release-management/features/sla/cpu-thread-handling.md
source/develop/release-management/features/sla/detailedquota.md
source/develop/release-management/features/sla/engine-high-availability.md
source/develop/release-management/features/sla/hosted-engine-vm-management.md
source/develop/release-management/features/sla/momintegration.md
source/develop/release-management/features/sla/ovirtschedulerapi.md
source/develop/release-management/features/sla/trusted-compute-pools.md
source/develop/release-management/features/storage/detailedfloatingdisk.md
source/develop/release-management/features/storage/snapshots-overview.md
source/develop/sla/host-mom-policy.md
source/develop/sla/network-qos.md
source/documentation/intro-vm-portal/chap-Managing_virtual_machines.adoc
source/documentation/intro-vm-portal/index.adoc
source/documentation/intro-vm-portal/topics/Editing_virtual_machines.adoc
source/documentation/intro-vm-portal/topics/Graphical_User_Interface_elements.adoc

Fixes issue #2074
- Finished to fix broken images
- Turn on automation checking broken images per commit

Fix broken images and enable automation

---

source/_includes/footer.haml
source/_plugins/index_pages.rb
source/_plugins/jekyll_generated_page.rb
source/_plugins/ovirt_events_pages.rb

Fixes issue #2263
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @duck-rh 

Mark generated pages and stop displaying edit/bug links

---

source/develop/release-management/features/network/copy-host-networking.html.md

net: Add limitation documentation to copy-host

---

source/documentation/administration_guide/chap-Clusters.adoc
source/documentation/administration_guide/chap-Data_Centers.adoc

- Fix section title out of sequence warnings
This pull request needs review by: @stoobie / @pmkovar

Fix section title out of sequence warnings

---

source/develop/release-management/features/storage/incremental-backup.md

I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @shenitzky 

Incremental backup: fix checkpoints XML examples

---

source/release/4.4.1/index.md

- Update 4.4.1 release notes for GA

Update 4.4.1 release notes for GA

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/download/node.md
source/index.haml

Releasing 4.4.1 GA

---

source/develop/api/rest-api/rest-client-addon.md

- fix rest-client-addon markdown

develop: fix rest-client-addon markdown

---

source/release/4.3.10/index.md

Fixes issue #2288
- Fix requirement node on RHEL / CentOS: 7.8 is needed
This pull request needs review by: @BSipos-RKF

Fix release notes for 4.3.10

---

source/develop/release-management/features/storage/incremental-backup.md

Removing to_checkpoint_id from 'Starting full backup' section
response example and update the description.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @shenitzky 

Incremental-backup.md: fix Starting full backup example

---

source/release/4.4.1/index.md

Update index.md for 4.4.1.1

---

source/release/4.4.1/index.md

Fix broken community link

---

source/release/4.4.1/index.md

Update index.md for 4.4.1.4

---

source/develop/internal/guest-agent/understanding-guest-agents-and-other-tools.md

- Refresh "Understanding Guest Agents and other tools"
This pull request needs review by: @ahadas , @nyoxi , @Gal-Zaidman

Refresh understanding-guest-agents-and-other-tools

---

source/release/4.4.1/index.md

Update index.md (Update contributor's name)

---

source/release/4.4.1/index.md

Update index.md with fixed contributors data

---

.travis.yml
test.rb

- Run htmlproofer using multiple processes making it faster

automation: run htmlproofer in parallel

---

source/release/4.4.2/index.md

Create index.md for 4.4.2

---

source/develop/release-management/features/virt/nvdimm-device.md

- Initial version of NVDIMM feature page. It's WIP, will be updated as needed.

Add NVDIMM feature page

---

source/release/4.4.2/index.md

Update index.md for 4.4.2 rc2

---

source/release/4.4.2/index.md

Update index.md for 4.4.2 rc3

---

source/release/4.4.2/index.md

In case of the non-GA release, the previous release notes should point to the "latest" tag.
Going to fix the generator code as well. 
-
-
-

Update a link to the previous release notes.

---

source/release/4.4.2/index.md

Update index.md for 4.4.2 rc4

---

source/release/4.4.2/index.md

- Update 4.4.2 release notes with RC5 content

Update 4.4.2 release notes for RC5

---

source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-3.adoc

Signed-off-by: Asaf Rachmani <arachman@redhat.com>

upgrade_guide: Fix 4.3 repo link

---

source/release/4.4.2/index.md

Update index.md for 4.4.2 GA

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml

- point to 4.4.2 as current stable release

point to 4.4.2 as current stable release

---

source/release/4.4.3/index.md

Create index.md for 4.4.3 rc1

---

test.rb

Fixes issue #1228
- automation: enable internal link checks

automation: enable internal link checks

---

source/develop/infra/testing/lago/testing-engine-patches-with-lago.md
source/develop/release-management/features/integration/ovirtappliance.md
source/develop/release-management/features/network/detailednetworklinking.md
source/develop/release-management/features/network/migration-network.md
source/develop/release-management/features/network/setupnetworks.md
source/develop/release-management/features/network/ucs-integration.md
source/develop/release-management/features/sla/engine-high-availability.md
source/develop/release-management/features/sla/optaplanner.md
source/develop/release-management/features/sla/vm-coredump.md
source/develop/release-management/features/storage/cinder-integration.md
source/develop/release-management/features/storage/online-virtual-drive-resize.md
source/develop/release-management/features/storage/reduce-luns-from-sd.md
source/develop/release-management/features/virt/guestagentopensuse.md
source/develop/release-management/features/virt/guestagentsles.md

- Fix some external broken links

Fix some external broken links

---

source/develop/release-management/features/network/lldp.md

lldp: fix broken link

---

source/release/4.4.2/index.md

- Updated 4.4.2 release notes adding oVirt Node

4.4.2: update release notes

---

source/develop/release-management/features/gluster/gluster-hooks-management.md

Fixed gluster hook url

---

source/develop/release-management/features/gluster/gluster-swift-management.md
source/develop/release-management/features/gluster/gluster-volume-performance-statistics.md
source/develop/release-management/features/gluster/glustervolumequota.md
source/develop/release-management/features/gluster/select-network-for-gluster.md

- fix broken links
- fix markdown
This pull request needs review by: @gobindadas

gluster: fix gluster feature pages

---

source/documentation/admin-guide/virt/console-client-resources.md

Fixes issue #2268
- the page was linked from multiple places and it requires too many fixes for pointing elsewehere.

console-client-resources: restore page

---

source/develop/release-management/features/storage/cd-block-storage.md

Add desing doc for functions and flows related to management fo CD-ROM:
for inserting, ejecting and changing CD.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @vjuranek 

cd-change: add design doc for CD management

---

source/release/4.4.3/index.md

- Updated 4.4.3 release notes with RC2 content

Update index.md for 4.4.3 rc2

---

source/develop/release-management/features/virt/hot-plug-cpu.md

Fixes issue #1933
- fix markdown making OS compatibility list readable

hot-plug-cpu: fix markdown

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with RC3 content

Update index.md for 4.4.3 rc3

---

source/develop/release-management/features/virt/tpm-device.md

- Initial version of TPM feature page. It's WIP, will be updated as needed.

Add TPM feature page

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with RC4 content

Update index.md for 4.4.3 rc4

---

source/develop/release-management/features/sla/external-scheduling-proxy.md

- Fix markdown for external-scheduling-proxy
This pull request needs review by: @MarSik

external-scheduling-proxy: fix markdown

---

source/develop/release-management/features/infra/fenceagents.md

- fix broken markdown on fenceagents page
This pull request needs review by: @oliel

fenceagents: fix broken markdown

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with rc5 content

Update index.md for 4.4.3 rc5

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with rc6 content

Update index.md for 4.4.3 rc6

---

source/develop/developer-guide/engine/engine-setup.md
source/develop/developer-guide/engine/otopi.md

otopi and engine-setup: Minor fixes

---

source/release/4.4.3/index.md

- Update 4.4.3 release notest with rc7 content

Update index.md for 4.4.3 rc7

---

source/develop/release-management/features/virt/nvdimm-device.md

- Data persistence limitation added to NVDIMM feature page.

nvdimm: Add data persistence limitation

---

source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc

Fixes issue #2381
In the topic "Updating the Ovirt Engine", added a prerequistie with link to the ovirt repo rpm.

BZ1894505 Added ovirt repo as prereq in topic on updating engine.

---

source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc

BZ1894505-1 fixed typo

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with RC8 content

Update index.md for 4.4.3 rc8

---

source/release/4.4.3/index.md

-  4.4.3_rc8: add bugs missed in previous update

4.4.3_rc8: add bugs missed in previous update

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.4.3/index.md

Release 4.4.3 GA

---

source/download/rpms_and_gpg.md

- Added a few mirrors
- Refreshed page content

rpms_and_gpg: refresh

---

source/release/4.4.4/index.md

- Add 4.4.4 release notes with RC1 content

Create index.md for 4.4.4 rc1

---

source/release/4.4.3/index.md

- Update 4.4.3 release notes with 4.5 cluster level

Update 4.4.3 release notes with 4.5 cluster level

---

source/release/4.4.4/index.md

- Updated 4.4.4 release notes with RC2 content

Update index.md for 4.4.4 rc2

---

source/release/4.4.4/index.md

- Updates content for 4.4.4 RC3 release notes

Update index.md for 4.4.4 rc3

---

source/develop/release-management/features/sla/aggregate-qos.md

- Fix markdown on aggregate-qos page

aggregate-qos: fix markdown

---

source/release/4.4.3/index.md

- Updates content for 4.4.3 async release

Update index.md for 4.4.3 async release

---

source/release/4.4.4/index.md

- Updates content for 4.4.4 RC4

Update index.md for 4.4.4 rc4

---

source/release/4.4.4/index.md

- Updates content for 4.4.4 RC5

Update index.md for 4.4.4 RC5

---

source/release/4.4.4/index.md

Update index.md for 4.4.4 rc6

---

source/community/index.md
source/develop/localization.md

Fixes issue #2309
- fix onboarding translators steps and point to them from community page.

community: fix onboarding translators docs

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.4.4/index.md

Release oVirt 4.4.4 GA

---

source/documentation/common/install/appe-Set_up_Cinderlib.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/index.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc

- Add cinderlib integration documentation appendix to install guides

documentation: add cinderlib documentation

---

source/_sass/lib/site.sass
source/community/get-involved/donate-hardware.md
source/index.haml

- make hardware donation request more visible. No resources donated in last few years and we are out of warranty.

Improve donate hardware visibility

---

source/develop/developer-guide/vdsm/developers.md
source/develop/developer-guide/vdsm/nose-tests.md
source/develop/release-management/features/virt/for-ppc64.md
source/develop/troubleshooting-nfs-storage-issues.md

Update git clone example to the recommended URL.

vdsm: Update git url

---

source/documentation/common/collateral_files/ovirt-attributes.adoc

- align with downstream configuration

documentation: align with downstream configuration

---

source/documentation/administration_guide/chap-monitoring_and_observability.adoc
source/documentation/administration_guide/topics/Configure_grafana.adoc
source/documentation/administration_guide/topics/Grafana_overview.adoc
source/documentation/administration_guide/topics/Install_collectd_and_rsyslog.adoc
source/documentation/administration_guide/topics/Sending_metrics_to_ELK.adoc

- administration guide: update monitoring chapter
This pull request needs review by: @stoobie @emarcusRH

administration guide: update monitoring chapter

---

source/develop/developer-guide/sonar-with-ovirt.md

- updated links to Sonar
- markdown fixes
This pull request needs review by: @mwperina or @pkliczewski

sonar-with-ovirt: updated links to Sonar

---

source/release/index.md

Created index.md for 4.4.5 RC1

---

source/release/4.4.5/index.md

- Updates content for 4.4.5 RC2

Update index.md for 4.4.5 rc2

---

source/develop/dev-process/working-with-gerrit.md
source/develop/developer-guide/vdsm/developers.md

- minor fixes to working-with-gerrit guide
- clarifications of testing procedures in vdsm developer guide
- point users to correct venv setup in vdsm developer guide
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @RomanBednar

Fixes to developer guide

---

source/develop/release-management/features/virt/bochs-display.md

- bochs-display feature page.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @smelamud 

Added bochs-display feature page.

---

source/develop/release-management/features/metrics/hypervisors-and-engine-setup.md
source/develop/release-management/features/metrics/metrics-store-all-in-one.md
source/develop/release-management/features/metrics/metrics-store-collected-metrics.md
source/develop/release-management/features/metrics/metrics-store-installation.md
source/develop/release-management/features/metrics/metrics-store-schema.md
source/develop/release-management/features/metrics/metrics-store.md
source/develop/release-management/features/metrics/setting-up-viaq-logging.md

Signed-off-by: Shirly Radco sradco@redhat.com
Updated the metrics feature pages documentation with a deprecation notice.
I confirm that this pull request was submitted according to the contribution guidelines:@sradco
This pull request needs review by: @sandrobonazzola @emarcusRH

Update metrics store feature pages with deprecation notice

---

source/release/4.4.5/index.md

- Update content for 4.4.5 RC3

Update index.md for 4.4.5 RC3

---

.travis.yml

Related-To: #2412
- Detect non-breaking spaces and fail if found.
This pull request needs review by: @didib

automation: detect non-breaking spaces

---

source/release/4.4.5/index.md

- Updated content for 4.4.5 RC4

Update index.md for 4.4.5 RC4

---

source/release/4.4.5/index.md

- Updated content for 4.4.5 RC5

Update index.md for 4.4.5 RC5

---

source/release/4.4.5/index.md

- Updated content for 4.4.5 RC6

Update index.md for 4.4.5 RC6

---

source/develop/release-management/features/virt/nvram-data.md

- Introduce secure boot NVRAM data persistence feature page.
This pull request needs review by: @ahadas @nyoxi @smelamud

NVRAM data persistence feature page

---

source/develop/release-management/features/virt/tpm-device.md

- TPM feature page update according to the recent progress.
This pull request needs review by: @ahadas @nyoxi @smelamud

TPM feature page update

---

source/release/4.4.5/index.md

- Updated content for 4.4.5 RC7

Update index.md for 4.4.5 RC7

---

source/release/4.4.5/index.md

- Updated content for 4.4.5 RC8

Update index.md for 4.4.5 RC8

---

source/develop/release-management/features/network/sriov-live-migration.md

- Add feature page for SR-IOV live migration

Add feature page for sriov live migration

---

source/develop/release-management/features/network/sriov-live-migration.md

Use correct XML example in sriov live migration feature page

---

source/documentation/common/collateral_files/ovirt-attributes.adoc

- update URL_vernum_satellite to 6.7

docs: ovirt attr: update satellite version

---

source/release/4.4.5/index.md

Update index.md for 4.4.5 GA

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml

Release 4.4.5 GA

---

source/develop/release-management/features/network/sriov-live-migration.md

Add another limitations to the sriov live migration page

---

source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc

- Updated proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI aligning with downstream content

docs: install: update SHE procedure

---

source/release/4.4.5/index.md

- Update 4.4.5 with async #1 content

Update 4.4.5 with async #1 content

---

source/release/4.4.6/index.md

Create index.md for 4.4.6 RC1

---

source/release/4.4.6/index.md

- Updated content for 4.4.6 RC2

Update index.md for 4.4.6 RC2

---

source/develop/developer-guide/readme_template.md

- Add readme template to dev guide
This pull request needs review by: @didib

Add readme template to dev guide

---

source/download/rpms_and_gpg.md

- Update GPG with the current information

Update GPG with the current information

---

source/release/4.4.6/index.md

- Updated the content for 4.4.6 rc3

Update index.md for 4.4.6 rc3

---

.github/workflows/website_tests.yml

This branch is used to test and possibly fix problems while upgrading our build OS.
DO NOT MERGE please, it needs to be in sync with the our builder host.

Update builder to F33

---

source/download/rpms_and_gpg.md

- Updates formatting of the keys table

Update formatting of the currently used keys table

---

source/download/alternate_downloads.md
source/download/index.md

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1948429
- Add note about enabling beta channels on RHEL beta releases

RHEL: add note for RHEL beta repos

---

source/documentation/index.haml
source/release/4.4.6/index.md

- 4.4.6: update with rc4 content

4.4.6: update with rc4 content

---

source/download/alternate_downloads.md
source/download/index.md

- Add missing baseos beta for 8.4-beta

Add missing baseos beta for 8.4-beta

---

source/release/4.4.6/index.md

- Updated content for 4.4.6 RC5

Update index.md for 4.4.6 rc5

---

source/release/4.4.6/index.md

- Updated content for 4.4.6 RC6

Update index.md for 4.4.6 RC6

---

source/_sass/lib/site.sass

Fixes issue #2413
- Add CSS fix
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @bencurio 

Fixes oVirt/ovirt-site#2413

---

source/develop/release-management/features/storage/managed-block-storage-copy.md

- Add feature page for Managed Block Storage copy
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @bennyz

Add feature page for Managed Block Storage copy

---

source/release/4.4.6/index.md

Add 4.4.6 async 1 updates

---

source/community/index.md
source/develop/index.md
source/develop/release-management/features/grafana/grafana.md
source/develop/release-management/features/storage/single-disk-snapshot.md
source/develop/release-management/features/virt/high-performance-vm.md
source/documentation/index.haml

- adding .html extension to some urls where it has been found missing.

add .html extension to some url

---

source/develop/release-management/features/virt/tpm-device.md

- The feature page updated in accordance to the current implementation.

Update TPM feature page according to the feature implementation

---

source/develop/release-management/features/virt/tpm-device.md

- it's better to not -> it's better not to
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @ahadas 

Minor fix in the TPM feature page

---

source/release/4.4.6/index.md

- updated 4.4.6 release notes with async updates

updated 4.4.6 release notes with async updates

---

source/release/4.4.6/index.md

- update 4.4.6 with async content

update 4.4.6 with async content

---

source/develop/developer-guide/vdsm/fake.md

- mark ovirt-vdsmfake as unmaintained

mark ovirt-vdsmfake as unmaintained

---

source/develop/release-management/features/integration/windows-guest-tools.md

- windows-guest-tools: mark as removed
This pull request needs review by: @lveyde @Gal-Zaidman

windows-guest-tools: mark as removed

---

source/develop/release-management/features/virt/intial-run-vm-tab.md

- intial-run-vm-tab: fix markdown
This pull request needs review by: @rgolangh

intial-run-vm-tab: fix markdown

---

source/develop/release-management/features/sla/quota.md

sla/quota.md: fix markdown

---

Gemfile.lock

- Update bundle, extend PR #2496

build: bundle update

---

.github/workflows/website_tests.yml
README.md

- archive generated website allowing to review the results.
- document how to consume archived artifacts
This pull request needs review by: @duck-rh @stoobie

archive generated website

---

source/develop/release-management/features/infra/detailedhostpmmultipleagents.md

- hostpmmultipleagents: fix markdown
This pull request needs review by: @emesika

hostpmmultipleagents: fix markdown

---

source/community/report-a-bug.md
source/develop/devdocs.md
source/develop/index.md
source/develop/integration/index.md
source/develop/qa/index.md

- Making developer section more welcoming
This pull request needs review by: @oVirt/ovirt-site  @mwperina @michalskrivanek @ahadas @shenitzky @janoszen @stoobie

Developers welcoming

---

source/release/4.4.7/index.md

Created index.md for 4.4.7 RC1

---

source/release/4.4.7/index.md

- Updated the supported OS types and versions section

Update index.md for supported OS versions

---

source/release/4.4.7/index.md

- 4.4.7: updated with rc2 content

4.4.7: updated with rc2 content

---

source/release/4.4.7/index.md

Update index.md for 4.4.7 RC3

---

source/release/4.4.7/index.md

- Updated the content for 4.4.7 RC4

Update index.md for 4.4.7 RC4

---

source/release/4.4.7/index.md

- Updated content for 4.4.7 RC5

Update index.md for 4.4.7 RC5

---

data/authors.yml
source/develop/dev-process/working-with-gerrit.md

- Improved instructions on how to create and use gerrit username
PR#1 of this original PR: https://github.com/oVirt/ovirt-site/pull/2513
This pull request needs review by: @ahadas @liranr23 @sandrobonazzola @nirs

working with gerrit tutorial - Improved instructions on how to create and use gerrit username   

---

source/develop/dev-process/working-with-gerrit.md

- Improved formatting
- Fixed topic branch outdated link
PR#2 of this original PR: https://github.com/oVirt/ovirt-site/pull/2513
This pull request needs review by: @ahadas @liranr23 @sandrobonazzola @nirs

improve working with gerrit tutorial - improved formatting + fix outdated link

---

source/release/4.4.7/index.md

- Updated the content for 4.4.7 RC6

Update index.md for 4.4.7 RC6

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.4.7/index.md

- Update the website announcing 4.4.7 GA

release 4.4.7 GA

---

source/documentation/common/collateral_files/attributes.adoc
source/documentation/data_warehouse_guide/chap-Installing_and_Configuring_Data_Warehouse.adoc
source/documentation/data_warehouse_guide/index.adoc
source/documentation/data_warehouse_guide/topics/Allowing_Read_Only_Access_to_the_History_Database.adoc
source/documentation/data_warehouse_guide/topics/History_Database_Overview.adoc
source/documentation/data_warehouse_guide/topics/Host_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Host_interface_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Latest_cluster_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_datacenter_configuration_view1.adoc
source/documentation/data_warehouse_guide/topics/Latest_datacenter_configuration_view2.adoc
source/documentation/data_warehouse_guide/topics/Latest_host_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_host_interface_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_storage_domain_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_disk_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_interface_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Overview_of_Configuring_Data_Warehouse.adoc
source/documentation/data_warehouse_guide/topics/Storage_domain_daily_history_view.adoc
source/documentation/data_warehouse_guide/topics/User_Details_History.adoc
source/documentation/data_warehouse_guide/topics/Virtual_Machine_Device_Configuration.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_disk_hourly_and_samples_history_views.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_interface_hourly_and_daily_history_views.adoc

- Aligned DWH guide to downstream

dwh guide: align to downstream

---

source/develop/release-management/features/virt/ovmf.md

- fix markdown and broken links in OVMF feature page

feature: ovmf: fix markdown and broken links

---

source/develop/release-management/features/gluster/gluster-arbiter-volume.md
source/develop/release-management/features/gluster/gluster-dr.md
source/develop/release-management/features/gluster/gluster-reset-brick-support.md
source/release/4.3.0/index.md

Signed-off-by: Sahina Bose <sabose@redhat.com>
Fixes issue #2528 
-
-
-

correcting links to gluster doc

---

source/develop/dev-process/working-with-gerrit.md

- improved git-review instructions, as they were outdated
PR#3 of this original PR: https://github.com/oVirt/ovirt-site/pull/2513
This pull request needs review by: @ahadas @liranr23 @sandrobonazzola @nirs

improve working with gerrit tutorial - improved git-review instructions

---

source/develop/release-management/process/press-plan.md

- Dropped broken links
- Reorderd reviewers section
- Removed unverified references
This pull request needs review by: @dneary @jasonbrooks

press-plan: fix broken links and markdown

---

source/develop/release-management/features/network/lldp.md
source/develop/release-management/features/network/networking-api-security-groups.md

Fixes #2534 
Fixes #2529 
@sandrobonazzola please take a  look

Fix 404 for network feature pages

---

.github/workflows/website_tests.yml
CONTRIBUTING.md
Gemfile.lock

Fixes issue #2537
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @duck

Clarify ruby version

---

source/develop/release-management/features/network/isolated-ports.md
source/develop/release-management/features/network/lldp.md
source/develop/release-management/features/network/managed_mtu_for_vm_networks.md
source/develop/release-management/features/network/networkfilterparameters.md
source/develop/release-management/features/network/openstack_identity_api_v3.md
source/develop/release-management/features/network/provider-physical-network.md
source/develop/release-management/features/sla/hosted-engine-network-check.md

@almusil @erav @arachman @phoracek Can you please approve?
CC: @sandrobonazzola @mwperina

Set new feature owners

---

source/develop/release-management/features/storage/backup-restore-disk-snapshots.md

Fixes issue #2533
- s/download_disk_snapshots.py/download_all_disk_snapshots.py
@danielerez 

Fixed link in backup disk-snapshots feature page

---

source/release/4.4.8/index.md

- Added new content for 4.4.8 RC1

Create index.md for 4.4.8 rc1

---

source/release/4.4.8/index.md

- Updated content for 4.4.8 RC2

Update index.md for 4.4.8 RC2

---

source/documentation/common/install/assembly-Installing_Hosts_for_RHV.adoc
source/documentation/common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1870695
new topic:
`common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc`
Added new topic to assembly: 
`common/install/assembly-Installing_Hosts_for_RHV.adoc`
This pull request needs review by: @sandrobonazzola or @duck-rh

1870695 Added a new topic: Installing a third-party package on oVirt-node

---

source/develop/release-management/features/virt/dedicated-cpu.md

Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
- This PR introduces a feature page for dedicated CPU policies
This pull request needs review by: @ahadas @mz-pdm @liranr23 @smelamud @ljelinkova

Add feature page for dedicated CPU policies

---

source/release/4.4.8/index.md

- Updated content for 4.4.8 RC3

Update index.md 4.4.8 RC3

---

source/develop/release-management/features/metrics/metrics-store-all-in-one.md

Fixes issue #2535
- Drop broken link on outdated and unmaintained page develop/release-management/features/metrics/metrics-store-all-in-one.html

Drop broken link

---

source/develop/qa/index.md

- Updated Next Releases to 4.4.8

Updated Next Releases to 4.4.8

---

source/release/4.4.8/index.md

- Updated content for 4.4.8 RC4

Update index.md for 4.4.8 RC4

---

source/release/4.4.8/index.md

- Updated content for 4.4.8 RC5

Update index.md for 4.4.8 RC5

---

source/release/4.4.8/index.md

- Updated content for 4.4.8 GA

Update index.md for 4.4.8 GA

---

source/develop/qa/index.md
source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.4.8/index.md

- Update website pointing to 4.4.8 GA

release 4.4.8 GA

---

source/release/4.4.8/index.md

- update 4.4.8 release notes with async 2 content

4.4.8: update release notes with async2 content

---

source/documentation/common/test-sync-script.adoc

- This is a standalone dummy file added to test automation for syncing the upstream to the downstream doc repo.-

test-sync-US2DS Added a dummy file

---

source/documentation/common/test-sync-script.adoc

I added a sentence to test-sync-script.adoc. I want to see if the mirroring script will copy this change to the same downstream branch that it already mirrored.

test-ds-mirror-2 Added a sentence to test-sync-script.adoc.

---

source/develop/qa/index.md
source/documentation/index.haml
source/release/4.4.9/index.md

4.4.9: add RC1 content

---

source/documentation/common/upgrade/proc-Upgrading_hypervisor_preserve_gluster_storage.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc

This PR replaces #2455.
Fixes issue #2287
- Copying updates from downstream (RHV) Upgrade Guide
This pull request needs review by: @rchikatw

issue#2287 Migrating downstream changes to upstream

---

source/release/4.4.8/index.md

- 4.4.8: update notes with async 4 content

4.4.8: update notes with async #4 content

---

source/community/about/community-activity.md
source/community/about/contact.md
source/community/about/governance.md
source/community/about/limitationsonbusinessentities.md
source/community/get-involved/donate-hardware.md
source/community/get-involved/promote.md
source/community/get-involved/repository-mirrors.md
source/community/index.md

Typo and grammar fixes
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md).

First small typo and grammar overhaul in community

---

source/documentation/administration_guide/chap-Hosts.adoc
source/documentation/administration_guide/topics/proc_migrating_she_host_to_different_cluster.adoc

Fixes BZ# https://bugzilla.redhat.com/show_bug.cgi?id=1858353
- Added new module: Migrating a self-hosted engine host to a different cluster

BZ1858353: [Docs][AdminGuide] Disabling moving HE hosts into different DCs/clusters

---

source/documentation/administration_guide/chap-Storage.adoc
source/documentation/administration_guide/topics/Removing_stale_LUNs.adoc

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1946995
- These changes were completed and approved in the RHV repo on GitLab and I'm copying them over now that we are working upstream first.
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @dcdacosta)
This pull request needs review by: Already reviewed and approved by SME, QE and peer reviewers.

BZ1946995 - Copy approved changes from downstream repo to upstream

---

source/documentation/virtual_machine_management_guide/chap-Additional_Configuration.adoc
source/documentation/virtual_machine_management_guide/topics/Configuring_Time_Zones.adoc

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1981099
- Added new section to additional configuration chapter for configuring time zones.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@dcdacosta)
This pull request needs review by: (@ahadas @saifabusaleh )

DRAFT: BZ1981099 - Added topic for configuring time zones

---

source/documentation/administration_guide/topics/Grafana_dashboards.adoc

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2010355
RFE. This PR is for 4.4.9. It should not be released beforehand.
This pull request needs review by: @avlitman

BZ#2010355: [Docs] Update Inventory Dashboard description

---

source/develop/dev-process/install-nightly-snapshot.md
source/develop/developer-guide/vdsm/developers.md
source/develop/developer-guide/vdsm/installing-vdsm-from-rpm.md
source/develop/release-management/features/integration/centos-9-stream-support.md

- Update the instructions for installing oVirt master snapshot
This pull request needs review by:  @tinez @sanjacodes @michalskrivanek @ahadas @shenitzky @mwperina

update installing nightly snaphost flow

---

source/develop/dev-process/install-nightly-snapshot.md

- Added el9 case to nightly installation of oVirt master
This pull request needs review by: @sanjacodes @michalskrivanek @ahadas @shenitzky @mwperina

nightly: added el9 procedure

---

.github/workflows/preview.yml
.github/workflows/remove-preview.yml

This change attempts to fix minor issues with the preview build / GitHub Actions integration.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @janosdebugs

Fix GitHub actions integration

---

.github/workflows/preview.yml
.github/workflows/remove-preview.yml

This PR adds the remaining fixes for GitHub Actions.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @janosdebugs

GHA fixes round 2

---

.github/workflows/dashpanel.yml

Fix Dashpanel Action to push into dashpanel branch instead of protected main branch

Push into dashpanel branch

---

source/develop/devdocs.md
source/develop/release-management/process/add_a_package_to_copr.md

- Added procedure for including a new package in oVirt/ovirt-master-snapshot COPR project.
This pull request needs review by: @arso @sanjacodes @lveyde

release management: adding pkgs to COPR

---

source/develop/devdocs.md
source/develop/developer-guide/migrating_to_github.md

- Adding guide for migrating to GitHub
This pull request needs review by: @sanjacodes @janosdebugs @ahadas @michalskrivanek @mwperina @marchukov

Adding guide for migrating to GitHub

---

source/develop/projects/project-movirt.md
source/download/alternate_downloads.md
source/download/browsers_and_mobile.md
source/download/index.md

- The moVirt project has been discontinued. Avoiding to point users to the application.

follow up on moVirt project discontinued

---

source/develop/developer-guide/migrating_to_github.md

Add information about:
* Template repository
* CODEOWNERS
* PR and issue templates
* Labels
* STDCI cleanup

Add more information to GitHub guide

---

source/develop/release-management/features/virt/parallel-migration-connections.md

- Adding a feature page about parallel migration connections.

Add parallel migration connections feature page

---

source/documentation/administration_guide/topics/con-Network-Manager-Stateful-Configuration-nmstate.adoc
source/documentation/administration_guide/topics/proc-enabling-fips_rhel_hosts_and_rhvm.adoc
source/documentation/common/install/proc-Creating_a_virtual_machine.adoc
source/documentation/common/sriov/assembly-Set_Up_and_Configure_SR-IOV.adoc
source/documentation/virtual_machine_management_guide/assembly-Installing_Red_Hat_Enterprise_Linux_Virtual_Machines.adoc

Fixes issue # (https://bugzilla.redhat.com/show_bug.cgi?id=1992296)
- Link checker scan of library highlighted several broken links. This PR fixes the broken links identified.-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @ddacosta)
This pull request needs review by: (please @emarcusRH)

BZ#1992296 - Fix broken links in RHV 4.4 Library

---

source/documentation/common/upgrade/snip-upgrade_considerations.adoc
source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/chap-Updates_between_Minor_Releases.adoc

Fixes issue  https://bugzilla.redhat.com/show_bug.cgi?id=1964159
- This is a duplicate pull request from https://github.com/oVirt/ovirt-site/pull/2610. Duplicated in order to successfully generate a preview and allow merging.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dcdacosta dacosta
This pull request needs review by: Previously reviewed by @stoobie

BZ1964159 - [duplicate] added link to upgrade considerations KC article

---

source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/index.adoc
source/documentation/upgrade_guide/master.adoc

Fixes issue # 1946403
- try to view preview build and 
- try to fix publishing problem in ovirt website
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH 

1946403A additional updates for Upgrade Guide

---

source/develop/release-management/features/virt/vm-screenshot.md

Add VM screenshot feature page
This pull request needs review by: @ahadas @liranr23 @mz-pdm  @nyoxi @ljelinkova  @smelamud

Add VM screenshot feature page

---

source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc

Bug fix
Fixes BZ2023343: https://bugzilla.redhat.com/show_bug.cgi?id=2023343#c4
Preview:
https://oVirt.github.io/ovirt-site/previews/2654
This pull request needs review by: @sandrobonazzola @didib

2023343:[Docs][Upgrade] Added that ovirt-release44.rpm must be up-to-date

---

source/documentation/data_warehouse_guide/topics/Enabling_debug_mode.adoc
source/documentation/data_warehouse_guide/topics/Overview_of_Configuring_Data_Warehouse.adoc

Fixes issue #2025298 
- add note to DWH guide under Enabling Debug Mode
This pull request needs review by: (please @avlitman )

BZ#2025298 add note to DWH guide under Enabling Debug Mode

---

source/documentation/administration_guide/index.adoc
source/documentation/administration_guide/master.adoc
source/documentation/common/collateral_files/legal-notice.adoc
source/documentation/data_warehouse_guide/index.adoc
source/documentation/data_warehouse_guide/master.adoc
source/documentation/disaster_recovery_guide/index.adoc
source/documentation/disaster_recovery_guide/master.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/index.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/master.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/master.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/master.adoc
source/documentation/introduction_to_the_vm_portal/index.adoc
source/documentation/introduction_to_the_vm_portal/master.adoc
source/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/index.adoc
source/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/master.adoc
source/documentation/upgrade_guide/index.adoc
source/documentation/upgrade_guide/master.adoc
source/documentation/virtual_machine_management_guide/index.adoc
source/documentation/virtual_machine_management_guide/master.adoc

Fixes issue # https://issues.redhat.com/browse/RHV-42520
- This is a duplicate pull request from https://github.com/oVirt/ovirt-site/pull/2581. Duplicated in order to successfully generate a preview and allow merging.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dcdacosta
This pull request needs review by: Previously reviewed by @stoobie

RHV-42520 - [duplicate] updating and adding legal notices

---

source/documentation/virtual_machine_management_guide/topics/Deleting_a_snapshot.adoc

Fixes issue #1472752
- remove all notes - out dated
- remove second introductory sentence regarding only working with running VM
-
This pull request needs review by: (please @bennyz )

Updating /removing outdated information in "deleting a snapshot" in VMM guide

---

source/develop/qa/index.md
source/documentation/index.haml
source/release/4.4.10/index.md

4.4.10: add RC1 content

---

source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc
source/documentation/upgrade_guide/chap-Red_Hat_Virtualization_Upgrade_Overview.adoc

Fixes issue BZ#1946403
- added step to updating Manager - update Manager subscriptions to 4.4 (RHV Docs only)
- improve formatting of upgrade options table in Overview chapter
- move up the recommendation for the RHV Upgrade Helper, format as a NOTE (RHV Docs only)
This pull request needs review by: (please @dcdacosta )

1946403B additional updates to Upgrade Guide 

---

source/stylesheets/asciidoc.css

Adding CSS for callouts.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @janosdebugs 

Adding support for callouts

---

source/release/4.4.10/index.md

- Updated content for 4.4.10 GA

Update index.md for 4.4.10 GA

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.4.10/index.md

- Update stable release to 4.4.10

Update stable release to 4.4.10

---

source/develop/dev-process/working-with-github.md

Describes basic GitHub workflow for developers similarly as we already
have for gerrit:
https://github.com/oVirt/ovirt-site/blob/master/source/develop/dev-process/working-with-gerrit.md
Signed-off-by: Martin Perina <mperina@redhat.com>

Describe basic GitHub workflow for developers

---

source/release/4.4.10/index.md

- update 4.4.10 with async #1 content

update 4.4.10 with async #1 content

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
source/documentation/contributing_to_docs/contributing.adoc
source/documentation/contributing_to_docs/contributing_user_stories.adoc

RFE
This PR addresses issue #2632
- Adding more detailed documentation contribution guidelines.
Preview: See the feature branch on my fork:
https://github.com/stoobie/ovirt-site/blob/RHV-43058.1/source/documentation/contributing_to_docs/contributing.adoc
https://github.com/stoobie/ovirt-site/blob/RHV-43058.1/source/documentation/contributing_to_docs/contributing_user_stories.adoc
https://github.com/stoobie/ovirt-site/blob/RHV-43058.1/CONTRIBUTING.md
This pull request needs review by: @duck-rh @sandrobonazzola @janosdebugs

issue2632 Documentation contribution guidelines

---

source/release/4.4.10/index.md

- Update release notes with oVirt 4.4.10 Second Async content.

4.4.10-2: update release notes

---

source/develop/localization.md

[Bug fix]
- Point to the new zanata instance.

localization: point to the new zanata instance

---

source/develop/release-management/features/virt/vm-screenshot.md

Bug fix
- remove invalid email address
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): sandrobonazzola

sabusale@redhat.com is no longer a valid address

---

source/release/4.4.10/index.md

- update 4.4.10 notes with 4.4.10.1

update 4.4.10 notes with 4.4.10.1

---

source/documentation/common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc

Fixes issue # | \[1867911](https://bugzilla.redhat.com/show_bug.cgi?id=1867911)  (delete if not relevant)
minor update -remove downstream only note/link to KCS article 4088711
This pull request needs review by: (please @RichardHoch )

1867911A remove note for KCS article 4088711

---

source/documentation/common/she/proc-Cleaning_Up_a_Failed_Self-hosted_Engine_Deployment.adoc

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1945267
- Add the missing reboot step to the procedure.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @dcdacosta 
This pull request needs review by: Marian Jankular

BZ#1945267 - Added missing reboot step and note to procedure

---

source/documentation/virtual_machine_management_guide/topics/Virtual_Machine_High_Availability_settings_explained.adoc

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1665449
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @ahadas 
This pull request needs review by: @stoobie @dcdacosta  @emarcusRH

Elaborate more on watchdog dump action

---

source/develop/release-management/features/virt/dedicated-cpu.md

* CPU hotplugging
* storing pinned CPUs in metadata
* mention emulator/IO thread pinning in relation to parallel migrations
This pull request needs review by: @mz-pdm, @ahadas, @liranr23

Dedicated cpu feature page udpate

---

source/documentation/assembly-Setting_up_a_gpu_on_a_vm/master.adoc

Deleted a line in a file to check the PR functionality.

minor change to a line to test pr

---

source/release/4.5.0/index.md

- Initial draft release notes for 4.5.0

4.5.0: added draft for alpha development

---

source/develop/localization.md

- Add bugzilla query for localization issues that can be handled by translators.

Add bugzilla query for localization issues

---

source/documentation/disaster_recovery_guide/assembly/asm_ActiveActiveDR.adoc
source/documentation/disaster_recovery_guide/assembly/asm_ActivePassiveDR.adoc
source/documentation/disaster_recovery_guide/concept/cpt_DisasterRecoverySolutions.adoc
source/documentation/disaster_recovery_guide/concept/cpt_NetworkConsiderationsAA.adoc
source/documentation/disaster_recovery_guide/concept/cpt_NetworkConsiderationsAP.adoc
source/documentation/disaster_recovery_guide/concept/cpt_OverviewActiveActive.adoc
source/documentation/disaster_recovery_guide/concept/cpt_OverviewActivePassive.adoc
source/documentation/disaster_recovery_guide/concept/cpt_StorageConsiderationsAA.adoc
source/documentation/disaster_recovery_guide/concept/cpt_StorageConsiderationsAP.adoc
source/documentation/disaster_recovery_guide/reference/ref_UsingOvirtDrScript.adoc
source/documentation/disaster_recovery_guide/reference/rfr_MappingFileAttributes.adoc
source/documentation/disaster_recovery_guide/reference/rfr_TestingAP.adoc
source/documentation/disaster_recovery_guide/reference/rfr_discreet_failover.adoc
source/documentation/disaster_recovery_guide/reference/rfr_discreet_failover_failback.adoc
source/documentation/disaster_recovery_guide/reference/rfr_non_discreet_failover_failback.adoc
source/documentation/disaster_recovery_guide/task/task_Clean.adoc
source/documentation/disaster_recovery_guide/task/task_ConfigureStretchCluster.adoc
source/documentation/disaster_recovery_guide/task/task_CreateAnsiblePlaybooks.adoc
source/documentation/disaster_recovery_guide/task/task_CreateCleanupPlaybook.adoc
source/documentation/disaster_recovery_guide/task/task_CreateFailoverFailbackPlaybooks.adoc
source/documentation/disaster_recovery_guide/task/task_ExecuteFailback.adoc
source/documentation/disaster_recovery_guide/task/task_ExecuteFailover.adoc
source/documentation/disaster_recovery_guide/task/task_GenerateMapping.adoc

update DR guide contexts

---

source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/master.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/master.adoc
source/documentation/introduction_to_the_vm_portal/chap-Accessing_the_VM_Portal.adoc
source/documentation/introduction_to_the_vm_portal/chap-Managing_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/master.adoc
source/documentation/introduction_to_the_vm_portal/topics/Connecting_to_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Creating_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Editing_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Graphical_User_Interface_elements.adoc
source/documentation/introduction_to_the_vm_portal/topics/Installing_the_CA_certificate.adoc
source/documentation/introduction_to_the_vm_portal/topics/Logging_in_to_the_VM_Portal.adoc
source/documentation/introduction_to_the_vm_portal/topics/Viewing_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/What_is_the_VM_Portal.adoc
source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-2.adoc
source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-2.adoc
source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-2.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-2_ff.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/chap-Red_Hat_Virtualization_Upgrade_Overview.adoc
source/documentation/upgrade_guide/chap-Updates_between_Minor_Releases.adoc
source/documentation/upgrade_guide/master.adoc
source/documentation/upgrade_guide/topics/Updating_the_Local_Repository_for_an_Offline_Red_Hat_Virtualization_Manager_Installation.adoc
source/documentation/upgrade_guide/topics/Upgrading_with_ovirt-fast-forward-upgrade.adoc
source/documentation/upgrade_guide/topics/installing_virtual_product_hypervisors_from_local_repository.adoc
source/documentation/upgrade_guide/topics/ovirt-fast-forward-upgrade_Explained.adoc

content-type attributes added to upgrade

---

source/documentation/data_warehouse_guide/chap-About_History_Database.adoc
source/documentation/data_warehouse_guide/chap-Installing_and_Configuring_Data_Warehouse.adoc
source/documentation/data_warehouse_guide/master.adoc
source/documentation/data_warehouse_guide/topics/Allowing_Read_Only_Access_to_the_History_Database.adoc
source/documentation/data_warehouse_guide/topics/Application_Settings_for_the_Data_Warehouse_service_in_ovirt-engine-dwhd.conf.adoc
source/documentation/data_warehouse_guide/topics/Changing_the_Data_Warehouse_Sampling_Scale.adoc
source/documentation/data_warehouse_guide/topics/Enabling_debug_mode.adoc
source/documentation/data_warehouse_guide/topics/History_Database_Overview.adoc
source/documentation/data_warehouse_guide/topics/Host_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Host_interface_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Latest_cluster_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_datacenter_configuration_view1.adoc
source/documentation/data_warehouse_guide/topics/Latest_datacenter_configuration_view2.adoc
source/documentation/data_warehouse_guide/topics/Latest_host_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_host_interface_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_storage_domain_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_disk_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Latest_virtual_machine_interface_configuration_view.adoc
source/documentation/data_warehouse_guide/topics/Overview_of_Configuring_Data_Warehouse.adoc
source/documentation/data_warehouse_guide/topics/Recording_statistical_history.adoc
source/documentation/data_warehouse_guide/topics/Storage_domain_daily_history_view.adoc
source/documentation/data_warehouse_guide/topics/Tracking_configuration_history.adoc
source/documentation/data_warehouse_guide/topics/Tracking_tag_history.adoc
source/documentation/data_warehouse_guide/topics/User_Details_History.adoc
source/documentation/data_warehouse_guide/topics/Virtual_Machine_Device_Configuration.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_disk_hourly_and_samples_history_views.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_hourly_and_daily_history_views.adoc
source/documentation/data_warehouse_guide/topics/Virtual_machine_interface_hourly_and_daily_history_views.adoc
source/documentation/doc-Hardware_Considerations_for_Implementing_SR-IOV/master.adoc

Add content-type attr to DWG

---

source/documentation/doc-Planning_and_Prerequisites_Guide/asm-Considerations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/asm-Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/master.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Directory_Server_Support.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-General_Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Host_Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Host_Types.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Infrastructure_Considerations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Minimum_Architecture.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Networking_Considerations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Networking_Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Security_Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Self-hosted_Engine_Recommendations.adoc
source/documentation/doc-Planning_and_Prerequisites_Guide/topics/con-Storage_Types.adoc

Add content types to PP guide

---

source/documentation/index.haml
source/release/4.5.0/index.md

- Still in pre-alpha but preparing for alpha release.

4.5: prepare for alpha release

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc
source/download/alternate_downloads.md
source/download/index.md
source/download/rpms_and_gpg.md

- Add instructions for oVirt 4.5 Alpha
This pull request needs review by: @apinnick

add 4.5 instructions

---

source/documentation/administration_guide/topics/proc-monitoring-available-space-in-a-storage-domain.adoc
source/documentation/common/backup-restore/proc_enable-incremental-backup-for-a-virtual-disk-api-call.adoc
source/documentation/common/backup-restore/proc_enabling-incremental-backup-on-a-new-disk.adoc
source/documentation/common/backup-restore/proc_enabling-incremental-backup-on-an-existing-virtual-disk.adoc
source/documentation/common/backup-restore/proc_finalize-a-backup.adoc
source/documentation/common/backup-restore/proc_find-disks-enabled-for-incremental-backup.adoc
source/documentation/common/backup-restore/proc_getting-information-about-a-backup.adoc
source/documentation/common/backup-restore/proc_getting-information-about-the-disks-in-a-backup.adoc
source/documentation/common/backup-restore/proc_image-transfer-object-for-incremental-restore.adoc
source/documentation/common/backup-restore/proc_image-transfer-objects-for-incremental-backup.adoc
source/documentation/common/backup-restore/proc_listing-changed-blocks.adoc
source/documentation/common/backup-restore/proc_listing-checkpoints-for-a-virtual-machine.adoc
source/documentation/common/backup-restore/proc_listing-specific-checkpoint-for-a-virtual-machine.adoc
source/documentation/common/backup-restore/proc_removing-a-checkpoint.adoc
source/documentation/common/backup-restore/proc_start-a-full-backup.adoc
source/documentation/common/backup-restore/proc_start-an-incremental-backup.adoc
source/documentation/common/backup-restore/ref_troubleshooting-incremental-backups.adoc
source/documentation/common/backup-restore/ref_using-the-imageio-api-to-transfer-backup-data.adoc
source/documentation/common/install/proc_installing-a-dud-driver-on-a-host-without-installer-support.adoc
source/documentation/common/install/proc_installing-a-third-party-package-on-ovirt-node.adoc
source/documentation/common/install/proc_installing-a-vdsm-hook.adoc

Removing noncompliant attribute (module-type)

---

source/community/about/mailing-lists.md
source/community/index.md
source/community/users-list.md

- Add /community/users-list
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @didib 

Add /community/users-list

---

source/documentation/introduction_to_the_vm_portal/chap-Managing_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/master.adoc
source/documentation/introduction_to_the_vm_portal/topics/Connecting_to_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Creating_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Editing_virtual_machines.adoc
source/documentation/introduction_to_the_vm_portal/topics/Viewing_virtual_machines.adoc

Fix VM portal headers

---

source/release/4.5.0/index.md

release 4.5.0 alpha

---

source/download/node.md

fix oVirt Node master link

---

source/download/node.md

- Add oVirt Node 4.5-pre section

Add oVirt Node 4.5-pre section

---

source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/master.adoc

Fixing offset level for issue 2783

---

source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.adoc
source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/master.adoc

fix other installation guides

---

source/develop/qa/index.md

- Changing pointers for creating new automation tests from jenkins to GitHub Actions.

Update QA page

---

source/documentation/administration_guide/topics/Host_Console_Settings_Explained.adoc

Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2062502
- Added the missing vGPU Placement setting to the Host Console Settings table-
Direct link to the preview to verify changes is here:
https://ovirt.github.io/ovirt-site/previews/2803/documentation/administration_guide/index.html#explanation-of-settings-and-controls-in-the-new-host-and-edit-host-windows
This pull request needs review by: (Germano Veit Michel)

BZ2062502 - Added vGPU placement setting to Host Console Settings table

---

source/documentation/administration_guide/topics/Host_Console_Settings_Explained.adoc

Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2062502
fix typo "consolidated"
Preview link: 
https://ovirt.github.io/ovirt-site/previews/2810/documentation/administration_guide/index.html#explanation-of-settings-and-controls-in-the-new-host-and-edit-host-windows
This pull request needs review by: (please @dcdacosta )

BZ#2062502  fix typo "consolidated"

---

source/_layouts/default.html

[Bug fix]
Fixes issue #2806 
- Fix nested header element in website pages by using a div instead

fix nested header element in website pages

---

_config.yml

[Bug fix]
- Not generating chapters and topics pages as they're included in final assembly.

config: avoid to generate a few unneeded pages

---

source/documentation/doc-Release_Notes/chap-Release_Notes.adoc
source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.10.adoc

[BZ#2056934](https://bugzilla.redhat.com/show_bug.cgi?id=2056934)
- add Deprecation notice for RHVM appliance
-
-

BZ#2056934 Update RHV 4.4.10 Release Notes - RHVM deprecation

---

source/documentation/common/storage/proc-Customizing_Multipath_Configurations_for_SAN_Vendors.adoc
source/documentation/common/upgrade/proc_upgrading-the-remote-data-warehouse-service-and-database.adoc
source/documentation/virtual_machine_management_guide/topics/Live_migration_prerequisites.adoc
source/release/4.0.5/index.md

Bug fix
Fixes issue #2842 (partially)
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @apinnick 
This pull request needs review by:@sandrobonazzola
Preview links: 
https://ovirt.github.io/ovirt-site/previews/2847/release/4.0.5/
https://ovirt.github.io/ovirt-site/previews/2847/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/index.html#proc-Customizing_Multipath_Configurations_for_SAN_Vendors_migrating_to_SHE
https://ovirt.github.io/ovirt-site/previews/2847/documentation/upgrade_guide/index.html#proc_upgrading-the-remote-data-warehouse-service-and-database_4-3_remote_db

Issue 2842 partial fix

---

source/documentation/administration_guide/topics/Detaching_storage_domains_from_a_data_center.adoc
source/documentation/administration_guide/topics/Memory_Optimization.adoc
source/documentation/administration_guide/topics/Moving_storage_domains_to_maintenance_mode.adoc
source/documentation/administration_guide/topics/Preparing_GPU_Passthrough.adoc
source/documentation/administration_guide/topics/Re-initializing_a_Data_Center.adoc
source/documentation/administration_guide/topics/Renaming_the_Manager_with_the_Ovirt_Engine_Rename_Tool.adoc
source/documentation/administration_guide/topics/con_Backup_domains_explained.adoc
source/documentation/common/upgrade/proc-Upgrading_hypervisor_preserve_gluster_storage.adoc
source/documentation/common/vgpu/proc_nvidia_gpu_passthrough.adoc
source/documentation/doc-Technical_Reference/topics/Bonding_Modes.adoc
source/documentation/doc-Technical_Reference/topics/Role_The_Storage_Pool_Manager.adoc
source/documentation/virtual_machine_management_guide/topics/Blacklisting_Network_Interfaces.adoc
source/documentation/virtual_machine_management_guide/topics/Live_migration_prerequisites.adoc

Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2054265
- Inclusive language changes to wrap terms like master and slave in backticks and changing blacklist to denylist where appropriate.
This pull request needs review by: (@apinnick )

BZ2054265 - implemented inclusive language changes

---

source/documentation/doc-Release_Notes/chap-Release_Notes.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.10.adoc

fix chapter title - rhv number, add deprecation notice for RHVM
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH n)

testrelnotes fix chapter title - rhv number, add deprecation notice

---

source/community/user-stories/brussels-airport-case-study.md

- fix 404 link to brussels airport

fix 404 link to brussels airport

---

source/community/user-stories/it-novum-case-study.md

- fix 404 lint to it-novum
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):

fix 404 lint to it-novum

---

source/develop/release-management/features/infra/sso.md

- Clearly mark SSO as deprecated
This pull request needs review by: @ahadas @michalskrivanek

mark sso as deprecated

---

source/documentation/doc-Release_Notes/chap-Introduction.adoc
source/documentation/doc-Release_Notes/chap-Release_Notes.adoc
source/documentation/doc-Release_Notes/docinfo.xml
source/documentation/doc-Release_Notes/master.adoc
source/documentation/doc-Release_Notes/topics/Introduction_to_Red_Hat_Virtualization.adoc
source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.1.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.10-beta.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.10.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.2.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.3.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.4.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.5.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.6.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.7.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.8.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.9.adoc

Fix orphan Intro header

---

source/documentation/administration_guide/topics/Cluster_Migration_Policy_Settings_Explained.adoc
source/documentation/administration_guide/topics/Virtual_Machine_Pool_Host_settings_explained.adoc
source/documentation/virtual_machine_management_guide/topics/Virtual_Machine_Host_settings_explained.adoc

Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1981096
- Added the information for the Parallel Migrations selection to the doc for Virtual Machine: Host Settings, Virtual Machine Pool: Host Settings and Migration Policies Explained (Creating a new Cluster).
- Also added information for Number of VM Migration Connections setting in the same files.
**NOTE:**: Both these settings were grayed out in the build I was looking at, so if these features are not yet completed we can keep this PR in draft format until the features are implemented.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@dcdacosta) …

BZ1982096 - Added information for Parallel Migrations

---

source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc

Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2052963
- Added systemtap to the table of removed features in the release notes.
This pull requests needs peer review by: (@emarcusRH )

BZ2052963 - added systemtap to the table of removed features

---

source/documentation/virtual_machine_management_guide/topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc

Bug fix
Partially fixes issue #2842
- virtual_machine_management_guide: fix 404 error according to https://github.com/oVirt/ovirt-site/issues/2842#issuecomment-1110909787

virtual_machine_management_guide: fix 404 error

---

source/release/4.5.0/index.md

- add ovirt-engine-4.5.0.6 notes

4.5.0: add ovirt-engine-4.5.0.6 notes

---

source/documentation/administration_guide/chap-Renewing_certificates.adoc
source/documentation/administration_guide/chap_Renewing-certificates.adoc
source/documentation/administration_guide/part-Administering_the_Environment.adoc
source/documentation/common/upgrade/proc-Replacing_SHA-1_Certificates_with_SHA-256_Certificates.adoc
source/documentation/doc-Release_Notes/chap-Certificates.adoc
source/documentation/doc-Release_Notes/master.adoc

[Bug fix]
Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2078025
-  Added steps to renew certificates in Admin Guide (https://ovirt.github.io/ovirt-site/previews/2866/documentation/administration_guide/index.html#chap-Renewing_certificates_RHV_backup_restore)
-  Added warning and link to steps in the Upgrade Guide (https://ovirt.github.io/ovirt-site/previews/2866/documentation/upgrade_guide/index.html#Replacing_SHA-1_Certificates_with_SHA-256_Certificates_4-2_local_db)
- Added topic on managing certificates and link to steps in Release Notes.
-  Rearranged info to eliminate blank intro topic
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING. …

BZ2078025 - document how to renew certificates

---

source/documentation/common/install/proc-Installing_Red_Hat_Enterprise_Linux_Hosts.adoc
source/documentation/common/prereqs/asm-Host_Requirements.adoc
source/documentation/common/prereqs/ref-Host_CPU_Requirements.adoc
source/download/alternate_downloads.md
source/download/index.md

- Added Tech Preview notes regarding CentOS Stream 9, ARM 64 and Power 64 LE.
This pull request needs review by: @oVirt/developers

oVirt 4.5 docs - add tech preview notes

---

source/community/index.md

- Added a section on how community can help keeping oVirt Node more secure.
This pull request needs review by: @stoniko

community: monitoring CVEs

---

source/release/3.6.1/index.md

Bug fix
- fix 404 errors in 3.6.1 release notes

3.6.1: fix 404 errors

---

source/develop/release-management/features/network/networkfilterparameters.md

Bug fix
Fixes issue #2857
- Fix broken link leading to 404 and markdown of the page.

fix 404 and markdown

---

source/documentation/common/admin/con_UEFI_Q35_explanation.adoc
source/documentation/common/admin/proc_Configuring_cluster_to_use_Q35_or_UEFI.adoc
source/documentation/common/admin/proc_Configuring_vm_to_use_Q35_or_UEFI.adoc
source/documentation/doc-Release_Notes/topics/ref-Technology_Preview_Features_RHV.adoc
source/documentation/doc-Technical_Reference/topics/Graphics_Devices.adoc

Fixes issue # | \[BZ#2081421](https://bugzilla.redhat.com/show_bug.cgi?id=2081421)  (delete if not relevant)
- remove UEFI and BOCH tech preview notices-

BZ#2081421  remove UEFI and BOCH tech preview notices

---

source/develop/troubleshooting-nfs-storage-issues.md

- Documentation: Defines work arounds to Synology DSM 7 ACL restrictions and lack of fine grained user control of NFS shares.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @matonb

Add Synology DSM settings to NFS Server section

---

source/release/4.5.0/index.md

- Update 4.5.0 notes with May 11 async content

4.5.0: update with May 11 async content

---

source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc

Fixes issue # | \[BZ#2072987](https://bugzilla.redhat.com/show_bug.cgi?id=2072987)  (delete if not relevant)
add DISA DTIG to Rel Notes Removed Functionality

BZ#2072987 add DISA DTIG to Rel Notes Removed Functionality

---

source/documentation/common/prereqs/asm-Networking_Requirements.adoc
source/documentation/common/prereqs/ref-MTU_Requirements.adoc

[Bug fix]
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1972934
- Added and MTU Requirements topic to the Networking Requirements chapter.
Direct preview link: https://ovirt.github.io/ovirt-site/previews/2892/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#MTU_Requirements_SM_localDB_deploy
This pull request needs review by: (Marina Kalinin)
This pull request needs peer review by: (@emarcusRH )

Bz1972934 - add MTU requirements info

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
source/download/alternate_downloads.md
source/download/index.md
source/download/install_on_rhel.md
source/download/rpms_and_gpg.md
source/release/4.5.0/index.md

- Updated instructions for RHEL 8.6 and derivatives.
This pull request needs review by: @oVirt/ovirt-documentation @almalinux @rocky-linux @navy-linux

rhel: updated instructions

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
source/download/alternate_downloads.md
source/download/index.md
source/download/install_on_rhel.md
source/download/rpms_and_gpg.md

- Add instructions for RHEL 9 experimental support
This pull request needs review by: @oVirt/ovirt-documentation @AlmaLinux @rocky-linux @navy-linux

Install on RHEL 9 instructions

---

source/release/4.5.0/index.md

Add 4.5.0.2 async notes

---

source/documentation/administration_guide/chap-Renewing_certificates.adoc
source/documentation/doc-Release_Notes/chap-Certificates.adoc

Fixes issue # | \[BZ#2078025](https://bugzilla.redhat.com/show_bug.cgi?id=2078025)  (delete if not relevant)
-add explicit Manager certificate renewal procedure
Preview  oVirt - https://ovirt.github.io/ovirt-site/previews/2908/documentation/administration_guide/index.html#chap-Renewing_certificates_RHV_backup_restore
This pull request needs review by: (please @apinnick )

BZ#2078025 adding explicit Manager certificate renewal procedure

---

source/release/4.5.0/index.md

Fixes issue #2915
- Fixing broken link

4.5 release notes: fix broken link

---

source/documentation/administration_guide/topics/Detaching_storage_domains_from_a_data_center.adoc

Fixes issue # | \[BZ#1548852](https://bugzilla.redhat.com/show_bug.cgi?id=1548852)  (delete if not relevant)
- Update note regarding removal of last master storage domain in a Data Center
- Preview - https://ovirt.github.io/ovirt-site/previews/2923/documentation/administration_guide/index.html#sect-Data_Centers_and_Storage_Domains
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH 

BZ#1548852 note regarding removal of last master SD in a DC

---

source/documentation/common/upgrade/proc-Replacing_SHA-1_Certificates_with_SHA-256_Certificates.adoc
source/documentation/disaster_recovery_guide/docinfo.xml
source/documentation/doc-Planning_and_Prerequisites_Guide/docinfo.xml
source/documentation/doc-Product_Guide/docinfo.xml
source/documentation/doc-Release_Notes/docinfo.xml
source/documentation/doc-Release_Notes/topics/Introduction_to_Red_Hat_Virtualization.adoc
source/documentation/doc-Technical_Notes/RHSA-20224711-06.adoc
source/documentation/doc-Technical_Notes/RHSA-20224712-03.adoc
source/documentation/doc-Technical_Notes/docinfo.xml
source/documentation/doc-Technical_Notes/master.adoc

This pull request needs review by: (please @apinnick )

SP1_attribute  updating attribute vernum_rhv >> vername_rhv where needed

---

source/documentation/common/collateral_files/_attributes.adoc

Updating vernum_rhv attribute for 4.4 SP1

---

source/documentation/administration_guide/topics/Adding_OVN_as_an_External_Network_Provider.adoc
source/documentation/administration_guide/topics/Importing_Networks.adoc
source/documentation/administration_guide/topics/Kernel_Settings_Explained.adoc
source/documentation/administration_guide/topics/proc-enabling-nested-virtualization-for-all-virtual-machines.adoc
source/documentation/administration_guide/topics/proc-enabling-nested-virtualization-for-individual-virtual-machines.adoc

Fixing broken xrefs in Admin guide

---

source/documentation/common/collateral_files/_attributes.adoc

Update vernum_rhv attribute

---

source/documentation/doc-Technical_Notes/docinfo.xml
source/documentation/doc-Technical_Notes/master.adoc

Fixes couple issues in tech notes
- Removed duplicate legal notice "include"
- Corrected {vernum_rhv_legacy} attribute
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @apinnick 
This pull request needs review by: @emarcusRH

small fixes for tech notes

---

source/documentation/common/collateral_files/_attributes.adoc

Workaround until renaming bug is fixed
-
-
-

Reverting vernum_rhv attribute

---

source/documentation/doc-Release_Notes/topics/ref-Technology_Preview_Features_RHV.adoc

Fixes issue # | \[BZ#2083679](https://bugzilla.redhat.com/show_bug.cgi?id=2083679)  (delete if not relevant)
-add dedicated CPU to Technical Preview chapter of Rel Notes

add dedicated CPU to Technical Preview chapter of Rel Notes

---

source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.0-1.adoc

Fixes issue # | \[BZ#1995455](https://bugzilla.redhat.com/show_bug.cgi?id=1995455)  (delete if not relevant)
-MANUALLY added enhancement notification for MAX CPUs to Rel Notes  enhancement section - the Rel Notes script is not picking up this particular BZ item

1995455 add important enhancement notice to Rel Notes

---

source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc
source/documentation/upgrade_guide/chap-Updates_between_Minor_Releases.adoc

Still fixing upgrade guide

---

source/documentation/doc-Release_Notes/master.html
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.1.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.2.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.3.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.7.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.0-1.adoc

- Replaced incorrectly coded links in the Release Notes

linkfix - Fixing broken markdown links in the release notes

---

source/documentation/common/upgrade/snip-upgrade_considerations.adoc

Fixes issue # | \[RHVDDF-33](https://issues.redhat.com/browse/RHVDDF-33)  (delete if not relevant)
- replace hard coded version number in note regarding OVN  with attribute

RHVDDF-33 add attribute for version number in note regarding OVN

---

source/documentation/administration_guide/topics/proc-enabling-fips_in_rhv.adoc
source/documentation/administration_guide/topics/proc-enabling-fips_she.adoc
source/documentation/common/security/proc-Applying_the_DISA_STIG_Security_Profile_RHV.adoc
source/documentation/common/security/proc-Applying_the_PCI_DSS_Security_Profile_RHV.adoc
source/documentation/doc-Product_Guide/asm-AccessingRHV.adoc

Fixing broken links from CP report

---

source/documentation/doc-Release_Notes/topics/ref-Technology_Preview_Features_RHV.adoc

Fixes issue # | \[BZ #2079696](https://bugzilla.redhat.com/show_bug.cgi?id=2079696) 
- remove Incremental backup from Tech Preview in Rel Notes-

BZ#2079696 remove Incremental backup from Tech Preview in Rel Notes

---

source/documentation/administration_guide/topics/proc-enabling-nested-virtualization-for-individual-virtual-machines.adoc

https://issues.redhat.com/browse/RHVDDF-30
- update link title text 

rhvddf-30 correcting link title

---

source/documentation/administration_guide/topics/Configuring_Red_Hat_SSO.adoc

https://issues.redhat.com/browse/RHVDDF-41
https://issues.redhat.com/browse/RHVDDF-39
https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-38
- checking improperly rendered headings in Administration Guide - sec. 3.6.5  RH SSO installation 
- line spacing was needed between **include** statements in the chapter level assembly in order to render the headings correctly

rhvddf-41  adjusting heading level formatting

---

source/documentation/common/backup-restore/proc_getting-information-about-a-backup.adoc

https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-40
-  update capitalization in bulleted list

rhvddf-40 capitalization of description list

---

source/develop/developer-guide/vdsm/hook/qemucmdline.md

- dropped broken links
- removed outdated docs for oVirt Node
- adjusted markdown
This pull request needs review by: @tinez @mz-pdm  (last touching the vdsm hook)
CC original writers: @dougsland @dyasny
CC original developer: @dpkshetty / @deepakcshetty
@oVirt/ovirt-documentation : FYI this hook seems not documented in our guides.

qemucmdline: update

---

source/develop/release-management/process/making-a-release.md

- added documentation about closing verified bugs.

making a release: document closing bugs

---

source/release/4.5.1/index.md

Added content for RC1
- Added content for 4.5.1 RC1

Create 4.5.1 release notes

---

source/develop/developer-guide/db-issues/helperutilities.md

Typo
There is no ticket for this PR.
- correct some small typing mistakes
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @rokkbert (well, the branch-name is the bad default name, sorry))
This pull request needs review by: (please @sandrobonazzola )

fixed small typos in helperutilities.md

---

source/develop/release-management/process/making-a-release.md

- Short instructions to set up a CentOS build environment.

making-a-release: Add more information about setting up CentOS builds

---

source/documentation/virtual_machine_management_guide/master.html
source/documentation/virtual_machine_management_guide/topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc

RHVDDF-29: fixing bullet list

---

source/documentation/administration_guide/topics/VDSM_hooks_domain_xml.adoc

Bug fix
Fixes issue #RHVDDF-26
-
-
-

RHVDDF-26: fixing markup

---

source/documentation/scripts/preview-upload.sh

Script to build downstream previews and upload to remote drive

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml

4.5.1: release

---

source/release/4.5.1/index.md

- Updated content for 4.5.1 GA

Update index.md for 4.5.1 GA

---

source/documentation/administration_guide/appe-Red_Hat_Virtualization_and_Encrypted_Communication.adoc
source/documentation/administration_guide/topics/Configuring_remote_viewer_trust_rhvm_ca_certificate.adoc
source/documentation/administration_guide/topics/Setting_Up_Encrypted_Communication_between_the_Manager_and_an_LDAP_Server.adoc
source/documentation/administration_guide/topics/configuring_cluster_to_enable_vnc_encryption.adoc
source/documentation/administration_guide/topics/running_vnc_sasl_ansible_playbook_for_each_host.adoc
source/documentation/administration_guide/topics/troubleshooting-vnc-sasl-ansible-playbook.adoc

Bug fix
Fixes issue #[RHV-45567](https://issues.redhat.com/browse/RHV-45567)
- Create proper modules for encryption assembly.
Preview build: http://file.tlv.redhat.com/apinnick/RHV-45567-fix-appendix/administration_guide/index.html#appe-Red_Hat_Enterprise_Virtualization_and_SSL
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @apinnick 

RHV-45567: Modularize the encryption assembly

---

source/documentation/doc-REST_API_Guide/model.adoc

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2101522
Changes proposed in this pull request: Updated REST API model
[Preview](http://file.tlv.redhat.com/apinnick/BZ2101522-rest-api-4.5.1/doc-REST_API_Guide/index.html) 

BZ2101522: Update REST API for 4.5.1

---

source/documentation/scripts/preview-upload.sh

Tweaked preview script so no error if no image folder

---

source/documentation/doc-REST_API_Guide/model.adoc

Fixing duplicate anchor ID in API model

---

source/documentation/common/storage/ref-Preparing_FCP_Storage.adoc

Bug fix
Fixes issue reported in Tableau > Documentation Touchpoint analytics dashboard (feedback survey)
- Add missing bracket to multipath config example

Add missing bracket

---

source/download/alternate_downloads.md
source/download/index.md

Bug fix
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2103604
- point to upgrade guide for instructions on how to upgrade to 4.5.

download: point to upgrade guide

---

source/documentation/virtual_machine_management_guide/topics/Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines.adoc

Fixes issue https://issues.redhat.com/browse/RHVDDF-25
- Note for SSO rewritten to eliminate confusion.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): (@dcdacosta )
Direct link to preview: https://ovirt.github.io/ovirt-site/previews/3013/documentation/virtual_machine_management_guide/index.html#Configuring_Single_Sign-On_for_Red_Hat_Enterprise_Linux_Virtual_Machines
This pull request needs review by: (@apinnick )

RHVDDF-25 reworded note for clarity

---

source/documentation/administration_guide/chap-Users_and_Roles.adoc
source/documentation/administration_guide/topics/Viewing_User_Information_CLI.adoc
source/documentation/administration_guide/topics/Viewing_user_information_UI.adoc

Bug fix
Fixes issue #3016
- Fix duplicate file names

Issue 3016 fix

---

source/documentation/doc-Technical_Notes/RHSA-20225555-09.adoc
source/documentation/doc-Technical_Notes/master.adoc

https://errata.devel.redhat.com/advisory/96099
renamed for release ( Live ID) RHSA-2022:5555-09

rhsa96099 create technical note for advisory RHSA 2022-5555-09

---

source/documentation/doc-Release_Notes/chap-Release_Notes.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.1.adoc

Fixes issue # | https://issues.redhat.com/browse/RHV-46424
- prepare draft of Release Notes for RHV 4.4 SP1 Batch 1

relnotes451 Rel Notes draft for RHV 4.4 SP1 Batch 1 (4.5.1)

---

source/documentation/administration_guide/topics/Configuring_Red_Hat_SSO.adoc
source/documentation/administration_guide/topics/Enabling_the_oVirt_Engine_Extension_Logger_log4j.adoc
source/documentation/administration_guide/topics/proc_Enabling_SyslogHandler_RHV_Manager_logs.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.4.1.adoc

BZ2109262: Fix "Red Had" typo

---

source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc

[BZ#2111600](https://bugzilla.redhat.com/show_bug.cgi?id=2111600)
- add deprecation notice to Rel Notes  - ldap and jdbc extensions

2111600rn add deprecation notice to Release Notes ldap and jdbc ext

---

source/documentation/administration_guide/topics/Attaching_an_Active_Directory.adoc
source/documentation/administration_guide/topics/Configuring_Additional_Local_Domains.adoc
source/documentation/administration_guide/topics/Configuring_LDAP_and_Kerberos_for_Single_Sign-on.adoc
source/documentation/administration_guide/topics/Configuring_an_External_LDAP_Provider.adoc
source/documentation/administration_guide/topics/Configuring_an_External_LDAP_Provider_ManualMethod.adoc
source/documentation/administration_guide/topics/Setting_Up_Encrypted_Communication_between_the_Manager_and_an_LDAP_Server.adoc
source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc
source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc

[BZ#2111600](https://bugzilla.redhat.com/show_bug.cgi?id=2111600)
[](url)
- add deprecation notices to documentation - ldap and jdbc extensions

BZ#2111600 add deprecation notices to documentation - ldap and jdbc extensions

---

source/documentation/administration_guide/topics/Installing_RH_SSO.adoc

- link to SSO installation guide in Administration Guide is 2 versions behind 

fix_sso  update sso guide URL to latest version

---

source/release/4.5.2/index.md

Create release notes file for 4.5.2

---

source/documentation/common/she/proc-Administering_the_Manager_Virtual_Machine.adoc

Bug fix
Fixes [BZ 1917940](https://bugzilla.redhat.com/show_bug.cgi?id=1917940)
- Add missing slash to path

Add missing slash to path

---

source/documentation/virtual_machine_management_guide/topics/Virtual_Machine_Custom_Properties_settings_explained.adoc

Fixes issue # | \[BZ 1834891](https://bugzilla.redhat.com/show_bug.cgi?id=1834891)  (delete if not relevant)
-
-
-

Remove obsolete link

---

source/documentation/common/security/proc-Applying_the_DISA_STIG_Security_Profile_RHV.adoc
source/documentation/common/security/proc-Applying_the_PCI_DSS_Security_Profile_RHV.adoc

[RHVDDF-34](https://issues.redhat.com/browse/RHVDDF-34), [RHVDDF-37](https://issues.redhat.com/browse/RHVDDF-37), [RHVDDF-36](https://issues.redhat.com/browse/RHVDDF-36), [RHVDDF-35](https://issues.redhat.com/browse/RHVDDF-35)
- Updates and corrections to security profiles appendix in Administration Guide ( downstream only)
- removed outdated and unnecessary attached images

Rhvddf-34  Updates and corrections to security profiles appendix in Administration Guide

---

source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml

Signed-off-by: Lev Veyde <lveyde@redhat.com>
- Update references to the latest stable version to 4.5.2

Update latest version references to 4.5.2

---

source/documentation/common/upgrade/proc-Upgrading_hypervisor_preserve_gluster_storage.adoc

Bug fix
Fixes [BZ 2071492](https://bugzilla.redhat.com/show_bug.cgi?id=2071492)
- Typo fix

BZ2071492: typo fix

---

source/release/4.5.2/index.md

- Updated content for 4.5.2 GA

Update index.md for 4.5.2 GA

---

source/documentation/administration_guide/topics/Configuring_RHSSO_OVN.adoc

https://issues.redhat.com/browse/RHVDDF-46
- remove hash mark from configuration code sentence
- Administration Guide > Configuring OVN

rhvddf-46 fix config sentence

---

source/develop/release-management/features/virt/zerocopy-migrations.md

Feature
Related to issue https://bugzilla.redhat.com/show_bug.cgi?id=2089434
- Feature page for zero-copy migrations added.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @mz-pdm 
This pull request needs review by: @michalskrivanek @mwperina

Add Zero-copy migrations feature page

---

.gitignore

Gitignore VS Code config

---

source/documentation/doc-REST_API_Guide/master.adoc
source/documentation/doc-REST_API_Guide/model.adoc

- Update REST API model
This pull request needs review by: @emarcusRH 
Preview build: http://file.tlv.redhat.com/apinnick/rest-api-update/doc-REST_API_Guide/index.html

Header levels fixed in REST API model.

---

source/community/index.md
source/community/ovirt-counter.md

- Proposing an oVirt counter
This pull request needs review by: @oVirt/developers

Add community oVirt counter

---

source/documentation/common/vgpu/proc_setting-up-nvidia-vgpu-devices.adoc

Fixes issue # | https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-47
- update link and instructions for download and install of NVIDIA vGPU driver in NVIDIA guide
note: this guide is only available in the downstream RHV document set

rhvddf-47  update NVIDIA vGPU install instructions

---

source/documentation/doc-Release_Notes/chap-Release_Notes.adoc
source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.2.adoc

Fixes issue # | https://issues.redhat.com/browse/RHV-47710
- compile release notes and test
- Preview: http://file.tlv.redhat.com/emarcus/relnotes452/

relnotes452  compilation

---

source/documentation/administration_guide/topics/proc_setting-up-debug-level-logging.adoc

Fixes issue # | [BZ 2064326](https://bugzilla.redhat.com/show_bug.cgi?id=2064326)  (delete if not relevant)
- note regarding sensitive information in debug-level logs

BZ#2964326 add note regarding debug-level logs

---

source/release/4.5.3/index.md

Create release notes for oVirt 4.5.3 GA

---

source/develop/qa/index.md
source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml

Signed-off-by: Lev Veyde <lveyde@redhat.com>
- Update latest version references to 4.5.3

Update latest version references to 4.5.3

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories.adoc
source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/doc-Java_SDK_Guide/topics/Downloading_the_Java_SDK.adoc
source/documentation/doc-Python_SDK_Guide/topics/Installing_the_Software_Development_Kit.adoc

Bug-Url: https://bugzilla.redhat.com/2132388
Signed-off-by: Martin Perina <mperina@redhat.com>

Fix RHEL version to 8.6 and subscribe to RHEL EUS channels

---

source/documentation/common/prereqs/ref-Manager_Firewall_Requirements.adoc

Bug fix
Fixes issue [BZ2139483](https://bugzilla.redhat.com/show_bug.cgi?id=2139483)  
- Fix port number
This pull request needs review by: @emarcusRH

BZ2139483: Fix port number

---

source/documentation/common/upgrade/proc-Replacing_SHA-1_Certificates_with_SHA-256_Certificates.adoc

Signed-off-by: Avital Pinnick <apinnick@redhat.com>
Bug fix
Fixes [BZ 2137508](https://bugzilla.redhat.com/show_bug.cgi?id=2137508) 
- Update openssl command

BZ2137508: Fix openssl command

---

source/documentation/common/upgrade/proc-Changing_Virtual_Machine_Cluster_Compatibility.adoc
source/documentation/common/upgrade/proc-Changing_the_Cluster_Compatibility_Version.adoc

Fixes issue # | [BZ#2129697](https://bugzilla.redhat.com/show_bug.cgi?id=2129697) 
in https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/upgrade_guide/index#Changing_Virtual_Machine_Cluster_Compatibility_minor_updates
- change to  boot from inside guest operating system is possible 

BZ#2129697 fix sentence on cluster compatibility update

---

source/documentation/upgrade_guide/chap-Red_Hat_Virtualization_Upgrade_Overview.adoc
source/documentation/upgrade_guide/master.adoc

- Moves SHE upgrade to beginning of doc, since SHE installation is our recommended installation
[Preview](https://ovirt.github.io/ovirt-site/previews/3084/documentation/upgrade_guide/index.html)

Updating upgrade guide structure

---

source/documentation/upgrade_guide/docinfo.xml
source/documentation/upgrade_guide/index.adoc

Revert "Update downstream version number"

---

source/documentation/virtual_machine_management_guide/topics/Configuring_Single_Sign_On_for_Windows_Virtual_Machines.adoc
source/documentation/virtual_machine_management_guide/topics/Updating_the_Guest_Agents_and_Drivers_on_Windows.adoc

Bug fix
Fixes [BZ#1939787](https://bugzilla.redhat.com/show_bug.cgi?id=1939787)
* update ovirt-win guest agent tools installation in the Virtual Machine Management guide
- sec 4.2.2 - Configuring Single sign-on for Windows Virtual Machines
Preview: https://ovirt.github.io/ovirt-site/previews/3090/documentation/virtual_machine_management_guide/index.html#sect-Configuring_Single_Sign-On_for_Virtual_Machines
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @emarcusRH
This pull request needs review by: @germanovm

BZ#1939787 update ovirt-win guest agent tools installation

---

source/documentation/virtual_machine_management_guide/topics/Installing_the_Guest_Agents_and_Drivers_on_Windows.adoc
source/documentation/virtual_machine_management_guide/topics/Updating_the_Guest_Agents_and_Drivers_on_Windows.adoc

Bug fix
Fixes [BZ#1884627](https://bugzilla.redhat.com/show_bug.cgi?id=1884627)
**updating guest agent for Windows installation in VMM guide:**
*   sec 6.6.3 Updating Windows guest agents and drivers using the command prompt
Preview: https://ovirt.github.io/ovirt-site/previews/3091/documentation/virtual_machine_management_guide/index.html#Updating_the_Guest_Agents_and_Drivers_on_Windows
*  sec 3.3.2 Installing the guest agents, tools, and drivers on Windows
Preview: https://ovirt.github.io/ovirt-site/previews/3091/documentation/virtual_machine_management_guide/index.html#Installing_the_Guest_Agents_and_Drivers_on_Windows 
I confirm that this pull request was submitted according to the [contribution …

BZ#1884627 update guest agent installation 

---

source/documentation/common/collateral_files/_attributes.adoc
source/documentation/common/prereqs/ref-Manager_Operating_System_Requirements.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc
source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc

Bug fix
Fixes issue # [3098](https://github.com/oVirt/ovirt-site/issues/3098)
- Add attribute for latest supported RHEL version so that it is not hard-coded into the docs
-
-

GH3098: Update supported RHEL version

---

.github/workflows/preview.yml
.github/workflows/remove-preview.yml
htmlproofer_test.rb
source/documentation/doc-Introduction_to_the_VM_Portal/topics/Creating_virtual_machines.adoc

Bug fix
Fixes issue #2826
- Fix command line for running htmlprrofer

automation: fix htmlproofer execution

---

source/release/4.5.4/index.md

- Update 4.5.4 with async update content
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

4.5.4: add async 1 release notes

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc

- Marked module enablement instructions as specific to el8.
This pull request needs review by: @oVirt/ovirt-documentation 
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

adjust instructions following el9 support

---

source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc

Appliance needs to be upgraded to latest bits during deployment
[Bug fix]
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2159724
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md):
This pull request needs review by: @emarcusRH

note about upgrading appliance

---

source/documentation/administration_guide/chap-Users_and_Roles.adoc
source/documentation/administration_guide/topics/Adding_OVN_as_an_External_Network_Provider.adoc
source/documentation/administration_guide/topics/account_settings_UI.adoc
source/documentation/virtual_machine_management_guide/topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc

Fixes issue # [BZ#2059942](https://bugzilla.redhat.com/show_bug.cgi?id=2059942)  
- add description of Administration user Account Settings / properties screen
- fix glitch -  visible comment in [Admin Guide sec 2.9.2.7.3](https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/administration_guide/index#Connecting_an_OVN_Network_to_a_Physical_Network) 
**Previews:** 
https://ovirt.github.io/ovirt-site/previews/3110/documentation/administration_guide/index.html#sect-Red_Hat_Enterprise_Virtualization_Manager_User_Tasks
https://ovirt.github.io/ovirt-site/previews/3110/documentation/virtual_machine_management_guide/index.html#Opening_a_Serial_Console_to_a_Virtu …

BZ#2059942  add new Administration Portal user options

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc

[Bug fix]
Fixes issue # |[BZ#1939973](https://bugzilla.redhat.com/show_bug.cgi?id=1939973) 
-  update SHE installation w/manager package update procedure
PREVIEW here: http://file.tlv.redhat.com/emarcus/BZ1939973/#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_install_RHVM

BZ#1939973 update SHE installation w/manager package update procedure

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories.adoc
source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/install/snip-RHVM_repo_steps.adoc
source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc

Bug fix
Fixes [BZ#2166824](https://bugzilla.redhat.com/show_bug.cgi?id=2166824) and [BZ#2166822](https://bugzilla.redhat.com/show_bug.cgi?id=2166822)
- Add missing backslash
-
-

fix repo list

---

source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/doc-Java_SDK_Guide/topics/Downloading_the_Java_SDK.adoc
source/documentation/doc-Python_SDK_Guide/topics/Installing_the_Software_Development_Kit.adoc

Fixes issue # | [RHVDDF-43](https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-43)  (delete if not relevant)
- Fix subscription channel lists in Upgrade guide
- Remove old note re RHEL 8.6 EUS repo

RHDDF-43 Fixing channel subscription lists in Upgrade Guide

---

source/documentation/common/database/proc-disabling-the-data-warehouse-service.adoc

Fixes issue # | [RHVDDF-52](https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-52)  
- add step for stopping Grafana service in DWH migration procedure
DOWNSTREAM ONLY - 
Previews need to be manually generated

RHVDDF-52 add step for stopping Grafana service in DWH migration procedure

---

source/documentation/common/upgrade/snip-Host_update_limitations.adoc

Fixes issue # | [RHVDDF-55](https://issues.redhat.com/projects/RHVDDF/issues/RHVDDF-55)  
-  remove confusing bullet from upgrading hosts limitations

RHVDDF-55 remove confusing bullet from upgrading hosts limitations

---

source/documentation/upgrade_guide/topics/Updating_the_Local_Repository_for_an_Offline_Red_Hat_Virtualization_Manager_Installation.adoc

Fixes issue # | [BZ#2167625](https://bugzilla.redhat.com/show_bug.cgi?id=2167625)
- add switch to reposync command
This pull request needs review by: (please @RichardHoch )

BZ#2167625 add switch to reposync in Upgrade Guide APP A

---

source/documentation/administration_guide/topics/Assigning_Additional_IPv4_Addresses_to_a_Host_Network.adoc

Fixes issue # | [BZ#2168149](https://bugzilla.redhat.com/show_bug.cgi?id=2168149) 
-  Update vdsm install instructions - Admin Guide / adding IPv4 addresses to a network

BZ#2168149 update instructions for vdsm install Admin Guide

---

source/documentation/virtual_machine_management_guide/topics/Installing_Windows_on_Virtio_Optimized_Hardware.adoc

Fixes issue # | [RHVDDF-59](https://issues.redhat.com/browse/RHVDDF-59) 
-  VMM guide sec 3.2.1 Installing Windows on VirtIO-optimized hardware, remove incomplete sentence fragment-

RHVDDF-59 remove incomplete sentence fragment from VMM guide 3.2.1

---

source/documentation/virtual_machine_management_guide/topics/conc-nvdimm-host-devices.adoc

Fixes issue # | [BZ#1894067](https://bugzilla.redhat.com/show_bug.cgi?id=1894067)  
- add comment re NVDIMM

BZ@1894067 add comment re NVDIMM - VMM guide

---

source/documentation/common/install/proc_installing-a-vdsm-hook.adoc

Fixes issue # | [BZ#2060274 ](https://bugzilla.redhat.com/show_bug.cgi?id=2060274)  
-  add host maintenance mode to VDSM hook install-

BZ#2060274 add host maintenance mode to VDSM hook install

---

source/documentation/administration_guide/topics/Shareable_Disks.adoc

Fixes issue # | [BZ#1845946](https://bugzilla.redhat.com/show_bug.cgi?id=1845946) 
- Admin Guide/Shareable disks - note regarding shareable formats

BZ#1845946 note regarding shareable formats

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc
source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-5.adoc
source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-5.adoc
source/download/alternate_downloads.md
source/download/index.md

- Wherever there's a description on enabling oVirt repositories also suggest to use nightly snapshots pointing to the user mailing list thread explaining why the suggestion is made.

docs: suggest nightly snapshots

---

source/documentation/common/upgrade/assembly-Updating_a_self-hosted_engine.adoc
source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc

Fixes issue # | [BZ#2186182 ](https://bugzilla.redhat.com/show_bug.cgi?id=2186182)  
-  add note and emphasis for updating repositories during upgrade

BZ#2186182 added emphasis for updating repositories during upgrade

---

source/develop/qa/index.md
source/documentation/index.haml
source/download/alternate_downloads.md
source/download/index.md
source/index.haml
source/release/4.5.5/index.md

Release 4.5.5

---

source/documentation/common/install/proc-Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories.adoc
source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc

[ Bug fix]
Fixes issue # | [BZ 2262194](https://bugzilla.redhat.com/show_bug.cgi?id=2262194)  
- add TUS repositories to subscription settings in installation of RHV-M and for Linux Host
This pull request needs review by: (please @ctomasko )

BZ 2262194  updates to RHV-M and Linux Host repo subs for install

---

source/dropped/admin-guide/virt/console-client-resources.md

[Bug fix]
Fixes issue #3159 
- trivial fix to url
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @gocallag 

trivial fix to virt-manager.org download link

---

source/community/about/board.md

- Added Jean-Louis Dupond to oVirt Board members.
Announced via https://blogs.ovirt.org/2025/01/welcome-jean-louis-dupond-to-the-ovirt-board/
- Took the chance to fix markdown syntax.

Add Jean-Louis Dupond to oVirt Board

---

data/authors.yml
source/download/install_on_rhel.md

Bug Fix
Fixes issue #3187 
Closes issue #3187
* Tested on Alma 9.x, Centos 9 Stream and RHEL 9.x
* Removed notes about bugs that were fixed quite some time ago
* Removed EL8 notes
* Added details on how to use the nightly builds as there hasn't been a
release for some time.
* Added author (gocallag)
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @gocallag 
This pull request needs review by: @JasperB-TeamBlue

Streamlined and validated the installation instructions.
