source/develop/infra/infrastructure.html.md
=> changed infra team assignments link

source/develop/infra/infrastructure.html.md
(JFWIW: it was originally improperly formatted on the wiki as well)
This fixes issue #17.
=> fixed formatting in a list within a list

source/develop/infra/jenkins.html.md
=> overhauled Jenkins infra page with tons of fixes (mainly formatting)

data/navigation.yml
=> updated navigation: reordered and added blog

data/site.yml, source/layouts/_breadcrumbs.haml, source/layouts/layout.html.haml, source/stylesheets/_bootstrap-includes.sass, source/stylesheets/lib/site.sass
=> added breadcrumbs

data/site.yml, source/layouts/_footer.haml, source/stylesheets/lib/site.sass
Addresses #32; code ported & adapted from from rdoproject.org, which, in turn, was ported & adapted from manageiq.org.
=> "Edit on GitHub" link

source/community/get-involved/wiki-rules-and-etiquette.html.md, source/develop/dev-process/working-with-gerrit.html.md, source/develop/developer-guide/vdsm/hook/vmfex.html.md, source/develop/infra/infra-bash-style-guide.html.md, source/develop/infra/phoenix-lab-hosts.html.md, source/develop/infra/phoenix-lab-ssh-spice-tunnel.html.md, source/develop/infra/phoenix-lab-storage-hosts.html.md, source/develop/infra/proxy.html.md, source/develop/release-management/features/storage/cinder-integration.html.md, source/develop/release-management/features/ux/detailedhostpmmultipleagents.html.md, source/develop/release-management/releases/3.3.2/testing.html.md, source/documentation/admin-guide/administration-guide.html.md
When merged, this should fix #21.
=> Code block fixes

source/develop/infra/infrastructure-instances.html.md
=> Infrastructure instances

source/blog/2015-11-30-welcome-to-new-ovirt-site.html.md
Populated the first blog post with draft content relevant to the new Website.
=> Add content to first blog post

source/download/index.html.haml
Uploaded a bit the download page, will require a full sync.
=> Updated download page

README.md
You need to run ./setup.sh before running the site.
=> Updated instructions how to run the website locally

source/develop/dev-process/install-nightly-snapshot.html.md
Previously the two yum commands were shown on the same line.
=> added a newline between commands

source/develop/projects/project-integration.html.md
Added some links to Integration projects
=> Updated project-integration.html.md

source/develop/release-management/releases/3.6/release-management.html.md
Fixed the table of the milestones for 3.6
=> 3.6 release management: fixed table

source/develop/developer-guide/vdsm/todo.html.md
https://trello.com/b/U3lsbVRU/vdsm
=> move a few TODO items to trello

source/develop/release-management/releases/3.6.z/release-management.html.md
=> added 3.6.3 RC4 to 3.6.z release management

source/develop/release-management/features/integration/ovirtappliance.html.md
=> added in-page link to the status section

source/develop/dev-process/working-with-gerrit.html.md
This patch closes issue #91
Change-Id: I40ae7467ff60fde202c22abbfdc46eceb64cc479
=> Escape HTML in working-with-gerrit.html.md

source/download/index.html.haml
Update recommended browsers to remove Chrome, add "ESR" to Firefox.
=> Update recommended browsers

source/community/index.html.md
Fixed the link to the oVirt classification.
=> Fix link to Bugzilla

source/layouts/_notice.haml
=> prepend old. to original wiki links

source/layouts/_production_only.haml
=> tracker JS uses the same resource now (http/https)

source/develop/release-management/releases/3.6.z/release-management.html.md, source/release/3.6.4/index.html.md
"What's new" section pending yet.
=> created ovirt-3.6.4 release notes

source/documentation/admin-guide/administration-guide.html.md
Fixed formatting issues in administration guide. Solve issue #138; Obsolete pull #138
=> Updated administration guide

source/develop/release-management/features/engine/commandcoordinator.html.md
Fit snippets to the new size:
1. remove redundant spaces.
2. remove apostrophes before an angle brackets
=> Cleanup CoCo feature page.

source/develop/release-management/releases/3.6.z/release-management.html.md, source/release/3.6.5/index.html.md
=> added 3.6.5 release notes

source/release/4.0.0/index.html.md
=> added 4.0.0 alpha1 release notes

source/release/4.0.0/index.html.md
=> fixed markdown error in 4.0.0 release notes

source/develop/release-management/features/infra/python-sdk.html.md
Many unbreakable space prevent markdown parsing.
=> Reformatting of python sdk code

source/node/index.html.md
=> Add Node index

source/node/index.html.md
- ISO verification
- Quickstart
- Stream clarification
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> node: Add quickstart and some additional informations

source/documentation/quickstart/quickstart-guide.html.md
This simply adds 3.6 to the quickstart documentation.
=> Update quickstart with latest versions.

source/documentation/admin-guide/virt/console-client-resources.html.md
Blocks https://bugzilla.redhat.com/show_bug.cgi?id=1316560
=> Remove Spice Plugin, since it is unsupported since 4.0

source/release/3.6.6/index.html.md
=> added 3.6.6 release notes

source/develop/release-management/features/gluster-self-heal-monitoring.html.md
Adding feature page for Gluster Self-Heal Monitoring.
=> Feature page for Gluster Self-Heal Monitoring

source/develop/release-management/features/storage/diskalignment.html.md
Improve the Disk Alignment page.
This PR addresses point 292 of issue #37.
=> Disk Alignment

CONTRIBUTING.md
=> added instructions on how to test locally

source/release/3.6.6/index.html.md
=> updated release notes for 3.6.6_rc2

source/documentation/migration-engine-3.6-to-4.0.html.md
=> fixed restore command for engine 3.6 -> 4.0 migration

source/develop/developer-guide/action-permissions-overview.html.md
Fixing issues in the Action Permissions Overview page
=> Improvements to the Actions-Permissions Overview page

source/develop/release-management/features/storage/live-storage-migration-between-mixed-domains.html.md
Fixed the grammar and spelling issues in the page and removed redundant
unused template blocks.
Change-Id: I17fecfc540d0a377c4ead200fccee0f79eb621c8
=> Mixed Domains LSM documentation

source/release/4.0.0/index.html.md
bugs pending. will be updated asap.
=> update release notes for 4.0.0 beta1.

source/release/4.0.0/index.html.md
=> updated 4.0.0 release notes. added bugs

source/release/3.6.7/index.html.md
=> added 3.6.7 release notes

source/release/3.6.6/index.html.md
=> fixed ovirt live url for 3.6.6 release notes

source/develop/release-management/features/sla/deploy-hosted-engine-hosts-via-engine.md, source/develop/release-management/releases/3.5.2/index.html.md
Two issues, hopefully now Travis will not complain.
=> Try to fix Markdown and other errors to make Travis happy.

source/develop/dev-process/install-nightly-snapshot.html.md
3.5 snpahots are not available anymore.
=> Drop 3.5 snapshot from nightly

source/search-results.json.haml, source/search.html.haml, source/stylesheets/lib/search.sass
Fixes #184 by adding semantic version support in searches.
Also, I have added a lot of comments for others to more easily follow along how the search code works.
=> Search semantic versions

source/release/3.6.7/index.html.md
=> updated release notes for 3.6.7

source/release/4.0.0/index.html.md
=> updated release notes for 4.0.0

Gemfile.lock, source/documentation/sla/affinity-labels.html.md
This is a feature page description of the new Affinity Label feature we introduced in 4.0.
=> Add feature page for Affinity Labels

source/release/3.6.7/index.html.md, source/release/4.0.0/index.html.md
=> fixed 3.6.7 RC5 and 4.0.0 RC4 release info

source/blog.html.haml
simple blog container fix & a no-index flag for the search engine
=> Blog container fix

data/site.yml
=> fixed footer links to privacy policy, about, & disclaimers

source/download/index.html.haml
Mirrors need time to be synced befaure updating the section.
=> update download page pointing to 4.0 instructions

source/release/4.0.1/index.html.md
=> added release notes for 4.0.1

source/develop/release-management/features/storage/manage-storage-connections.html.md
Fix and update the Manage Connections page.
=> Manage connections

source/blog/2016-07-04-application-scoped-tests-for-ovirt-with-arquillian.html.md
Hi a technical post for engineers working on the engine. I also published it on [my blog] (http://rmohr.github.io/continuous%20integration/2016/07/04/application-scoped-tests-for-ovirt-with-arquillian).
=> Blog post on how to write application scoped unit tests for oVirt

config.rb, lib/blog_helpers.rb, source/tag.html.haml
ported several tag updates from the Red Hat Community site (community.redhat.com)
=> Tag updates

CONTRIBUTING.md, MAINTAINING.md
This document describes best practices and guidelines for the oVirt site maintainers.
=> Created maintainers guide for ovirt github site

source/documentation/how-to/hosted-engine-host-OS-upgrade.html.md
typo chane->change
'`' for inline code
=> hosted-engine-host-OS-upgrade: Minor fixes

source/download/ovirt-live.html.md
Added 4.0.1 release and updated links to jenkins jobs
=> Release oVirt Live 4.0.1

source/release/4.0.1/index.html.md
=> Released oVirt 4.0.1

source/documentation/admin-guide/serial-console-setup.html.md
Rephrase the steps or add more details to make the documentation
friendlier. No new content.
=> serial console: clarify the customization steps

source/develop/release-management/features/migration-enhancements.html.md
Since the feature has been designed the testing showed some issues with it and
the implemented feature has diverged from it. 
This patch rewrites the documentation to match the actual implementation.
=> Rewritten the migration enhancements feature page to match reality

source/documentation/quickstart/quickstart-guide.html.md
I *think* this fixes a few, but since git-hub preview is significantly different than the actual website, it's hard to tell.
=> fix a few more multi-line-wrapped-into on

source/blog/2016-06-18-ovirt-engine-4_0-setup-in-fedora24.html.md
Signed-off-by: yquinn <yquinn@redhat.com>
=> 2016-06-18-ovirt-engine-4_0-setup-in-fedora24.html.md

source/release/4.0.2/index.html.md
Added cockpit-ovirt related notes and updated ovirt-engine notes after respin
=> Updated 4.0.2 release notes

source/develop/developer-guide/vdsm/developers.html.md
Adding a require py3 package: yaml.
=> vdsm devel: Require python3-yaml (for fedora)

source/documentation/index.html.haml
Added link to releases directory so micro releases will be accessible.
Added link to 4.0.0 release
=> Updated release notes links

source/documentation/index.html.haml
=> fixed YouTube ID rewriting of embedded videos

source/develop/release-management/releases/4.0.z/release-management.html.md
- Added 4.0.2 rc3 to the schedule
=> Added 4.0.2 rc3

source/release/4.0.2/index.html.md
- Updated 4.0.2 rc3 release notes
=> Update 4.0.2 rc3 release notes

source/develop/dev-process/working-with-gerrit.html.md
=> Link to commit-msg hook without authentication

source/develop/developer-guide/vdsm/developers.html.md
also drops a link to a long-defunct list.
=> add python3 to the list of required pacakages

.gitignore
- Adds IntelliJ IDEA related files to `.gitignore`.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @idanshaby
=> Ignore IntelliJ IDEA related files

source/develop/release-management/releases/4.0.z/release-management.html.md
- Added 4.0.2 rc4 and ga to the schedule
=> Added 4.0.2 rc4 and ga

source/release/4.0.2/index.html.md
- Update releases notes to 4.0.2 RC4
=> Update to 4.0.2 rc4

source/node/faq.md
turning the quickstart address to a hyperlink
=> turning the quickstart address to a hyperlink

source/develop/release-management/releases/4.0.z/release-management.html.md
-Postponed 4.0.2 GA by one day
=> Postponed 4.0.2 GA by one day

source/release/4.0.2/index.html.md
- Update release notes to 4.0.2 GA
=> Update release notes to 4.0.2 GA

source/download/ovirt-live.html.md
- Updated oVirt lIve with 4.0.2 release
=> Updated oVirt lIve with 4.0.2 release

source/develop/developer-guide/vdsm/hooks.html.md
This pull request needs review by: @mureinik @nirs
=> Fix code snippets in VDSM hooks page

source/develop/release-management/features/engine/metrics-store.html.md
=> Add Metrics Stores

data/authors.yml
Adds my user to authors.yml.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @idanshaby
=> Add idanshaby to authors.yml

source/develop/developer-guide/vdsm/developers.html.md
=> Updating 4.0 repo link

source/develop/release-management/features/storage/wipe-volumes-using-blkdiscard.html.md
Introduce a new feature page - *Wipe volumes using blkdiscard*.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @idanshaby
This pull request needs review by: @mureinik @mykaul @nirs @rollandf @tnisan
=> Wipe volumes using blkdiscard

source/develop/release-management/features/storage/discard-after-delete.html.md
Introduce a new feature page - *Discard after delete*.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @idanshaby
This pull request needs review by: @mureinik @mykaul @rollandf @tnisan
=> Discard after delete

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Update 4.0.3 schedule

source/release/4.0.3/index.html.md
- Created oVirt 4.0.3 release notes
This pull request needs review by: @mwperina @fbacchella @tiraboschi @fabiand
=> Created oVirt 4.0.3 release notes

source/node/index.md
=> Fix dead links

Gemfile, Gemfile.lock
=> fixed missing dependencies for fetch-dashboard.rb

source/blog/2016-07-27-Manage-Your-Hosted-Engine-Hosts-Deployment.html.md
=> Fix type mistake

Dockerfile
=> Dockerfile missing dependency zlib-devel

source/release/4.0.3/index.html.md
- Update release notes with 4.0.3 GA notes
=> Released oVirt 4.0.3

source/download/ovirt-live.html.md
- Update oVirt lIve page with 4.0.3 release
=> oVirt Live 4.0.3 has been released

source/develop/release-management/releases/4.0.z/release-management.html.md
- Updated 4.0.3 schedule including GA release issued today.
=> Updated 4.0.3 schedule

source/release/4.0.4/index.html.md
Changes proposed in this pull request: Added release notes for 4.0.4 RC1
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @rafaelmartins
This pull request needs review by: @sandrobonazzola 
=> Added release notes for 4.0.4

source/community/index.html.md
- Add link to oVirt's YouTube channel in community page
=> Add link to oVirt's YouTube channel in community page

source/develop/release-management/features/storage/copy-disks.html.md
- Add feature information in the header
This pull request needs review by: @mureinik @jelkosz
=> Fix code formatting in Copy Disks feature page

source/release/4.0.4/index.html.md
Changes proposed in this pull request: updated release notes for 4.0.4 rc2
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @rafaelmartins
=> update 4.0.4 release notes for rc2

source/develop/release-management/features/storage/mixed-types-data-center.html.md
Fixes item 306 of issue #37 
- Fix header block
- Fix markdown issues
- Improve spelling/grammar
- Update information to current version
This pull request needs review by: @tnisan
=> Mixed types data center

source/develop/release-management/features/storage/online-virtual-drive-resize.html.md
Fixes point 306 of issue #37 
- Fix code formatting issues created during the MediaWiki migration
This pull request needs review by: @rollandf @danielerez
=> Fix code formatting for Online Disk Resize

source/develop/release-management/releases/3.5.z/release-management.html.md
- Fixed tables layout for 3.5.z release management
This pull request needs review by: @tiraboschi
=> Fixed tables layout for 3.5.z release management

source/release/4.0.4/index.html.md
=> Update 4.0.4 release notes

source/develop/release-management/releases/4.0.z/release-management.html.md
- Added oVirt 4.0.4 Schedule
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): (@sandrobonazzola
=> oVirt 4.0.4 Schedule

source/release/4.0.4/index.html.md
- Last minutes updates for 4.0.4 rc4
=> Last minutes updates for 4.0.4 rc4

source/develop/release-management/features/storage/virtio-scsi.html.md
=> Fix code format in virtio-scsi feature page

source/develop/release-management/features/storage/spmpriority.html.md
Fixes point 313 of issue #37 
- Fix the page layout
- Fix some typos
- Update the fact that is was released back in oVirt 3.1
This pull request needs review by: @tnisan @laravot @rollandf
=> SPM Priority

source/index.html.haml
- Update home page pointing to 4.0.4
=> Released oVirt 4.0.4

source/blog/2016-09-26-manage-ovirt-with-ansible-playbooks.html.md
- Added new blog on Ansible playbooks
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): (please @bproffit yourself to sign)
This pull request needs review by: Reviewed
=> Ansiblemoduleblog

source/community/activities/outreachy.html.md
=> Changed the outreachy landing page to be more up-to-date

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Added 4.0.5 schedule

source/develop/release-management/features/storage/iscsi-multipath.html.md
=> Fix code format in iSCSI Multipath feature page

source/develop/release-management/features/storage/single-disk-snapshot.html.md
=> Fix code format in Single Disk Snapshot feature page

source/release/4.0.5/index.html.md
- Created oVirt 4.0.5 RC1 release notes
This pull request needs review by: @rafaelmartins @fabiand @mwperina
=> Created oVirt 4.0.5 RC1 release notes

source/blog/2016-09-30-new-ovirt-video-tutorials-available.html.md
Changes proposed in this pull request: Added a new blog for Sept. 30
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @bproffit
=> Added 093016 blog

source/develop/release-management/features/storage/serial-execution-of-asynchronous-tasks.html.md
- Document that SEAT was removed completely in 4.1
=> SEAT: Document the removal in 4.1

source/develop/release-management/features/gluster/gdeploy-cockpit-integration.html.md
Fix a minor formatting issue in gluster gdeploy-cockpit feature page.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @dpmramesh
This pull request needs review by: @sandrobonazzola @bproffitt
=> fix minor issue in gdeploy-cockpit feature page

source/develop/release-management/features/storage/ovfautoupdater.html.md
Fixes point 310 of issue #37
- Fix typos
- Fix markdown generated incorrectly from the MediaWiki conversion
This pull request needs review by: @laravot
=> Fix Ovfautoupdater page

source/develop/release-management/features/storage/DataCenterV4_1.html.md
-
-
-
This pull request needs review by: (please @mureinik @mykaul the reviewer if relevant)
=> Feature page: Add documentation for 4.1 DC.

source/develop/release-management/features/storage/backup-restore-api-integration.html.md
=> Feature page Backup-Restore API Integration

source/documentation/architecture/architecture.html.md
- documentation edits.
minor edits and spelling corrections
=> minor edits and spelling corrections

source/develop/release-management/features/engine/engine-backup.html.md
-
-
-
Put the most useful things first
Mention that extra users are created with random passwords
=> engine-backup.html.md: Rearrange Restore

source/develop/release-management/features/infra/ansible_modules.html.md
-
-
-
In markdown links works fine, but on ovirt.org site it doesn't.
This patch fixes it.
=> Fix links in modules table

source/develop/release-management/features/storage/live-storage-migration-between-mixed-domains.html.md
Add details as to when this feature was released.
=> LSM between mixed domains status

source/develop/release-management/features/storage/importmorethanonce.html.md
=> Fix code format in Import Vm More Than Once

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Update 4.0.5 schedule

source/release/4.0.5/index.html.md
- Update 4.0.5 release notes with RC2 content
=> Update 4.0.5 release notes

source/develop/developer-guide/vdsm/developers.html.md
Bug 1382317 of bugzilla@redhat.com
Added dnf commands for Fedora 
* Update developers.html.md
* Update developers.html.md
=> Update developers.html.md (#1)

source/documentation/quickstart/quickstart-guide.html.md
- The url in the text referred to an outdated repo that doesn't contain all the packages
-
-
=> outdated url for 3.6 repo

config.rb
=> fix stats proxy config, missing extension

source/community/user-stories/users-and-providers.html.md
- Updated users and providers page changing RHEV to RHV
=> Update RHEV -> RHV brand

source/develop/release-management/features/node/node-next-persistence.html.md
- Add a feature page for Next Gen Node RPM persistence
This pull request needs review by: @fabiand @dougsland @irosenzw
=> Add a feature page for page for NGN RPM persistence

source/blog/2016-10-13-call-for-proposal-fosdem-2017.html.md
=> updated 101316 blog

source/release/4.0.5/index.html.md
- Updated 4.0.5 Release notes with RC3 content
=> Updated 4.0.5 Release notes with RC3 content

source/download/index.html.haml
- Update Download page pointing to 4.0.4
=> Update Download page pointing to 4.0.4

source/documentation/index.html.haml
- Added Categories giving access to inner documentation
=> Update Documentation page

source/documentation/index.html.haml
- Live website behave differently than local instance, adding duplicate documentation folder.
Dropping it.
=> Fix categories links

source/documentation/how-to/guest-agent/install-the-guest-agent-in-ubuntu.html.md
=> added 16.04 instructions

source/documentation/admin-guide/hosted-engine-backup-and-restore.html.md
emphasize commands and terminal output
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @mbghsource
to emphasize commands and terminal output
=> formatting changes

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Added 4.0.5 RC4 schedule

source/release/4.0.5/index.html.md
- Updated 4.0.5 release notes with RC4 content
=> Updated 4.0.5 release notes

source/community/about/community-guidelines.html.md
- Corrects poor merge of code of conduct
=> Updated community guidelines

data/authors.yml
- Add sandrobonazzola twitter account
=> Add sandrobonazzola twitter account

source/develop/dev-process/unit-testing-utilities/mockconfigrule.html.md
- Update `MockConfigRule`'s page to match the current code
- Fix typos
- Fix formatting
=> MockConfigRule

source/blog/2016-10-28-setting-community-values.html.md, source/blog/2016-11-01-setting-community-values.html.md
- New blog highlighting the new code of conduct
=> Added 102816 blog

source/develop/release-management/features/network/import-vm-net-changes.html.md
Update import-vm-net-changes page with proper URLs and xml example.
This pull request needs review by: @mmirecki
=> Update import-vm-net-changes page with proper URLs and xml example.

source/develop/release-management/releases/4.0.z/release-management.html.md
- Updated 4.0.5 Release schedule with RC5 and GA dates
=> Updated 4.0.5 Release schedule

data/authors.yml
- Add Rafael Martins to authors
=> Add Rafael Martins to authors

source/blog/2016-11-01-setting-community-values.html.md
=> Fixed internal link

source/blog/2016-11-02-ovirt-provider-ovn.md
=> Updated OVN blog to today's date

source/blog/2016-11-02-ovirt-provider-ovn.md
=> Ovirt provider OVN blog - corrections

source/documentation/how-to/hosted-engine.html.md
Fixes issue #578 
- Link repaired, and integrated into the text.
=> Fixed link per issue #578

source/develop/release-management/features/network/liveMigrationSupportForSRIOV.html.md
added manual procedure instructions for sr-iov live migration
@leongold
@dankenigsberg
=> sr-iov migration: added manual procedure instructions

source/blog/2016-11-02-ovirt-provider-ovn.md
=> Modifying links on OVN blog site.

source/develop/release-management/features/engine/windows-guest-tools.html.md
cleanup formatting
update oVirt version 3.5 to 4.0
remove confusingly named links:
All links are named  "oVirt Windows Guest Tools" each one pointing to different locations.
=> formatting and link cleanup

data/authors.yml
- Updates Martin Sivak's author name
=> Update Martin Sivak

source/develop/index.html.md
Not sure if this change is the correct one or this one http://www.ovirt.org/develop/release-management/process/release-process/
=> try to fix a broken link

source/documentation/index.html.haml
-
-
-
I notice quite a few links in the documentation lead to a "Not found" page with a set of search results.
I was quite frustrated by this. Such frustration reflects badly on a oVirt, a project that I wish to succeed.
Since I don't know a good way to find what those links should be, 
I thought it might save other users the trouble of discovering that those links are broken.
=> identify broken links and add newer links

source/release/4.0.5/index.html.md
- Updated release notes for 4.0.5 GA
=> Release 4.0.5 GA

source/blog/2016-08-26-up-and-running-with-ovirt-4-0-and-gluster-storage.html.md
=> fix broken link to community

source/documentation/quickstart/quickstart-guide.html.md
=> fix broken link to User Portal Guide

source/documentation/admin-guide/administration-guide.html.md
Current link http://www.ovirt.org/Features/vm-init-persistent#Custom_Script is broken.
Perhaps this is correct link  http://www.ovirt.org/develop/release-management/features/virt/vm-init-persistent#Custom_Script
=> fix broken link

source/develop/release-management/features/virt/ram-snapshots.html.md
- Fix the feature header
- Fix formatting issues introduced by the migration from the old MediaWiki
- Fix typos
=> Ram snapshots

source/develop/release-management/features/storage/storagedomainliveupgrade.html.md
- Fix feature template
- Update the current status (released in 3.1)
- Minor grammar and phrasing improvements
This pull request needs review by: @nirs / @laravot / @maorlipchuk
=> Storage Domain Live Upgrade

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Add 4.0.6 Schedule

source/develop/release-management/features/storage/storagepool-metadata-removal.html.md
- Added missing entries in the header
- Fixed some markdown issues created by the migration to markdown
- Removed some dead parts of the old template
- Fixed some typos and punctuation issues
This pull request needs review by: @nirs / @laravot
=> StoragePool Metadata Removal cleanup

source/community/user-stories/alter-way-case-study.html.md, source/community/user-stories/it-novum-case-study.html.md, source/community/user-stories/user-stories.html.md
- Repairs images for Alter Way and IT-Novum case studies.
=> Case study images

source/develop/release-management/features/storage/vm-leases.html.md
This adds a feature page for the vm leases feature for 4.1.
@mureinik, @aglitke, @michalskrivanek @ahadas, @oourfali  please review.
=> vm-leases: add feature page

source/release/4.0.6/index.html.md
- Added release notes for 4.0.6 RC2
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @rafaelmartins
This pull request needs review by: @sandrobonazzola 
=> added release notes for 4.0.6 rc2

source/develop/developer-guide/engine/writing-a-new-user-query.html.md, source/develop/release-management/features/infra/user-portal-permissions.html.md
- Move the "Writing a new User Query" page to the right place
- Fixed markdown
- Fixed typos
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): (please @mureinik)
=> Writing a new user query

source/blog/2016-11-14-testing-ovirt-changes-without-cluster.md
- Fixed download link
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @bproffit
=> Fixed link for download script

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Update 4.0.6 Schedule

source/develop/release-management/features/storage/image-upload.html.md
Update image I/O page with the relevant changes.
=> Update Image I/O page.

source/release/4.0.6/index.html.md
- Update release notes to 4.0.6 RC3 content
=> Update release notes to 4.0.6 RC3 content

source/develop/release-management/releases/4.1/release-management.html.md
- Initial 4.1 release management page
=> Initial 4.1 release management page

source/release/4.1.0/index.html.md
- oVirt 4.1.0 beta release notes
This pull request should be reviewed (and improved) by: @rafaelmartins @michalskrivanek @mwperina @oourfali @mureinik @machacekondra @jhernand @didib @tiraboschi @mareklibra @vinzenz @mojaves @mykaul @fabiand @dankenigsberg @MarSik and probably many others.
=> oVirt 4.1.0 beta release notes

source/develop/release-management/features/infra/user-portal-permissions.html.md
- Fix feature header
- Fix markdown issues
- Fix typos
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): (@mureinik)
=> User Portal Permissions

source/blog/2016-11-02-ovirt-provider-ovn.md
=> Updated links on ovirt-provider-ovn blog

source/develop/developer-guide/porting-ovirt.html.md
- Update Porting oVirt page
- Add support details for RHEL based distributions and Fedora based distributions
- Add Arch Linux
This pull request needs review by: @rafaelmartins @mykaul @mz-pdm @mwperina and probably others.
=> Updated Porting oVirt

source/blog/2016-12-02-ovirt-november-newsletter.md
=> Added 120216 blog

source/develop/release-management/features/sla/hosted-engine-edit-configuration-on-shared-storage.html.md
Add feature page to allow editing hosted engine configuration on shared storage
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @jtokar
This pull request needs review by: @MarSik @doron-fediuck
=> Feature page - edit HE shared storage config

source/documentation/admin-guide/administration-guide.html.md
=> Added chapter to Administration Guide about disk sparsification.

source/blog/2016-12-06-new-oVirt-project-underway.md
- Added new blog about project status changes 
=> 120616blog

source/develop/release-management/features/network/arbitraryvlandevicename.html.md
- Fix indexing
- Remove html tags
- Change vlan to VLAN
This pull request needs review by: @dankenigsberg
=> Fix format in "arbitrary vlan device name"

.github/CONTRIBUTING.md
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @jniederm
This pull request needs review by: @garrett 
If required metadata is missing, CI build is failing with very cryptic
message. This notice informs contributer what metadata is required.
=> Description of required metadata

source/develop/release-management/features/infra/ansible_modules.html.md
=> Update ansible modules feature page

source/develop/release-management/features/engine/virtio-rng-enhancements.html.md
=> Feature page Virtio RNG Enhancements

source/release/4.0.6/index.html.md
- Updated 4.0.6 release notes with RC4 content
=> Updated 4.0.6 release notes

source/develop/release-management/features/network/bridgeless-networks.html.md
- Minor fixes
This pull request needs review by: @dankenigsberg @rgolangh
=> Fix code format in "bridgeless networks"

source/release/4.0.6/index.html.md
- Updated 4.0.6 Release notes with RC5 content
=> Updated 4.0.6 Release notes with RC5 content

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Added 4.0.6 RC5

source/develop/release-management/features/storage/qcow2v3.html.md
New pull request of qcow2v3 since the last repository encountered problems
-
-
This pull request needs review by: @rollandf @mureinik
=> qcow2v3: Add feature page.

source/blog/2016-12-08-the-need-for-speed.html.md
I did not complain but reported an issue.
@ifireball, @rollandf please review.
=> Fix url and pick a better word

source/develop/release-management/releases/4.0.z/release-management.html.md
=> Updated 4.0.6 schedule

source/develop/developer-guide/vdsm/developers.html.md
@MarSik, @rollandf, @dankenigsberg, please review.
=> vdsm-developers: Add missing docs about tox

source/release/4.1.0/index.html.md
- Update release notes with 4.1.0 beta2
This pull request needs review by: @mwperina @tiraboschi
=> Update release notes with 4.1.0 beta2

source/develop/release-management/features/storage/vm-leases.html.md
- Change the APIs to standard SPM tasks, since we don't have
infrastructure to run SPM jobs yet.
- Update the volume format so sanlock can use the same format in a
future version.
- Format raw link to gerrit
- Fix some typos
@mureinik, @rollandf, @aglitke, @teigland, please review.
=> vm-leases: Update feature page

source/develop/developer-guide/engine/engine-development-environment.html.md
- Make bold the 'root' user , in the create DB user section
- Fix a "red" color
This pull request needs review by: @sleviim @idanshaby
=> Fix some format in Engine dev env page

source/develop/release-management/features/sla/hosted-engine-edit-configuration-on-shared-storage.html.md
- text formatting for the feature page on editing HE shared storage configuration
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jtokar
=> Formatting and wording

source/develop/developer-guide/vdsm/developers.html.md
Fixes type: changes proposed in this pull request:
- changing f* to fc* in link url
Yaniv Bronhaim <bronhaim@gmail.com>
=> changing f* to fc* - typo fix

source/develop/developer-guide/vdsm/tasks.html.md
- Fix image link in 'VDSM tasks' page
=> Fix image link in VDSM tasks page

source/develop/release-management/features/infra/Engine_vacuum.md
This page describes the the engine-vacuum cli tool and the setup plugin that uses it
and is the actual result of the work on https://bugzilla.redhat.com/show_bug.cgi?id=1388430
Please review:
@mykaul @didib @mwperina @mgoldboi
=> Engine vacuum tool and setup plugin feature page

source/blog/2017-01-01-ovirt-system-tests-to-the-rescue.html.md
Signed-off-by: Eyal Edri <eedri@redhat.com>
-
-
-
=> new blog on running OST per patch in CI

source/develop/release-management/features/storage/data-path-operations.html.md
- Add "Data Path Operation" feature page
This pull request needs review by: @aglitke @mureinik @nirs @laravot
=> Add Data Path Operation feature page

source/develop/release-management/features/storage/remove-snapshot.html.md
Added new feature page to describe new enhancements we are planning for Cold Merge
I confirm that this pull request was submitted according to the contribution guidelines: @alhino
Added new feature page to describe new enhancements we are planning
for Cold Merge
=> Feature: Cold Merge

source/release/4.0.6/index.html.md
- Update 4.0.6 release notes for GA
=> Update 4.0.6 release notes for GA

source/index.html.haml
- Update home page with 4.0.6 release
=> Update home page with 4.0.6 release

source/download/index.html.haml
- Update Download page with 4.0.6 release
=> Update Download page

source/develop/release-management/features/engine/maximum-memory-size.html.md
Hi @bproffitt, could you please merge it?
=> Max memory feature page

source/develop/release-management/releases/4.1/release-management.html.md
- Updated 4.1.0 RC1 release date
=> Updated 4.1.0 RC1 release date

source/develop/index.html.md
- Update Develop index adding link to Node team
This pull request needs review by: @evol262 @fabiand
=> Update Develop index adding link to Node team

source/blog/2017-01-16-happy-new-documentation.md
- Added documentation blog that will post after new docs go live.
Please do not merge until new documentation page goes live.
=> Added 011617 blog on new docs

source/documentation/upgrade-guide/chap-Updating_the_oVirt_Environment.html.md, source/documentation/upgrade-guide/upgrade-guide.md
- Repair RH references in Upgrade Guide
=> Fixed Upgrade guide opening

source/documentation/admin-guide/appe-Branding.html.md, source/documentation/admin-guide/appe-Custom_Network_Properties.html.md, source/documentation/admin-guide/appe-System_Accounts.html.md, source/documentation/admin-guide/appe-Using_Search_Bookmarks_and_Tags.html.md, source/documentation/admin-guide/appe-VDSM_and_Hooks.html.md, source/documentation/admin-guide/appe-oVirt_User_Interface_Plugins.html.md, source/documentation/admin-guide/appe-oVirt_and_SSL.html.md, source/documentation/admin-guide/chap-Backups_and_Migration.html.md, source/documentation/admin-guide/chap-Clusters.html.md, source/documentation/admin-guide/chap-Data_Centers.html.md, source/documentation/admin-guide/chap-Errata_Management_with_Foreman.html.md, source/documentation/admin-guide/chap-Event_Notifications.html.md, source/documentation/admin-guide/chap-External_Providers.html.md, source/documentation/admin-guide/chap-Global_Configuration.html.md, source/documentation/admin-guide/chap-Hosts.html.md, source/documentation/admin-guide/chap-Log_Files.html.md, source/documentation/admin-guide/chap-Logical_Networks.html.md, source/documentation/admin-guide/chap-Pools.html.md, source/documentation/admin-guide/chap-Proxies.html.md, source/documentation/admin-guide/chap-Quality_of_Service.html.md, source/documentation/admin-guide/chap-Quotas_and_Service_Level_Agreement_Policy.html.md, source/documentation/admin-guide/chap-Storage.html.md, source/documentation/admin-guide/chap-System_Dashboard.html.md, source/documentation/admin-guide/chap-Users_and_Roles.html.md, source/documentation/admin-guide/chap-Utilities.html.md, source/documentation/admin-guide/chap-Virtual_Machine_Disks.html.md, source/documentation/admin-guide/chap-Working_with_Gluster_Storage.html.md
- Repairs links in Admin Guide
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @bproffitt)
=> Repaired Admin Guide Links

source/documentation/install-guide/Installation_Guide.html.md, source/documentation/install-guide/appe-Attaching_the_Local_ISO_Domain_to_a_Data_Center.html.md, source/documentation/install-guide/appe-Changing_the_Permissions_for_the_Local_ISO_Domain.html.md, source/documentation/install-guide/appe-Configuring_a_Hypervisor_Host_for_PCI_Passthrough.html.md, source/documentation/install-guide/appe-Enabling_Gluster_Processes_on_Gluster_Storage_Nodes.html.md, source/documentation/install-guide/appe-Installing_the_Websocket_Proxy_on_a_different_host.html.md, source/documentation/install-guide/appe-Preparing_a_Local_Manually-Configured_PostgreSQL_Database_for_Use_with_the_oVirt_Engine.html.md, source/documentation/install-guide/appe-Preparing_a_Remote_PostgreSQL_Database_for_Use_with_the_oVirt_Engine.html.md, source/documentation/install-guide/chap-Adding_a_Hypervisor.html.md, source/documentation/install-guide/chap-Configuring_Storage.html.md, source/documentation/install-guide/chap-Enterprise_Linux_Hosts.html.md, source/documentation/install-guide/chap-Installing_oVirt.html.md, source/documentation/install-guide/chap-Introduction_to_Hypervisor_Hosts.html.md, source/documentation/install-guide/chap-Introduction_to_oVirt.html.md, source/documentation/install-guide/chap-System_Requirements.html.md, source/documentation/install-guide/chap-oVirt_Engine_Related_Tasks.html.md, source/documentation/install-guide/chap-oVirt_Nodes.html.md, source/documentation/intro-admin/Introduction_to_the_Administration_Portal.html.md, source/documentation/intro-user/Introduction_to_the_User_Portal.html.md, source/documentation/intro-user/chap-Accessing_the_User_Portal.html.md, source/documentation/intro-user/chap-The_Basic_Tab.html.md, source/documentation/intro-user/chap-The_Extended_Tab.html.md
- Repaired Installation Guide links
=> Repaired Installation Guide links

source/blog/2017-01-19-oVirt-December-2016-newsletter.md
- Posted December 2016 newsletter
=> Added 011917 blog

source/develop/infra/infrastructure.html.md
Just a small update for the team members
=> Added me (Daniel), Gal and Gil to the Infra team list

source/release/4.1.0/index.html.md
- Release notes for 4.0.1 RC1
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @rafaelmartins
=> updated release notes for 4.1.0 rc1

source/develop/release-management/releases/4.1/release-management.html.md
=> Update 4.1.0 Schedule

source/release/4.1.0/index.html.md
- anouncing rc2
- I'm having technicall issues generating release notes but I don't want to hold the announce anymore.
I'll update the notes tomorrow morning when hopefully the issues with the release notes script generator will be fixed.
=> Update the announce to point to rc2

source/develop/developer-guide/engine/engine-development-environment.html.md
=> Redundant quote removed in engine-development-environment.html.md

source/release/4.1.0/index.html.md
- Update oVirt 4.1.0 release notes with rc2 content
=> Update oVirt 4.1.0 release notes with rc2 content

source/documentation/index.html.haml
- Fix community documentation links
=> Fix community documentation links

source/develop/release-management/features/sla/vmpinningtomultiplehosts.html.md
- Fix code snippets
- Remove HTML tags
- Rewording and typos
-Update release information
This pull request needs review by: @mureinik @doron-fediuck
=> Fix VM pinning to multiple hosts

source/develop/release-management/features/sla/hosted-engine-edit-configuration-on-shared-storage.html.md
- Clarified what parts of the feature are implemented
- fixed a typo in one of the editable keys.
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jtokar
This pull request needs review by: @MarSik
=> Fix some documentation errors

source/develop/release-management/features/storage/sharedStorageDomainsAttachedToLocalDC.html.md
- Introducing a new feature page for shared storage domains in local Data Center, describing all the new functionalities and changes
@mlipchuk
@rollandf @mureinik
=> AttachSharedSDToLocalDC: Add feature page.

source/node/faq.md
- Adding information on livecd-tools and ovirt-node-ng
@yuvalturg
=> using livecd-tools with ovirt-node-ng

source/release/4.1.0/index.html.md
- Update 4.1.0 release notes for GA
=> Update 4.1.0 release notes

source/release/4.1.0/index.html.md
1. Changed the order a bit (manually) to highlight more interesting new features.
2. Removed mentioning teams from area that had only a single or two teams. It doesn't
really matter to anyone, and the release notes are way too long as is.
3. Fixed some wording, removed some useless 'Feature: Done' and so on text.
4. Hopefully fixed some escaping for markdown (as seen in Atom).
-
-
-
=> slightly improve the 4.1.0 release notes

source/download/index.html.haml
- Update Download page with 4.1.0 release
=> Update Download page with 4.1.0 release

source/release/4.1.0/index.html.md
=> 4.1 release notes: Add a note about EPEL

source/download/ovirt-live.html.md
=> Added oVirt Live 4.1.0

source/release/4.1.0/index.html.md
- Added note for 4.1.0 async release
=> added 4.1.0 async

source/documentation/index.html.haml
- patches to fix broken links in ovirt.org/documentation 
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @dougsland)
This pull request needs review by: (please @sandrobonazzola @rafaelmartins )
=> ovirt.org/documentation: fix several broken links

source/documentation/index.html.haml, source/download/index.html.haml, source/node/index.md
- fix release notes links
- general improvements for download session
- added more data for node site
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @dougsland)
This pull request needs review by: (please @sandrobonazzola @rafaelmartins )
=> general improvements / node

source/documentation/architecture/migration-communication.html.md
- After recent changes in migration there is a great opportunity to document the communication between Engine and Vdsm during migrations.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mz-pdm
=> Migration communication developer documentation

source/develop/release-management/features/virt/headless-vm.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @sgratch
This pull request needs review by: @ahadas @shaharha
=> headless VM wiki page

source/community/activities/summer-of-code.html.md
- Adding idea to the 2017 GSoC page
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @bproffit
=> Added new idea to GSoC

source/release/4.1.1/index.html.md
- Added 4.1.1 Test Compose release notes
=> Added 4.1.1 Test Compose release notes

data/authors.yml, source/develop/release-management/features/sla/sla-mom-ballooning-tp.html.md, source/develop/release-management/features/sla/sla-mom.html.md, source/develop/release-management/features/vdsm/libvdsm.html.md, source/documentation/internal/guest-agent/guest-agent-proposals.html.md
Update my information on the site so my name is displayed and my correct email address is used.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @aglitke
=> Fix aglitke author

source/develop/developer-guide/engine/engine-tools.html.md
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1120586
- Pointing ovirt-image-uploader section to Administration Guide relevant section.
=> Update ovirt-image-uploader documentation

source/develop/developer-guide/engine/engine-tools.html.md
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1120586
-  Update iso uploader section pointing to administration guide for 4.0
=> Update iso uploader section

source/develop/developer-guide/engine/engine-tools.html.md
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1120588
- Update log collector section pointing to Administration Guide
=> Update log collector section

source/develop/release-management/releases/4.1.z/release-management.html.md
- Create release-management.html.md for 4.1.z
=> Create release-management.html.md for 4.1.z

source/develop/developer-guide/vdsm/vdsclient.html.md, source/develop/developer-guide/vdsm/vdsm-client.html.md
- add documentation for vdsm-client
=> add vdsm-client documentation

source/develop/release-management/features/hot-unplug-memory.html.md
- Feature page for memory hot unplug.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mz-pdm
This pull request needs review by: @jniederm
=> Document memory hot unplug feature

source/release/4.1.1/index.html.md
- Updated 4.1.1 release notes with test compose 2 content
=> Update 4.1.1 release notes

source/community/activities/outreachy.html.md
Update the outreachy wiki page for the current round.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (@jelkosz)
This pull request needs review by: (please @michalskrivanek @jniederm @mz-pdm )
=> Update outreachy page

source/community/activities/outreachy.html.md
Created dialogs may not necessarily end up in webadmin. They may used in other projects.
@jelkosz
=> outreachy.html.md - Dialog rewrite project update

source/documentation/self-hosted/chap-Maintenance_and_Upgrading_Resources.html.md, source/documentation/upgrade-guide/chap-Upgrading_to_oVirt_4.0.html.md
Fixes issue #819 
- Removed references to RHV subscription-manager  that were missed in the initial bootstrap
=> Cleaned up RHV references in oVirt documentation.

source/develop/release-management/features/storage/lun-resize.html.md
- Add version in LUN refresh feature page
=> Add version in LUN refresh feature page

source/release/4.1.1/index.html.md
- Update 4.1.1 release notes with rc1 content
=> Update 4.1.1 release notes with rc1 content

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Added 4.1.1 RC2

source/release/4.1.1/index.html.md
- Update 4.1.1 release notes with rc2 content
=> Update 4.1.1 release notes with rc2 content

source/documentation/architecture/architecture.html.md
Fixes issue #845 
- Fix links to images
=> Fix images links in architecture patch

source/community/index.html.md
Fixes issue #840 
- Changed old MediaWiki instructions to new GitHub instructions
=> Correct community page legacy instructions

source/community/activities/outreachy.html.md
- add outreachy mentorship idea re containerization docs
@jelkosz @michalskrivanek
=> add outreachy containerization docs idea

data/subprojects.yml
- updated list of maintainers
- updated links to oVirt github
- added link to documentation
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jelkosz
This pull request needs review by: @matobet
=> Updated moVirt subproject

source/develop/release-management/features/virt/vm-lifecycle-with-kubevirt.md
New wiki page that details the first phases in integrating ovirt with kubevirt in regards to VM-lifecycle
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @ahadas
This pull request needs review by: @fabiand @michalskrivanek @mykaul
=> Plan for how to delegate parts of VM-lifecycle to Kubevirt

source/develop/release-management/features/sla/hosted-engine-edit-configuration-on-shared-storage.html.md
Added usage examples and some formatting.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jtokar
This pull request needs review by: @MarSik @doron-fediuck
=> Added examples for missing keys

source/release/4.1.1/index.html.md
- Updated 4.1.1 notes with rc3 content
=> Updated 4.1.1 notes with rc3 content

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Updated 4.1.1 schedule

source/community/activities/outreachy.html.md
- Let Outreachy candidates know that no new candidates are accepted for mzamazal's projects.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mz-pdm
=> mzamazal doesn't accept new Outreachy candidates anymore

source/blog/2016-11-02-ovirt-provider-ovn.md
New OVN configuration introduced in OVS 2.7
-
-
-
=> OVN blog: configure OVN to listen to requests on specified ports

source/release/4.1.1/index.html.md
- Updated 4.1.1 release notes for GA
=> Updated 4.1.1 release notes for GA

source/download/index.html.haml
- Update download page with 4.1.1
=> Update download page with 4.1.1

source/blog/2016-11-02-ovirt-provider-ovn.md
Signed-off-by: Marcin Mirecki<mmirecki@redhat.com>
-
-
-
=> OVN blog: provider setup using engine-setup

source/develop/release-management/features/storage/storage_domain_v4.html.md
- Fix link to live storage update
- Fix status of feature
This pull request needs review by: @mureinik @maorlipchuk
=> Fix Storage Domain V4 feature page

source/documentation/how-to/virtual-machines/sealing-linux-vm.html.md
Since there is ansible role that perform the sealing steps above it might be useful to include it here.
=> Add info about ansible-role-seal

source/community/activities/summer-of-code.html.md
- Added docker-machine
- Fixed typos.
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mykaul
=> Added docker-machine as a GSoC idea

source/develop/release-management/features/virt/headless-vm.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @sgratch
This pull request needs review by: @jelkosz
=> add REST API partial support section for Headless VM

source/develop/developer-guide/engine/engine-development-environment.html.md
Fixes issue https://gerrit.ovirt.org/#/c/61716/
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @gregsheremeta
=> update developer guide with new ovirt-js-dependencies instructions

source/community/user-stories/alter-way-case-study.html.md
-I reformatted the title and removed the subtitle so that it matches the title format of other case studies.
-
-
This pull request needs review by: @bproffitt @mykaul
=> changed alter way title

source/documentation/sla/memory-balloon.html.md
- Fixed formatting.
- Changed some of the descriptions to match the actual code. 
- Fixed image link.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jtokar
This pull request needs review by: @MarSik @doron-fediuck
=> Update memory-balloon design page

source/blog.html.haml
- I changed title of blog page from "oVirt News" to "oVirt Blog"
-
-
This pull request needs review by: @bproffitt @mykaul
=> changed title of blog page

source/community/user-stories/alter-way-case-study.html.md
Fixes issue #837 
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @bessii
This pull request needs review by: @JohnMarksRH @jasonbrooks
=> added a caption, resized alter way user image

source/develop/release-management/features/engine/maximum-memory-size.html.md
clusters -> vms
Hi @bproffitt, please merge this.
=> Fix in maximum-memory-size.html.md

source/release/4.1.1/index.html.md
- Add 4.1.1 Async release notes
=> Add 4.1.1 Async release notes

source/release/4.1.1/index.html.md
- The usual header "Install / Upgrade from previous versions" is missing.
=> missing header for 4.1.1 release notes

source/develop/dev-process/working-with-gerrit.html.md
Changes proposed in this pull request: Add URL to Gerrit and edited the sentence in which the URL is provided.
-
-
-
This pull request needs review by:@mykaul
=> Working with Gerrit added URL

source/community/index.html.md
- Fixed link to community guidelines page.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mykaul
=> Fix broken link to community guidelines

source/blog/2017-04-05-say-hello-to-ovirt-4.1.1.md
- This is a new blog post about the 4.1.1 release
-
-
This pull request needs review by: @mykaul @ykaul
=> Blogpost411

source/blog/2017-04-05-say-hello-to-ovirt-4-1-1.md
Changes proposed in this pull request: I have resubmitted the 4.1.1 blog post, this time with the correct filename format. I have changed the subheadings from "##" - which look the same size as the title - to "###". This time I previewed the post on middleman (. ./run-server.sh). This PR is associated with PR # 894. 
-
-
-
This pull request needs review by: @bproffitt @mykaul
=> new commit for blog post 411

source/develop/infra/testing/spice.html.md
- Updated the spice-guest-tools referenced download link to the latest version.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @HeadlessChild
This pull request needs review by: @garrett
=> Updated spice-guest-tools link to latest

source/blog/2017-04-05-say-hello-to-ovirt-4-1-1.md
Fixes issue #905 
Changes proposed in this pull request: H3 headings changed to H2 headings
- Unresolved issue: The H2 headings appear the same size as the title, so it looks a little odd. Who is responsible for the style sheet? Is it a question of resizing the h2 tags?
-
-
This pull request needs review by:  @duck-rh @garrett @mykaul @bproffitt
=> change subheadings from h3 to h2

source/community/user-stories/users-and-providers.html.md
- 
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @bessii
=> corrected typo on alterway case study link

source/documentation/vmm-guide/chap-Administrative_Tasks.html.md
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @bessii)
=> updated broken links in administrative task doc to accessible urls

source/blog/2017-03-29-up-and-running-with-ovirt-4-1-and-gluster-storage.html.md
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @bessii
This pull request needs review by @jasonbrooks
=> minor typo edit in blog post

source/develop/release-management/features/ovirt-ovn-provider.md
Add Authentication and Authorization to the feature page of
oVirt OVN provider.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @dominikholler
This pull request needs review by: @mmirecki @mkalfon
=> Add Authentication and Authorization to  OVN provider

source/develop/dev-process/working-with-gerrit.html.md
Changes proposed in this pull request: My edits are mainly for clarity and uniformity.  Included in this edit are
- Unifomity in the use of capitalization 
- Edits to improve clarity
- Possible correction of header tag (I might be wrong, it depends on the context..)
- The sections renamed ""The Process in Detail" and "Submitting a Topic Branch to Gerrit" might benefit from additional language edits for clarity. Happy to collaborate with contributor on this.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md):  @jmarks
This pull request needs review by: @mykaul @oourfali @devel@ovirt.org
=> Gerrit page review

source/develop/release-management/features/virt/autoinstall-windows-drivers.md
- Added feature page for automatic installation of Windows virtio drivers
@nyoxi
=> Create feature page for automatic installation of drivers

source/node/index.md
- Modified download links for 3.6 and 4.0 
- Removed broken links for legacy node
@yuvalturg
=> updated ovirt node iso links

source/release/4.1.2/index.html.md
- Added 4.1.2 RC1 release notes
=> 4.1.2 RC1 release notes

source/documentation/index.html.haml
- at http://www.ovirt.org/documentation/ON ovirt > Documentation 
On the the main documentation page, I have updated the links to the release notes, so that they link to the most updated versions.
-
=> updated release note versions

source/node/index.md
Fixes issue #933 #934 
I have pushed the changes again (with one minor addition of a comma).
This pull request needs review by: @yuvalturg @sandrobonazzola @duck-rh
=> pushing ovirt node changes again

source/release/4.1.0/index.html.md, source/release/4.1.1/index.html.md, source/release/4.1.2/index.html.md
Mentioned in:
http://lists.ovirt.org/pipermail/users/2017-May/081802.html
-
-
-
=> Fix notes about EPEL repo in 4.1.* release notes

source/develop/release-management/features/hot-unplug-memory.html.md
=> Note "not implemented" removed

source/release/4.1.2/index.html.md
- Update 4.1.2 release notes with rc2 content
=> Update 4.1.2 release notes with rc2 content

source/release/4.1.1/index.html.md
Fixes issue #923 
Changes proposed in this pull request: 
- Replaced broken links with correct links in 4.1.1 release notes introduction
- Improved the introduction.
- https://www.ovirt.org/release/4.1.1/
This pull request needs review by: @dbec @mykaul
=> re #923 broken links, improved text

source/blog/2016-11-02-ovirt-provider-ovn.md
Signed-off-by: Marcin Mirecki<mmirecki@redhat.com>
-
-
-
=> ovirt-provider-ovn blog: PKI setup

source/documentation/how-to/migrate-pki-to-sha256.html.md
=> Add how-to/migrate-pki-to-sha256.html.md

source/blog/2017-05-16-openshift-openId-integration-with-engine-sso.html.md
- Fixed front matter date so it matches filename and eliminates errors.
=> Corrected frontmatter date

setup.sh
=> Trigger new build: reindent setup.sh slightly

source/documentation/how-to/migrate-pki-to-sha256.html.md
=> how-to/migrate-pki-to-sha256.html.md: Add toc

source/download/index.html.haml
- Update download page pointing to 4.1.2
=> Update download page pointing to 4.1.2

source/release/4.1.2/index.html.md
- Update 4.1.2 release notes with GA content
=> Update 4.1.2 release notes with GA content

source/index.html.haml
- Update home page with 4.1.2 release
=> Update home page with 4.1.2 release

source/documentation/introduction/what-is-ovirt.html.md
Corrected image pathways, one spelling correction, htags corrected.
=> Edits to "What is oVirt?" page

source/release/4.1.3/index.html.md
- Created 4.1.3 Test Candidate release notes
=> Created 4.1.3 Test Candidate release notes

source/develop/developer-guide/vdsm/vdsm-client.html.md
usecure is a typo, it was already marked as deprecated in the code so the documentation needs to be updated as well.
This pull request needs review by: @bronhaim @nirs
=> change unsecure option to insecure

source/blog/2017-05-10-welcome-gsoc-2017-students.md
A minor change to the GSOC blog post title
=> change to GSOC post title

source/develop/archived/proposals/node/kimchiplugin.html.md, source/develop/projects/node/3.1-release-management.html.md, source/redirects.yaml
- Archive kimchiplugin feature
This pull request needs review by: @evol262 @mykaul
=> Archive kimchiplugin feature

source/release/4.1.1/index.html.md
These links were corrected in a previous commit, but the PR was never merged, and in fact, cannot be located.
=> 4.1.1 two broken links in intro

source/community/user-stories/RCC-case-study.html.md
Minor edits to RCC case study requested by FSU marketing department.
The head of RCC had already approved the case study text, and we published it. Today, I received an email with a request for some minor edits.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md):@jmarks
This pull request needs review by:  @bproffitt
=> minor edits to RCC case study

source/develop/developer-guide/vdsm/hook/floppy.html.md
- Markup fix to actually display the XML snippet.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): mz-pdm
=> Fix of markup in floppy.html.md

source/release/4.1.3/index.html.md
- Update 4.1.3 release notes with test compose 2
=> Update 4.1.3 release notes with test compose 2

source/develop/release-management/features/storage/cinder-integration.html.md
Fixed images links in 'Cinder Integration' feature page.
Change-Id: I4de32fefa952ab34a7af37f2e7b3569655529208
Signed-off-by: Daniel Erez <derez@redhat.com>
@danielerez
=> cinder feature page: fixed images links

source/community/user-stories/user-stories.html.md, source/index.html.haml
Fixes issue #1000 
- Removed empty section in users-stories.html.md
- Moved Florida State University to the end of the file in order to be seen in the home page
- Fix comment in index,html about where the user stories are located
This pull request needs review by: @JohnMarksRH @duck-rh
=> Fix user story issue in home page

source/release/4.1.3/index.html.md
- Update 4.1.3 with RC1 content
=> Update 4.1.3 with RC1 content

source/release/4.0.6/index.html.md
Three broken links corrected.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @jmarks 
This pull request needs review by: @sandrobonazzola @mykaul
=> 4.0.6 release notes broken links

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Updated 4.1.3 schedule

source/release/4.1.3/index.html.md
- Updated 4.1.3 release notes with rc2 content
=> Updated 4.1.3 release notes with rc2 content

source/community/index.html.md
https://www.ovirt.org/community/
Changes included:
- Tweaked introductory paragraph to include direct link to users@ovirt.org signup page and the link to the main mailing lists page.
- Placed all social links in one line (with spaces between) in order to save space 
=> Minor changes to community page

source/develop/release-management/features/engine/hostdev-passthrough.html.md
- update hostdev feature page with information regarding virtual GPU assignment
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mpolednik
=> update hostdev feature page to mention virtual GPU assignment

source/documentation/how-to/migrate-pki-to-sha256.html.md
=> how-to/migrate-pki-to-sha256.html.md: Note about 3rd party certs

source/release/4.1.3/index.html.md
- Update 4.1.3 release notes with rc3 conten
=> Update 4.1.3 release notes with rc3 content

source/develop/developer-guide/engine/otopi.html.md
=> developer-guide/engine/otopi: Fix broken link

source/feature/feature-template.html.md
- Minor changes to feature name paragraph as proposed by @bgraveno in PR971 
This pull request needs review by: @dyaniv @bgraveno @mykaul
=> minor changes to feature name paragraph

dashboard_config.yml
=> update dashboard url

source/community/user-stories/users-and-providers.html.md
http://www.ovirt.org/community/user-stories/users-and-providers/
Main changes proposed in this pull request:
- Deleted Wind River from page
- Moved Red Hat from the "Service Providers" to the "Professional Services & integrators" category, and deleted the former.
- Moved "Professional Services & Integrators" above the "Partners in Education" category
- Deleted Yi Yunjie Technology (Beijing) Ltd.
=> Users and Providers Page

source/develop/infra/testing/spice.html.md
- Updated from Ubuntu 12.04 to current LTS releases of Ubuntu, 14.04 and 16.04. 12.04 is EOL and the information is still relevant to the current LTS releases.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @HeadlessChild
This pull request needs review by: @garrett
=> Updated from 12.04 to current LTS releases of Ubuntu

source/documentation/how-to/guest-agent/install-the-spice-guest-agent.html.md
The page in question:
http://www.ovirt.org/documentation/how-to/guest-agent/install-the-spice-guest-agent/
- Corrected broken link
=> Spice Guest Agent Page - Broken Link

source/community/user-stories/users-and-providers.html.md
Changes proposed in this pull request: 
- Added UDS under "professional services and integrators"
This pull request needs review by:  @mykaul
=> further changes to users and providers page

source/community/user-stories/universidad-de-sevilla-case-study.html.md
=> Corrected links and hypertext

source/community/user-stories/universidad-de-sevilla-case-study.html.md
=> small grammatical correction

source/documentation/self-hosted/chap-Backing_up_and_Restoring_an_EL-Based_Self-Hosted_Environment.html.md
=> hosted-engine backup/restore: Fix broken link to Chapter 7

source/develop/release-management/features/storage/reduce-luns-from-sd.html.md
- Add feature page for "Reduce LUNs"
=> Add Reduce LUN feature page

source/develop/release-management/features/network/networkfilterparameters.html.md
- Add information requested in https://bugzilla.redhat.com/show_bug.cgi?id=1366905
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @dominikholler
This pull request needs review by: @mmirecki
=> Add Current Implementation Status of Network Filter Parameters

source/index.html.haml, source/release/4.1.3/index.html.md
=> release: publish 4.1.3

lib/site_helpers.rb
=> Fixed markdown_to_html() matching

source/develop/release-management/features/infra/pki-renew.html.md
=> Add Pki renew page

source/documentation/upgrade-guide/upgrade-guide.md
Connected with Issue #1062 
- Link corrected
This pull request needs review by: @mykaul @karlacio
=> oVirt Upgrade Guide - Corrected links

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Update 4.1.4 schedule

source/release/4.1.4/index.html.md
=> Add 4.1.4 RC2 release notes

source/blog/2017-07-18-ovirt-ansible-roles-an-introduction.html.md, source/blog/2017-07-19-ovirt-ansible-roles-an-introduction, source/blog/2017-07-19-ovirt-ansible-roles-an-introduction.html.md
New blog post on Ansible roles
This pull request needs review by: @mgoldboi
=> Blog post Ansible roles

source/develop/release-management/features/engine/metrics-store.html.md
-  Typos corrected
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @JohnMarksRH
=> oVirt Metrics Store minor corrections

source/develop/release-management/features/engine/metrics-store-installation-guide.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @JohnMarksRH
=> ovirt metrics intstallation guide

source/develop/release-management/features/engine/metrics-store-collected-metrics.html.md
- Capital Letter for Second Word of Subheading
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @JohnMarksRH
=> Capital Letter for Second Word of Subheading

source/develop/release-management/features/engine/metrics-store-installation-guide.html.md
Fixes issue # 
so all metrics store features will have different names
Changed feature name meta tag
-
-
-
=> change feature name meta tag

source/develop/release-management/releases/3.5/feature.html.md
- Added two links to features listed on feature page, and are associated with 3.5.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @JohnMarksRH
This pull request needs review by: @mykaul @oourfali @pkliczewski
=> links to two features under 3.5 releases

source/develop/release-management/features/index.html.md
- Add links to features 4.0,4.1
- Change 3.6 link text from "proposed feature" > "feature"
- Update introductory text above links
- Change heading text
=> Add links to recent releases and update intro text

source/develop/release-management/features/index.html.md
- Create ovirt 3.7 features page
=> add links to recent releases and update text

source/develop/release-management/releases/4.0/feature.html.md
-  Created oVirt 4.0 features page
- Added links to three features
=> oVirt 4.0 feature spage

source/develop/release-management/releases/3.6/feature.html.md
- Updated oVirt 3.6 features page with links to 11 features
=> oVirt 3.6 features

source/index.html.haml, source/release/4.1.4/index.html.md
=> release: publish 4.1.4

source/documentation/index.html.haml, source/release/4.1.3/index.html.md
Signed-off-by: John Marks <jmarks@redhat.com>
Added link to 4.1.4 release notes on documentation page
This pull request needs review by: @sandrobonazzola @mykaul
=> Add 4.1.4 RN link to Documentation

source/develop/release-management/releases/3.1/feature.html.md
- List of features for 3.1
This pull request needs review by:@mykaul
=> 3.1 feature list

source/develop/release-management/features/engine/metrics-store-installation-guide.html.md
=> Corrected typo

source/community/about/community-activity.html.md
- Deleted first link as it is out of date
- I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @jmarks
This pull request needs review by: @duck-rh @mureinik @mykaul
=> First link deleted as it is out of date

source/develop/release-management/releases/3.3/feature.html.md
=> 3.3 features page

source/develop/release-management/releases/3.4/feature.html.md
=> 3.4 features Page Update

source/develop/release-management/releases/3.6/proposed-feature.html.md
- This file is not being used and is replaced by:
/home/jmarks/ovirt-site/source/develop/release-management/releases/3.6/feature.html.md
=> Remove 3.6 proposed feature file

source/develop/release-management/features/metrics/metrics-store-collected-metrics.html.md, source/develop/release-management/features/metrics/metrics-store-installation.html.md, source/develop/release-management/features/metrics/metrics-store.html.md
- Under Features, create "Metrics" folder
- Under "Metrics" folder, add 3 metrics features
=> Metrics Folder and Associated Features Added

source/develop/release-management/releases/3.2/feature.html.md
=> 3.2 features page

source/develop/release-management/features/metrics/metrics-store.html.md
- Corrected links to installation guide and collected data features
=> Corrected Links in Feature

source/community/user-stories/users-and-providers.html.md
Add Bobcares.com to User and Providers Page
This pull request needs review by: @
=> Add Bobcares to Users and Providers Page

source/release/4.1.5/index.html.md
=> Create index.html.md for oVirt 4.1.5 release

.travis.yml
- Fix the CI
I can't sign, the link to contributing is wrong. So there is no way I can't accept it.
=> Workaround travis breakage

source/develop/index.html.md
- Link to features page from Develop page - makes it easier to find the features.
=> Link to features on Develop pages

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Add 4.1.5 schedule

source/release/4.1.5/index.html.md
- Update release notes with 4.1.5 rc3 content
=> Update release notes with 4.1.5 rc3 content

.github/PULL_REQUEST_TEMPLATE.md
=> Update contribution guidelines link

source/develop/release-management/releases/4.0/feature.html.md
=> Links under 4.0 features

source/develop/release-management/releases/3.4/feature.html.md
- 1 3.4 link corrrected
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md) @jmarks
=> Correction of one 3.4 link

source/develop/release-management/releases/3.3/feature.html.md
=> 3.3 features links

source/develop/release-management/releases/3.1/feature.html.md
- two links to 3.1 features corrected
=> 2 links to 3.1 features corrected

source/documentation/install-guide/chap-Installing_oVirt.html.md
Added required repositories to install ovirt engine install guide. Without these repositories the instalation guide will not work.
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @petrkotas yourself to sign)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ovirt/ovirt-site/1112)
=> Added official repositories to install guide.

README.md
This pull request needs review by: @mykaul @thatdocslady
=> fix internal link in README

source/documentation/vmm-guide/chap-Administrative_Tasks.html.md
This pull request needs review by: @michalskrivanek @ahadas @bessii @bproffitt
=> document verification steps for seting up Xen imports

source/develop/release-management/features/virt/hostusb.html.md
Fixes issue:
http://lists.ovirt.org/pipermail/users/2017-August/083760.html
-
=> Remove the hook

source/index.html.haml
=> Released 4.1.5

source/download/index.html.haml
- Updated download page pointing to 4.1.5 release notes
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): sandrobonazzola
=> Download: point to 4.1.5 release notes

source/documentation/index.html.haml
- Moving latest release to 4.1.5
=> Moving to 4.1.5

source/develop/release-management/features/storage/glusterfs-storage-domain.html.md
- Updated a GlusterFS domain feature page.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @akashihi
=> Updated GlustreFS domain feature page.

source/develop/release-management/releases/4.1.z/release-management.html.md
=> Add 4.1.6 schedule

source/develop/dev-process/working-with-gerrit.html.md
Hi @jelkosz, could you please give it a like?
=> Working with gerrit: hooks need x permission

source/blog/2017-08-16-ovirt-ansible-roles-how-to-use.html.md
=> Add new blog post - how to use ansible roles

source/develop/release-management/features/sla/engine-high-availability.html.md, source/develop/release-management/features/sla/hosted-engine-add-hosts-with-web-ui.html.md, source/develop/release-management/features/sla/hosted-engine-configuration-on-shared-storage.html.md, source/develop/release-management/features/sla/hosted-engine-improve-management-in-host-dialogs.html.md, source/develop/release-management/features/sla/hosted-engine-indicate-host-in-web-ui.html.md, source/develop/release-management/features/sla/hosted-engine-indicators-ui.html.md, source/develop/release-management/features/sla/hosted-engine-migration-to-4-0.md, source/develop/release-management/features/sla/hosted-engine-vm-management.html.md, source/develop/release-management/features/sla/hosted-engine.html.md, source/develop/release-management/features/sla/memory-aware-even-distribution-policy.html.md, source/develop/release-management/features/sla/quota-3.2.html.md, source/develop/release-management/features/sla/self-hosted-engine-fc-support.html.md, source/develop/release-management/features/sla/self-hosted-engine-gluster-support.html.md, source/develop/release-management/features/sla/self-hosted-engine-hyper-converged-gluster-support.html.md, source/develop/release-management/features/sla/self-hosted-engine-iscsi-support.html.md, source/develop/release-management/features/sla/self-hosted-engine-maintenance-flows.html.md, source/develop/release-management/features/sla/self-hosted-engine.html.md, source/develop/release-management/features/sla/sla-for-storage-io-bandwidth.html.md
-Move features from "unclassified" "engine" and "ux" into "SLA
- Note: some of these features can also be found under the associated release version link. These links will need to be updated before merging.
=> move various features to SLA category

source/develop/release-management/releases/4.0/feature.html.md
- 3 features added to 4.0 features page
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@jmarks
=> 3 new features to 4.0

source/develop/release-management/releases/3.3/feature.html.md
=> one corrected link

source/develop/release-management/features/network/lldp.html.md
Update the REST-API URL for LLDP from a discussed URL to the
finally implemented one.
Signed-off-by: Dominik Holler <dholler@redhat.com>
This pull request needs review by: @mmirecki
=> Fix REST-API URL for LLDP

source/blog/2017-09-02-ovs-dpdk.html.md
This PR replaces PR #1191 #1070 
This pull request needs review by: @igoihman @dankenigsberg
=> OVS-DPDK blog post

source/develop/release-management/features/sla/stateless-broker.html.md
- Added 'stateless broker' feature page
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @akashihi
=> Added 'Stateless HE broker' feature page.

source/javascripts/application.js, source/layouts/feature.html.haml, source/stylesheets/_application-custom.css.sass, source/stylesheets/_bootstrap-custom.sass, source/stylesheets/application.css.sass
Changing to a better font.
Adding Expand/Collapse Feature menu
Adding Expand/Collapse for each feature Category
All menus are working will local storage to recall last state
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @eldan 
=> UX improvment in features

source/layouts/feature.html.haml, source/stylesheets/_application-custom.css.sass
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @eldan
=> Remove: "at a glance" section and merge the feature metadata in the page

source/develop/release-management/releases/3.2/feature.html.md
=> Corrected link to quota 3.2

source/blog/2017-09-02-ovs-dpdk.html.md
fixed the post appearance.
This pull request needs review by: @dankenigsberg @JohnMarksRH
=> fix ovs-dpdk post

source/develop/release-management/features/sla/hosted-engine-agent-offloading.html.md
- Added 'Hosted Engine Agent Offloading' feature page
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@dchaplyg)
This pull request needs review by: (@doron-fediuck @MarSik @jtokar @akrejcir @yanirq @pcbailey )
=> Added 'Hosted engine agent offloading feature'

source/documentation/index.html.haml
- Update Documentation page with 4.1.6
=> Update Documentation page with 4.1.6

source/download/index.html.haml
- Update Download page with 4.1.6
- Update CentOS requirements to 7.4
=> Update Download page with 4.1.6

source/release/4.1.6/index.html.md
-  Update oVirt 4.1.6 release notes
=> Update oVirt 4.1.6 release notes

source/release/4.1.6/index.html.md
-links corrected, a few minor punctuation corrections
-
-
This pull request needs review by: @sandrobonazzola @mykaul
=> links corrected, a few minor punctuation corrections

source/release/4.1.7/index.html.md
=> Adding 4.1.7 rc1 release notes

source/blog/2017-09-21-starting-vm.html.md
- Fix link to image in blog
This pull request needs review by: @petrkotas
=> Fix image link in blog

source/release/4.2.0/index.html.md
- 4.2.0 alpha release notes
This pull request needs review by: @JohnMarksRH @mykaul
=> 4.2.0 alpha release notes

source/blog/2017-09-19-introducing-ovirt-4.2.0.html.md
- New blog post, highlighting main features of 4.2.0.
- Four images included. Best resolution possible
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):@jmarks
=> Blog post on 4.2.0

source/release/4.1.7/index.html.md
=> Update index.html.md w/ 4.1.7 rc2 release notes

source/develop/release-management/features/metrics/metrics-store-installation.html.md
- Fix the links to ViaQ README
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):@rollandf
=> Fix ViaQ link to README

source/blog/2017-10-02-introducing-high-performance-vms.md
- New blog post on high performance vms
-
-
=> high performance VMs blog post

source/blog/2017-10-02-introducing-high-performance-vms.md
- Tweaks and image
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @jmarks)
=> Tweaks and image

source/develop/release-management/features/infra/aaa_faq.html.md
This PR add new question for AAA FAQ:
```
Is it possible to use modify search filter for users?
```
=> Add new question to AAA FAQ

source/documentation/quickstart/quickstart-guide.html.md
- Update quickstart-guide.html.md for 4.1.7
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sandroboanzzola
=> Update quickstart-guide.html.md for 4.1.7

source/download/index.html.haml
The issue has been reported here:
https://bugzilla.redhat.com/show_bug.cgi?id=1497305
This pull request needs review by: (please @sandrobonazzola  the reviewer if relevant)
=> Added explicit note that a version can not be skipped

source/develop/release-management/features/sla/hosted-engine-new-deployment.html.md
- Provide overview of the new deployment process 
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jtokar
This pull request needs review by: @doron-fediuck @MarSik @mykaul
=> New hosted engine deployment process overview

source/index.html.haml
- Added a link to the 4.2.0 blog post ("and much more")
-
=> Add link to banner text

source/index.html.haml
=> correct link to local version

source/release/4.1.7/index.html.md
=> Update release notes for oVirt 4.1.7 rc4

source/community/user-stories/users-and-providers.html.md
- Fix non-existing link in providers page
-
-
=> Fix link in providers page

source/develop/dev-process/build-and-test-standards.html.md, source/develop/index.html.md
Also added a link to that page from the main 'develop' page, so new
developers may actually find it.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @ifireball
This pull request needs review by: @Jmarks @eedri
=> Updated page about teh build and test standards

source/blog/2017-10-19-come-to-fosdem-event.md
=>  A few tweaks to post

source/blog/2017-01-03-ovirt-system-tests-to-the-rescue.html.md
- Fix broken links 
This pull request needs review by: @eedri
=> Fix links in ovirt-system-tests-to-the-rescue blog post

source/index.html.haml
- Edited the bullet points - main 4.2.0 features
-
=> 4.2.0 banner on home page

source/develop/release-management/features/storage/backup-restore-disk-snapshots.html.md
Added 'Backup-Restore Disk-Snapshots' feature page.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @danielerez
This pull request needs review by: 
@rollandf
=> features: Backup-Restore Disk-Snapshots

source/index.html.haml
-tweaked bullet about high performance computing
=> Home page 4.2.0 top features

source/develop/release-management/features/virt/high-performance-vm.html.md
Update the High Performance VM feature page.
This pull request needs review by: @jelkosz @michalskrivanek
=> Update High Performance VM feature page

source/develop/release-management/features/storage/multipath-events.html.md
- Feature page for Multipath events
This pull request needs review by: @nirs @mureinik
=> Add Multipath events feature

source/release/4.1.7/index.html.md
=> Update index.html.md for 4.1.7 rc6

source/blog/2017-11-02-introducing-ovirt-4.2.0-beta.html.md
=> 4.2.0 beta blog

source/blog/2017-10-02-introducing-high-performance-vms.md
- Added a couple of sentences about the pop-up listing additional recommended manual configurations
This pull request needs review by: (please @sgratch @mykaul
=> High Performance VM - Pop-up 

source/documentation/how-to/networking/changing-engine-hostname.html.md
=> changing-engine-hostname.html.md: Mention SSO_ALTERNATE_ENGINE_FQDNS

source/develop/release-management/features/metrics/metrics-store-installation.html.md
- Corrected hyperlink to data collection flow image
=> Corrected hyperlink to data collection flow image

source/index.html.haml
This pull request needs review by: @sgratch
=> High Performance VM Tweak

source/develop/developer-guide/engine/migrate-to-hosted-engine.html.md
- Hyperlink at the end of the page only works when user completes guidelines on the page. Therefore, I turned it to a URL in bold type.
=> Convert hyperlink to URL

source/index.html.haml
=> small corrections

source/develop/release-management/features/network/lldp.html.md
Add two new supported TLVs to feature page.
This reflects https://gerrit.ovirt.org/#/c/83769/
This pull request needs review by: @mmirecki  @dankenigsberg @EdDev
=> Update feature page for LLDP

source/release/4.2.0/index.html.md
- Update 4.2.0 release notes with beta2 content
=> Update 4.2.0 release notes with beta2 content

source/layouts/feature.html.haml, source/stylesheets/_application-custom.css.sass
Arranging search and list features - mostly CSS
Removing Unclassified category
@JohnMarksRH  please review
I confirm that this pull request was submitted according to the [contribution guidelines]
This pull request needs review by: (please @eldan the reviewer if relevant)
=> Remove Unclassified category from feature list

source/develop/release-management/features/index.html.md
=> 4.2 features page and link

source/blog/2017-10-02-introducing-high-performance-vms.md
- Change of three main featured listed in blog post
This pull request needs review by: @mykaul @sgratch
=> High Performance VMs Blog Post _ Features

source/documentation/how-to/hosted-engine.html.md
-Hosted Engine Howto: Corrected links, minor edits
- One link is still broken- Hosted Engine Console. I could not find such a page on the ovirt site.
-
=> Hosted Engine Howto: Corrected links, minor edits

source/download/index.html.haml
- Point to 4.1.7 release notes
=> Update download page pointing to 4.1.7

source/documentation/index.html.haml
- Current release is 4.1.7
- Moved 4.1.6 to previous releases
=> Update documentation pointing to 4.1.7

source/develop/release-management/features/infra/advancedforemanintegration.html.md
-Delete this feature - page is empty
-
-
=> Delete this feature - page is empty

source/develop/release-management/releases/4.0/feature.html.md
- Features associated with ovirt 4.0 added
-
-
=> Features associated with ovirt 4.0 added

source/develop/release-management/releases/4.2/feature.html.md
=> Links to 5 - 4.2 features

source/develop/release-management/releases/3.5/feature.html.md
-added 4 more features under 3.5 features
-
-
=> added 4 more features under 3.5 features

source/blog/2017-11-22-webadmin-lldp.html.md
- Change date to 22.11.2017
-
-
=> Change date of post

source/documentation/admin-guide/chap-Clusters.html.md
new CPUs added Admin-Guide > Clusters chapter
based on: https://bugzilla.redhat.com/show_bug.cgi?id=1487155
This pull request needs review by: @apinnick  @michalskrivanek
=> new CPUs added Admin-Guide > Clusters chapter

source/blog/2017-11-22-webadmin-lldp.html.md
=> LLDP blog minor edit

source/develop/release-management/features/index.html.md, source/develop/release-management/releases/3.0/feature.html.md
- new 3.0 link on main feature page and new 3.0 feature
-
-
=> new 3.0 link on main feature page and new 3.0 feature

source/develop/developer-guide/engine/engine-setup.html.md
Add content about env and how to use it
-
-
-
=> Update Engine Setup

source/develop/developer-guide/engine/engine-development-environment.html.md
small fixes to developer guide
- fix formatting bugs
- remove references to old user portal
- add references and links to super dev mode for GWT debugging
=> small fixes to developer guide

source/release/4.1.8/index.html.md
=> Updated for 4.1.8 RC2

source/develop/release-management/features/metrics/metrics-store-installation.html.md, source/develop/release-management/features/network/mangeiqOvn, source/develop/release-management/features/network/unrestricted-network-names.html.md, source/develop/release-management/features/sla/cluster-optimization-host-change-notification.html.md, source/develop/release-management/features/sla/cockpit-he-wizard-ui-update.html.md, source/develop/release-management/features/virt/KvmToOvirt.html.md
Fixes issue #1175 
- Remove old wiki headers
This pull request needs review by: @duck-rh @JohnMarksRH
=> Remove old Wiki headers

source/release/4.1.8/index.html.md
=> Update for oVirt 4.1.8 RC3

source/documentation/quickstart/quickstart-guide.html.md
- Correction of broken links in quick start guide
- Some images are also broken due to use of jpg instead of PNG. To be fixed shortly
-
=> Documentation > Quick Start Guide > Broken Links

source/documentation/introduction/about-ovirt.html.md
- Broken link on about ovirt page
-
-
=> Corrected broken link

source/release/4.1.8/index.html.md
=> Update for 4.1.8 RC4

source/release/4.2.0/index.html.md
- Update 4.2.0 release notes with RC content
=> Update 4.2.0 release notes

source/release/4.2.0/index.html.md
=> 4.2 release notes: Clarify Fedora status

source/develop/release-management/features/storage/multipath-events.html.md
- Some updates in the multipath events feature page
=> Update multipath events feature page

source/release/4.2.0/index.html.md
=> 4.2.0 release notes: Add ovirt-wgt

source/release/4.1.8/index.html.md
=> Update 4.1.8 release notes

source/index.html.haml
- Update home page with oVirt 4.1.8 release
=> Update home page with oVirt 4.1.8 release

source/download/index.html.haml
- Update download page with 4.1.8 references
=> Update download page with 4.1.8 references

source/documentation/index.html.haml
- Updates links to release notes
=> Update links to release notes

source/release/4.2.0/index.html.md
Changes proposed in this pull request: list of features for 4.2.0 GA
-
-
-
This pull request needs review by: (please @sandrobonazzola @mykaul
=> 4.2.0 GA RN Features 

source/develop/release-management/releases/4.2/release-management.html.md
=> Update 4.2 schedule

source/blog/2017-09-19-introducing-ovirt-4.2.0.html.md
- Updated OVN description in 4.2.0 Alpha post, kindly provided by Dan.
-
-
This pull request needs review by: (please @dankenigsberg
=> Updated OVN description in 4.2.0 Alpha post

config.rb
=> Workaround for HAML 5 warnings until MM is ready

source/release/4.2.0/index.html.md
- Update 4.2.0 release notes with rc3 content
=> Update 4.2.0 release notes with rc3 content

Gemfile, Gemfile.lock
I compared building with and without and it is identical.
=> wikicloth is not needed

source/release/4.2.0/index.html.md
- I have updated the feature descriptions and added some links.
-
-
=> Updated feature descriptions

source/documentation/install-guide/chap-Enterprise_Linux_Hosts.html.md
Without repository configuration my installation fails to add a new host.
- Added to "Chapter 7: Enterprise Linux Hosts" command to setup repository
@karlacio
=> Missing project repository configuration?

source/blog/2017-12-17-ovirt-4.2.0-now-ga.html.md, source/blog/2017-12-20-ovirt-4.2.0-now-ga.html.md
- Further changes required. Not ready for publication.
-
-
=> blog post for 4.2.0 ga

source/documentation/quickstart/quickstart-guide.html.md
- Update quickstart-guide.html.md for 4.2
=> Update quickstart-guide.html.md for 4.2

source/index.html.haml
- Fix home page link to GA release
Thanks to @eedri for having reported it promptly
=> Fix home page link to GA release

source/blog/2017-12-17-ovirt-4.2.0-now-ga.html.md
Changes proposed in this pull request: change one heading from 4.2.0 > 4.2
-
-
-
=> Blogpost 4.2.0 ga

source/develop/release-management/features/virt/virt-sparsify.html.md
=> minor edits

source/blog/2017-12-18-ovirt-metrics-store.html.md
- oVirt Metrics Store blog post.
- Outstanding issues: links to deep dive and blue jeans session
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @jmarks
This pull request needs review by: @sradco @mykaul
=> oVirt Metrics Store

source/documentation/install-guide/chap-System_Requirements.html.md
- Update Supported Hypervisor CPU Models
=> Update Supported Hypervisor CPU Models

source/develop/release-management/features/storage/backup-restore-disk-snapshots.html.md
Backup-Restore Disk-Snapshots:
* Added detailed description to "Download Disks" section.
* Added examples for download/upload disk.
@rollandf
=> feature: added details and examples to backup-restore

source/layouts/feature.html.haml
Fixes issue #520
This pull request needs review by: @mureinik @sandrobonazzola
=> indexes do not need feature info

source/blog/2017-12-08-host-deploy-customization.html.md
=> Add blog post about customization of host-deploy

source/documentation/install-guide/chap-System_Requirements.html.md, source/download/index.html.haml
- change the wording in the download site
- changed the browser requirements to be consistent with the one in update site
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jelkosz
This pull request needs review by: @sandrobonazzola @gregsheremeta
=> Update browser requirements.

source/node/index.md
- Added 4.2 to the docs
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @donnydavis
=> Updating for oVirt 4.2

data/datavideo.yml
=> Added metrics video to Documentation page.

source/node/index.md
- fixed a typo
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sinuswave
=> fixed copy paste typo

source/develop/release-management/features/sla/hosted-engine-agent-offloading.html.md, source/develop/release-management/features/sla/hosted-engine-ovf-extraction.md
- HE refactoring feature update
- Moved OVF and other shared configuration handling to the separate feature.
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @akashihi
This pull request needs review by: (@MarSik @doron-fediuck )
=> Feature he agent offloading

source/develop/release-management/features/sla/stateless-broker.html.md
- Feature status updated.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dchaplyg
This pull request needs review by: @MarSik @doron-fediuck
=> 'Stateless HE broker' feature page updated.

source/download/ovirt-live.html.md
- add depreciation notice
This is to reduce confusion (as I experienced) between oVirt live and oVirt node and to make people aware that oVirt live is no longer maintained.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sammcj
=> add depreciation notice to ovirt-live

source/node/faq.md
- Fixes the styling for the code block
@sandrobonazzola @evol262 @dougsland
=> Fixed styling in node upgrade faq

source/community/activities/summer-of-code-students.html.md, source/community/activities/summer-of-code.html.md
Updated the gsoc sites to the new 2018 round
- changed the administrators
- removed old projects / added a template
- fixed a link to mentors
- updated dates
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @jelkosz)
=> updated google summer of code pages to 2018 year

source/develop/release-management/features/virt/virt-sparsify.html.md
- @smelamud This PR replaces #772 - which could not be merged.
- The content is copied from the #772 PR.
-
This pull request needs review by: (please @smelamud
=> New version of the virt-sparsify feature page

source/blog/2018-01-18-ovirt-admin-bookmarks.md
- Added a blog post about the new webadmin UI bookmarking capability.
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @mention yourself to sign) @awels
=> - Added webadmin UI bookmark blog post.

source/community/activities/summer-of-code.html.md
add Google Summer of Code 2018 section, and a couple ideas
This pull request needs review by: @jelkosz @mykaul @sandrobonazzola
=> add Google Summer of Code 2018 section, and a couple ideas

source/documentation/how-to/guest-agent/install-the-guest-agent-in-ubuntu.html.md
evilissimo no longer provides packages for Ubuntu 12.04. Add manual build instructions.
- Update ovirt-guest-agent instructions for Ubuntu 12.04
=> Update instructions for GA on Ubuntu 12.04

source/index.html.haml
=> Update home page

source/release/4.2.1/index.html.md
=>  Update release note for 4.2.1 with BZ#1543988 as a know issue

source/develop/dev-process/install-nightly-snapshot.html.md
=> Update 4.1 branch to 4.2 branch repos

source/documentation/how-to/troubleshooting/troubleshooting-nfs-storage-issues.html.md
Remove a comma that was annoying me.
-
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @eggsome
=> Remove erroneous comma

source/documentation/how-to/hosted-engine.html.md
=> Add instructions for HE setup via cockpit

source/develop/release-management/features/network/provider-physical-network.md
Make the feature page more clear.
=> content: fix feature page for provider physical network

source/documentation/gluster-hyperconverged/Gluster_Hyperconverged_Guide.html.md, source/documentation/gluster-hyperconverged/chap-Introduction.html.md, source/documentation/gluster-hyperconverged/chap-Maintenance_and_Upgrading_Resources.html.md, source/documentation/gluster-hyperconverged/chap-Single_node_hyperconverged.html.md
Signed-off-by: Sahina Bose <sabose@redhat.com>
-
-
-
=> Added single node HC deployment guide

source/documentation/resources/index.html.md
Signed-off-by: Marcin Mirecki <mmirecki@redhat.com>
-
-
-
=> Fix broken link in documents/resources

source/community/activities/summer-of-code.html.md
oVirt was not accepted for GSoC 2018. Removed ideas and added a note.
This pull request needs review by: @jelkosz @mykaul @sandrobonazzola
=> oVirt was not accepted for GSoC 2018. Removed ideas and added a note.

source/documentation/how-to/hosted-engine.html.md
=> Change instructions to be more accurate

source/blog/2018-02-20-Your-Container-Volumes-Served-By-oVirt.md
Signed-off-by: Roy Golan <rgolan@redhat.com>
- updated the date format of the blog post, this might cause a rendering issue on prod
@rollandf
=> Fix a blog post date header problem

source/develop/release-management/features/storage/backup-restore-api-integration.html.md
- Remove unnecessary tags
- Fix reference numbering 
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):@rollandf
This pull request needs review by: @idanshaby
=> Fix Backup-Restore page

source/develop/developer-guide/vdsm/vdsm-client.html.md
This pull request needs review by: @dankenigsberg @nirs
=> fix examples in vdsm-client documentation

source/develop/release-management/features/network/import-vm-net-changes-2.html.md
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
- new feature description for network changes in import vm
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): eraviv@redhat.com
This pull request needs review by: mlipchuk@redhat.com, mburman@redhat.com
=> Add new import-vm-net-changes-2.html.md doc

source/develop/release-management/features/metrics/metrics-store-installation.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco
=> Add prerequisites for installing OpenShift Logging

source/blog/2018-02-20-your-container-volumes-served-by-ovirt.html.md
Fixed date
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @grafuls
This pull request needs review by: @rgolangh
=> Fixed date on blog post for ref-arch ocp on rhv

source/index.html.haml
- Update home page with 4.2.2 GA
=> Update home page with 4.2.2 GA

source/download/index.html.haml
- Update download page with 4.2.2 GA
=> Update download page with 4.2.2 GA

source/documentation/index.html.haml
- Update documentation page with 4.2.2 GA
=> Update documentation page with 4.2.2 GA

data/authors.yml, source/develop/release-management/features/network/provider-physical-network.md
The approach to get the provider physical network on
importing an external network.
-
-
-
This pull request needs review by: @phoracek  @mmirecki  @dankenigsberg
=> content: Import of a provider physical network

CONTRIBUTING.md, README.md
-
-
-
This pull request needs review by: @thatdocslady @sandrobonazzola @mmirecki
=> Instruction how to add a new author

source/develop/release-management/features/ux/uiplugins43.html.md
- Update UI plugin documentation for 4.2 and below.
- Added UI plugin documentation for 4.3 and beyond.
- Update outdated documentation
- Add new documenation for new version
-
=> oVirt Site: Update UI plugin documention

source/develop/release-management/features/storage/vm-leases-and-snapshots-behavior.html.md
-
Add VM leases and VM snapshots integration page
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @eshenitzky
This pull request needs review by: @rollandf
=> Add VM leases and VM snapshots integration page

source/develop/release-management/features/metrics/centos7-viaq.repo
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sradco
This pull request needs review by: @mykaul @rollandf @richm
=> Update Viaq installation instructions for OpenShift logging 3.9

source/documentation/gluster-hyperconverged/chap-Single_node_hyperconverged.html.md
Signed-off-by: Sahina Bose <sabose@redhat.com>
Fixes issue bz#1552559
Changes proposed in this pull request: Fixes some issues in the gdeploy config file
-
-
-
=> Single node HC guide - edits to gdeploy config file

source/documentation/ovirt-orb/index.html.md
- Some punctuations and typo fixes
- Move commands to blocks
This pull request needs review by: @lveyde 
=> Some fixes in Orb page

source/release/4.2.3/index.html.md
- Update 4.2.3 release notes with RC2 content
=> Update 4.2.3 release notes with RC2 content

source/develop/developer-guide/vdsm/log-files.html.md
Add short introduction, with reference to the full docs,
about how to configure the Vdsm logging at runtime.
Signed-off-by: Francesco Romani fromani@redhat.com
=> develop: log: document the runtime logging

source/documentation/self-hosted/chap-Backing_up_and_Restoring_an_EL-Based_Self-Hosted_Environment.html.md
=> Restore procedure done using the vintage flow

source/develop/release-management/releases/4.2.z/release-management.html.md
=> Update 4.2.3 schedule

source/documentation/ovirt-orb/index.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dankenigsberg
This pull request needs review by: @lveyde or @sandrobonazzola 
Note that having read this doc, I still don't quite understand what orb does. I'll need to try out first.
=> ovirt-orb: indent requirements properly

source/develop/developer-guide/engine/engine-setup.html.md
=> engine-setup: Add "Secret Knobs" subsection

source/documentation/ovirt-orb/index.html.md
The former version had too many headers relative to the content within. My version condenses the content and makes using it more straightforward.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dankeningsberg
I would like to add a paragraph on how orb is built. @lveyde, where is the code that creates the tarball?
This pull request needs review by: @sandrobonazzola @lveyde
=> rework ovirt-orb

source/documentation/ovirt-orb/index.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dankenigsberg
This pull request needs review by: @sandrobonazzola @lveyde
=> ovirt-orb: minor markdown fixes

source/develop/release-management/features/sla/mom-declarative-language.html.md
- Add a feature page describing the design of a new policy language for MOM.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @akrejcir
This pull request needs review by: @MarSik @doron-fediuck @aglitke
=> Add feature page: New policy language for MOM

source/release/4.2.3/index.html.md
- Update 4.2.3 release notes with async content
=> Update 4.2.3 release notes with async content

source/release/4.2.4/index.html.md
- Added 4.2.4 RC1 release notes
=> Added 4.2.4 RC1 release notes

source/documentation/ovirt-orb/index.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @dankenigsberg
This pull request needs review by: @sandrobonazzola @lveyde
=> mention where `ovirt-orb` comes from

source/author.html.haml
=> sort blog posts on author page

source/community/about/mailing-lists.html.md
- Fix links to mailing lists
- Remove old lists
=> Fix mailing lists links

source/node/index.md
- Update Node page fixing references to 4.1 ISO
=> Update Node page

source/develop/release-management/features/storage/incremental-backup.html.md
Added a feature page for 'Incremental Backup'.
-
-
-
@nirs 
@rollandf 
@tnisan
=> feature: incremental backup

source/index.html.haml
- Update home page with 4.2.4 release
=> Update home page with 4.2.4 release

source/download/index.html.haml
- Update download page with 4.2.4
=> Update download page with 4.2.4

source/documentation/index.html.haml
- Update documentation page with 4.2.4
=> Update documentation page with 4.2.4

source/release/4.2.5/index.html.md
- Add 4.2.5 release candidate notes
=> Add 4.2.5 release candidate notes

source/develop/release-management/releases/4.2.z/release-management.html.md
=> Update 4.2.5 Schedule

source/develop/developer-guide/engine/otopi.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @didib
=> developer-guide/engine/otopi: Add Logs

source/develop/release-management/features/network/managed_mtu_for_vm_networks.html.md
This pull request needs review by: @dankenigsberg @mmirecki @mburman5 
Even if the headings for the flows are not visible on github, they will be visible on ovirt-site.
=> Add new flow to feature page for managed MTU

source/index.html.haml
=> clean up index page

source/develop/release-management/features/storage/image-upload.html.md
* Added a link to documentation site on github pages.
* Updated feature status and authors.
-
-
-
=> imageio: added a link to documentation

source/documentation/index.html.haml
- Update documentation page with 4.2.5
=> Update documentation page with 4.2.5

source/download/index.html.haml
- Update download page with 4.2.5
=> Update download page with 4.2.5

source/index.html.haml
- Update home page with 4.2.5 GA
=> Update home page with 4.2.5 GA

source/blog/2018-07-29-ovn-dpdk.html.md
- add READMORE link for 'Upgraded DPDK support in oVirt' blog
=> add READMORE link for 'Upgraded DPDK support in oVirt' blog

data/authors.yml, source/documentation/how-to/reports/dwh-development-environment.html.md
- added needed java libraries to the setup instructions
- fixed links
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sjd78
=> Updated the DWH dev environment build page

source/develop/release-management/releases/4.2.z/release-management.html.md
=> Add 4.2.6 schedule

source/release/4.2.6/index.html.md
- Add 4.2.6 release notes for RC1
=> Add 4.2.6 release notes for RC1

source/layouts/_nav.haml
=> fix logo for mobile display

source/develop/infra/infrastructure.html.md
- Fixed spelling errors in the document at 2 places
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sankarshanmukhopadhyay
=> minor spelling corrections

source/blog/2018-08-02-Skydive-With-oVirt.html.md
- fix number formatting in skydive blog
Before:
After:
=> fix number formatting in skydive blog

source/blog/2018-08-03-sso-keycloak-ovirt-saml-389ds.html.md
- English and formatting fixes for keycloak blog
=> English and formatting fixes for keycloak blog

source/release/4.2.5/index.html.md
- Update 4.2.5 with async content
=> Update 4.2.5 with async content

source/release/4.2.6/index.html.md
- Update 4.2.6 release notes with RC2 content
=> Update 4.2.6 release notes with RC2 content

source/develop/release-management/releases/4.2.z/release-management.html.md
=> Update 4.2.6 schedule

source/layouts/_production_only.haml, source/layouts/basic.html.haml
=> remove obsolete RH tracking

source/release/4.2.6/index.html.md
- Update 4.2.6 release notes with RC3 content
=> Update 4.2.6 release notes with RC3 content

source/release/4.2.6/index.html.md
- Update 4.2.6 release notes with GA content
=> Update 4.2.6 release notes with GA content

source/index.html.haml
=> Update home with 4.2.6

source/download/index.html.haml
- Update download page with 4.2.6
=> Update download page with 4.2.6

source/release/4.2.6/index.html.md
- Update 4.2.6 release notes after initial community feedback received.
=> Update 4.2.6 release notes

source/release/4.2.6/index.html.md
- Added known issue reported by Giulio Casella on users mailing list
=> Update 4.2.6 with known issue about IP over IB

source/release/4.2.6/index.html.md
- Update 4.2.6 release notes with async content
=> Update 4.2.6 release notes with async content
