oVirt/ovirt-site

source/community/about/community-guidelines.html.md
As Markdown supports some embedded HTML, I've added a form that kicks a query over to Google as previously only suggested in plaintext.
I dug around and figured out how to append the limiting text to a provided search string during a Google query so that one could simply type a simple string to search. In addition, I have this appended instead of prepended so that the search is always visible within Google as well.
=> search lists & bugzilla from suggestions page

source/search.html.haml
This commit changes %20 and the like into their proper characters. Fixes #8.
=> enforce URI decoding on the hash (fixes cases where %20 might show up)

config.rb, source/develop/release-management/features/index.html.md, source/layouts/feature.html.haml
This should fix #5, as the layout wasn't used for feature pages when things were shuffled around. Now it is.
=> fixed feature page layouts

source/search-results.json.haml
Adds URL fragments and MediaWiki-based titles to search index.
Fixes #35.
=> URL (and MediaWiki titles) as search keywords

source/search-results.json.haml
Not needed anymore. I meant to remove this before merging the branch. Fixed.
=> removed MediaWiki title search debugging

setup.sh
this is needed at least for clean fedora 23 installs.
=> add redhat-rpm-config as dependency.

source/develop/developer-guide/engine/engine-development-environment.html.md
Some important instructions was missed when copying the old wiki to
the new site. This patch adds these missing instructions.
=> development-environment: sync with old wiki page.

source/develop/developer-guide/engine/engine-development-environment.html.md
malicap package is essential for installing and running ovirt, (as
stated in the README.developer file) therefor it must be included
in the package list specified in the setup instructions.
=> development-environment: Add a package to 3rd party setup list

source/develop/developer-guide/engine/engine-development-environment.html.md
After making an ovirt build, it is a common mistake to connect to the
webadmin with a browser that is not supported.
=> development-env: add a troubleshooting value.

source/develop/release-management/features/integration/allinone.html.md
Remove Alex's email address since it's not valid anymore.
Explicitly stated which the feature is deprecated in 3.6 and will be dropped in 4.0
Fixed current status
=> Updated all-in-one

source/index.html.haml
Currently home page points to oVirt 3.6.1 but we have a newer release.
=> Update home page pointing to oVirt 3.6.2 release

source/stylesheets/lib/site.sass
(Leaving classes in a span so it can be toggled locally for development or in a userStyle.)
This should address issue #15 by simply hiding that the pages do not exist (and are therefore "broken"). It was decided to not port the user pages on purpose, so they're intentionally "broken". As far as the site is concerned, they simply do not exist, and they will not be represented with a link.
In other words, MediaWiki-ported linking to user pages is now fully ignored by default.
=> comment out broken link styling

source/develop/dev-process/working-with-gerrit.html.md
Markdown has a known limitation where indented blocks inside a list are
interpreted as the part of the list, instead of a code block. Breaking
beforehand with an un-indented line (even if it has nothing but &nbsp;)
fixes this issue.
This patch completes the work of the previous PR and closes issue #91
Change-Id: I376efb63b7b8b25ad61b88baa51a7431e0197d61
=> Fixed broken code inside lists in "Working with Gettit"

source/develop/release-management/features/storage/importstoragedomain.html.md
This page was automatically generated when the site was migrated from
MediaWiki to Markdown. The result off this automatic conversion was
broken in several places (most notably around code-block formatting).
This patch fixes the major issues in this page.
Change-Id: I2ff20adf556dd2206b92d4553d249771b0e72ae7
=> Fix Import Storage Domain page

source/events/calendar.json.haml
rh-events recently had an event with no time; this patch fixes it where the calendar JSON info builds properly despite an event not having both a start and end times
=> handle the case where there's an event with no time

source/blog/2016-03-18-up-and-running-with-ovirt-3-6.html.md
re #153 -- there appears to be an issue w/ middleman right now where links at ovirt.org are being rewritten to be relative to the blog post they appear in. I'm working around this for now by swapping the markdown links for html style links.
=> fix links, work around issue 153

source/develop/developer-guide/download-devel-release.html.md, source/develop/release-management/features/infra/python-sdk.html.md, source/download/index.html.haml
In yum's man page in RHEL6 (so quite old release):
localinstall
Is used to install a set of local rpm  files.  If  required  the
enabled  repositories will be used to resolve dependencies. Note
that the install command will do a local  install,  if  given  a
filename. This option is maintained for legacy reasons only.
=> localinstall is deprecated in yum

source/documentation/quickstart/quickstart-guide.html.md
non-indented text in the middle of a numbered list resets numbering. this
patch fixes some easy instances, but trickier ones remain (e.g. all the ones with 'examples'.)
=> fix some numbering restarts

source/develop/api/pythonapi.html.md
Remove the redundant double indentation and formatting errors introduced
by the conversion from wikitext to markdown.
This patch addresses point 17 of issue #37
Change-Id: Ieac8549505edaadbf473e1481ad8ab6f8d81d520
=> Fix indentation in Python API code blocks

.gitignore
Added vi[m]'s temporary swap files to .gitignore to make editing the
site wit vi[m] easier.
Change-Id: I1e1edc8f6b07570989b63e0f323403f8bab16754
=> Add vi[m] swap files

source/develop/developer-guide/engine/engine-development-environment.html.md
changed to the correct location in the source tree at README.adoc instead of README.developer
on OVirt Engine Development Environment page
=> Updated latest certified documentation location

source/community/about/licensing.html.md
This patch is part of the work on issue #37.
Change-Id: Ieda583ccf9e9a03a7678d99e038422369443978f
=> Remove redundant spacing from the license example

source/documentation/migration-engine-3.6-to-4.0.html.md
Simple documentation about how to migrate ovirt-engine from 3.6 to 4.0.
Don't know if this is the better location for this documentation, so feel free to move it around, if there's a better place for it.
Also, we need to make sure to update ovirt-release rpm after release :-)
=> added doc about migrating ovirt-engine from 3.6 to 4.0

source/develop/release-management/features/storage/glance-integration.html.md
Fixed the formatting issues in the Glance Integration page:
- Filled in the "at the glance" (no pun intended) template
- Fixed markdown issues caused by the conversion from wikitext
- Fixed image paths
Change-Id: Ie1dbc427e947083d6551fc3d8b3b90f65b0cd165
=> Formatting issues on the Glance Integration page

source/layouts/feature.html.haml
When people have added non-Markdown files in the features directories, that has broken the build.
While the non-Markdown files should not have been added in the previous commits (which had build errors), the build should still not error out. I think there are cases where it might make sense to have non-Markdown files alongside feature pages. (Like `.txt` files, for whatever reason.)
=> handle non-markdown files in features directories

source/documentation/admin-guide/serial-console-setup.html.md, source/feature/container-support.html.md
This patch documents how to manually change the serial console port setting.
Fixes the ovirt-documentation part of
https://bugzilla.redhat.com/show_bug.cgi?id=1281283
=> Add documentation about how to change serial console port

Gemfile, Gemfile.lock, create-post.rb
Adds correct gems, upgrades `create-post.rb` to slop version 4, and enables one to run it without prefixing it with `bundle exec`.
(Ported from RDO: https://github.com/redhat-openstack/website/pull/581)
=> fixes & upgrades to create-post.rb

source/develop/developer-guide/vdsm/developers.html.md
VDSM build requires two new packages PyYAML openvswitch. So including these packages in the vdsm developer guide.
=> Add PyYAML and openvswitch as dependency for vdsm build

Dockerfile, setup.sh
Commit 4b49f9 changed the Gemfile to download files from
https://rubygems.org instead of http://rubygems.org. Using HTTPS
requires openssl to be installed, and while it's hard to imagine a
system that doesn't have it installed, we should not make any
assumptions. Especially in light of how cheap it is to verify this.
Change-Id: I90e4b25eade1c7a962014554bd76e6d43e5fd68c
=> Install openssl for gem updates

source/develop/developer-guide/vdsm/hook/scratchpad.html.md
Identical to https://gerrit.ovirt.org/#/c/58582/
(and fix a typo).
=> Fix syntax for scratchpad VDSM hook

source/search-results.json.haml
Forked from #284 — basically, fall back to using the modified file time on the FS if there's no git time.
When search indexing occurs, it looks for a datetime stamp in the metadata first, then in git (if it doesn't find it), and now also in the file's mtime if it is not found it git.
This covers the case when someone is building the site but hasn't checked in a file quite yet. (Basically: Development work.)
=> search index: fall back to file modified if there's no git time

config.rb, lib/wiki_helpers.rb
Handle the old wiki redirects directly in Middleman instead of relying on Apache.
(This may solve a few 404s, as the logic is a bit more sound than the Apache redirects. Plus, it's better to not have to rely on Apache redirects anyway.)
=> improved (ported) wiki link redirects

source/documentation/how-to/hosted-engine-host-OS-upgrade.html.md
Fixes #243.
1. Corrects heading depth (h1, h2, h3)
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
2. Nests bullet point text appropriately (uses consistent # of characters to the content)
Reference: http://kramdown.gettalong.org/quickref.html#lists
3. Prefer block code instead of relying on indentation
Advantages: 
- Same depth as rest of the content
- Could (optionally) use syntax highlighting
- Easier to understand that a code block occurs, instead of implying that a code block exists
- Easier to get the # of spaces for indentation right
- Consistent with typical GitHub usage
4. Removes defunct wiki category tag (@ line 154 in the original document)
- Proper use is `category:` in frontmatter metadata at the top of the document)
- For more info on …
=> fixed errors in hosted-engine-host-OS-upgrade doc

source/layouts/index.haml
Index pages previously displayed unsorted results; this change sorts subpages by alphabetical order (case insensitive).
=> index pages: sort subpages alphabetically

source/layouts/toc.haml, source/stylesheets/application.css.sass, source/stylesheets/lib/toc-md.sass
Ported directly from the RDO website (thought it existed on oVirt too — I guess it was an oversight)
=> add toc (table-of-contents) layout

source/stylesheets/application.css.sass, source/stylesheets/lib/target-enhancements.sass
when a target in a page is deep linked (selected by a hash in the URL — all headings get autogenerated IDs which are selected hashes), this snippet of CSS adds an offset and a little attention-grabbing animated color (yellow) that fades out
=> add a target highlight and anchor offset

source/layouts/toc.haml
addresses #181 (noticed that the requested page was a features page; this change lets the layouts transparently stack, so `layout: toc` will still show a features layout based on page's path)
=> added support for `layout: toc` in feature pages

source/blog/2016-06-23-ovirt-40-release.html.md
The markdown-style links get resolved as relative links and therefore broken, changed to html-style links to force absolute URLs.
=> Fixed links to oVirt.org pages in blog post

source/develop/release-management/features/kernel-cmdline.html.md
The feature is now outdated, as the feature was moved from VDSM to
ovirt-host-deploy project. This commit updates the page to inform of
feature's present state.
=> update kernel cmdline feature page

source/release/4.0.1/index.html.md
Provide link to migration guide as text since something is breaking the link while publishing it ot the website.
=> Provide link to migration guide as text

source/develop/release-management/releases/3.6/index.html.md
changelogs on release pages are all one big long wrapped line. I think this will get it to bulleted lists as intended, though it's hard to tell for sure since github preview is a little different that the actual live site.
=> fix changelog lists in 3.6 release page

source/blog/2016-07-20-announcing-the-ovirt-engine-dr-subproject.html.md
Note: Don't use offsite links for oVirt site links.
1. When you specify HTTP as the protocol, it will switch people from https to http, which defeats the purpose of HTTPS
2. This makes links brittle, in case the domain (or subdomain, such as
www) changes
3. It ties the document to the website itself
4. It breaks links when testing things locally
5. Linking the URL incorrectly might trigger Apache redirect rules
=> fixed link for an absolute path to the project

source/develop/developer-guide/vdsm/developers.html.md
rpm-python is required to build the rpm/s.
=> vdsm dev: Require package rpm-python

source/index.html.haml
- Update home page pointing to oVirt 4.0.2 release
=> Update home page pointing to oVirt 4.0.2 release

source/index.html.haml
- Update home page pointing to oVirt 4.0.3 release
=> Update home page pointing to oVirt 4.0.3 release

source/documentation/migration-engine-3.6-to-4.0.html.md
Fixes 4.0 repository URL which should be used to install oVirt 4.0 when
doing upgrade from 3.6 using engine-backup.
=> Fix 3.6 to 4.0 upgrade documentation

source/index.html.haml, source/layouts/_blog_posts.haml
Added support for limiting to # of articles in the blog_posts layout, and enabled support for oVirt by limiting to 3 article summaries.
=> Limit front page articles

source/community/get-involved/report-a-bug.html.md
Fixes issue #464
- remove the "community" step as oVirt has its own bug classification.
Fixing link on the instructions (Issue #464)
=> looks like the ovirt bug classification moved

source/develop/infra/testing/lago/testing-engine-patches-with-lago.html.md
- Added documentation about how to use lago and ovirt-system-tests to manually test a custom engine patch
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @rafaelmartins
This pull request needs review by: @sandrobonazzola @tiraboschi @irosenzw @lveyde @didib
=> Added documentation on how to test engine patches with lago

source/develop/developer-guide/vdsm/developers.html.md
- Separate sections for configuring, testing and making rpms
- Configuration: how to get available options
- Testing: using make targets
- Testing: running specific tests
- Making rpms: remove irrelevant testing flags, we don't run tests
during make rp now, see https://gerrit.ovirt.org/63966.
@dankenigsberg @mojaves @mureinik please review.
=> vdsm-developers: Enhance testing documentation

source/develop/index.html.md
- Added link to the Testing ovirt-engine patches with Lago page
=> Add link to testing engine with lago

source/community/index.html.md
- Fix broken link to Infrastructure team page
=> Fix broken link in Community page

source/develop/release-management/features/os-support/fedora-24-support.html.md
Fixes #518:
Never link to the website as an external resource. It's a bad idea for so many different reasons, with the most important being that it breaks the possibility to test the site locally. (In addition, it seems to mess up server redirection in some cases.)
=> remove `http://www.ovirt.org` from the link

source/develop/index.html.md
- Add team list linking to team pages to Develop main page
This pull request needs review by: @bproffitt @eedri
=> Add teams to Develop page

source/download/index.html.haml
- Dropping link from Fedora, RHEL and CentOS words pointing 10 rows later in the same document to the same anchor.
It creates expectation of reaching different landing points actually scrolling down 10 lines skipping a box marked as important.
=> Downloads: drop link to internal anchor

source/develop/developer-guide/vdsm/developers.html.md
Unlike the rest of code snippets in Vdsm Developers document, `git clone` commands are shown as inline code, not a code block. Because of that they are somehow easy to look over. For the sake of consistency and readability I change two `git clone` snippets from inline code into a code block.
=> use code block for git clone snippets

data/subprojects.yml
- Dropped Keith Roberts as maintainer for iso and image uploader and log collector after he left the project with his approval
- Added Rafael Martins as iso and image uploader and log collector as announced in mailing list (http://lists.ovirt.org/pipermail/devel/2016-August/013576.html)
=> Updated tools maintainers list

data/subprojects.yml, source/subprojects.html.haml
Added deprecated subprojects section
Related-To: https://bugzilla.redhat.com/1381223
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
This pull request needs review by: @garrett
=> subprojects: add deprecated section

source/develop/developer-guide/vdsm/developers.html.md
Vdsm replaced pep8 and pyflakes with flake8 tool. Explain how to run the
new style checks on all modules or specific module.
@mureinik @dankenigsberg, please review.
=> Update vdsm-developers after switching to flake8

source/develop/release-management/features/node/node-validate-pre-conditions-during-installation.md
- RFE documentation about oVirt Node Next installation requirements
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md) @dougsland
This pull request needs review by: @fabiand 
oVirt Node Next needs to validate the system where it's
getting installed to determine if it has the minimum
requirements for installation.
=> RFE: Node Validation during install

source/download/index.html.haml
- oVirt 3.6 has reached EOL, dropping it from OSes support list
=> Drop 3.6 OSes support list

source/documentation/index.html.haml
I'd appreciate some help or documentation that shows how links get translated in this file.
I've made this change based on the following observations
Absolute links are getting prefixed with /documentation.
for example - http://www.ovirt.org/release/  is becoming - https://www.ovirt.org/documentation/release/
whereas relative links do not get prefixed with /documentation.
for example - /develop/release-management/process/making-an-release/ 
becomes
https://www.ovirt.org/develop/release-management/process/making-an-release/ 
It is not clear how certain other links get translated
examples - 
(Community_activity) becomes - …
=> another attempt to fix broken links

source/index.html.haml
-
-
-
Home page still refers to current release as being 4.04. Current release as of November 11, 2016 is 4.05.
=> Update for 4.0.5 Release

source/develop/developer-guide/engine/writing-a-new-user-query.html.md
Remove deprecated instructions that haven't been relevant since oVirt 3.2 from the page.
This pull request needs review by: @aaviram 
As per the feedback on PR ##615, the section about "Queries with a
User ID as a parameter" is no longer relevant (since oVirt 3.3, in
fact).
This patch removes it so it doesn't confuse current developers.
=> Writing a new user query: queries with a user parameter

source/release/3.6.7/index.html.md
- Updated 3.6.7 release notes to explicit note that 3.6 is supporting only EL7 hosts
This pull request needs review by: @mykaul 
Signed-Off-By: Sandro Bonazzola <sbonazzo@redhat.com>
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1398107
=> Update 3.6.7 release notes

source/develop/release-management/features/sla/scheduling-weight-normalization.html.md
- A feature page for scheduling weight normalization
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @MarSik
This pull request needs review by: @doron-fediuck @rmohr @jtokar @yanirq
=> Add the feature page for Normalizing scheduling policy weights

source/develop/developer-guide/engine/engine-development-environment.html.md
- Added missing backquotes and spaces to make the corresponding text visible on the web page.
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @mz-pdm
=> Add missing escaping in Enable DEBUG Log

source/index.html.haml, source/layouts/_blog_posts.haml
This fixes PR #565 's build failure. This problem was introduced in b7c24a0 with the article limiting feature.
I also wonder what this line wants to achieve:
`summarize ||= summarize`
I guess it is supposed to be numeric to hold the default value site-wide.
Having @garrett 's insight before merging would be much better.
=> 'summarize' parameter must be numeric or Nil

.gitignore
Some developers may want to have a local version of the bundled gems.
Adding `/vendor` to `.gitignore` would allow them to do so without having
that directory pop up in `git status`.
This patch [very partly] addresses issue #661.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mureinik
=> Add bundle's vendor cache to .gitignore

source/blog/2016-12-20-ci-please-build.html.md
oVirt infra team added a new feature for
developers to build artifacts on CI,
on-demand, using just a comment in the patch.
Signed-off-by: Eyal Edri <eedri@redhat.com>
-
-
-
=> New blog from oVirt infra on 'build-on-demand' feature

source/documentation/how-to/hosted-engine.html.md
I confirm that this pull request was submitted according to the [contribution guidelines](/.github/CONTRIBUTING.md): @dwimsey
This pull request needs review by: 
The hosted-engine --deploy seems to require an appliance image to use, while the message shown during this part of the script indicates you can use 'None' and it will take longer but work, it seems to look for an image named None, fails and then reprompts for an image to use.  This seems to be the simplest work around and probably a better default for newbies since it leaves less room for guessing
=> Adding ovirt-engine-appliance package installation to Hosted Engine HowTo

source/layouts/index.haml
The build was working on some middleman and not others, and
failed in Travis. This was tested on RHEL 7, and is likely
the right fix.
=> Fix the build after the ovirt 4.0 merge

source/develop/projects/node/contributing-to-the-node-project.html.md
- Add an overview of who's in Node team and what the team is doing
This pull request needs review by: @evol262 @dougsland @irosenzw @fabiand
=> Add team details to contributing to Node page

source/develop/release-management/features/infra/Engine_vacuum.md
- The engine vacuum setup plugin is now 'false'
- markdown fixes for code snippets (apparently ruby's markdown library
needs a blank space before a code snippet (triple backquotes)
Signed-off-by: Roy Golan <rgolan@redhat.com>
@mykaul @bproffitt
=> Engine vacuum: content and markdown fixes

source/documentation/index.html.haml
- Fix oVirt Global Workshops link, pointing to http://www.ovirt.org/community/events/archives/workshop/global-workshops/
=> Fix oVirt Global Workshops link

source/develop/developer-guide/engine/engine-development-environment.html.md
Adds python-dateutils to the list of required packages for engine
development environment.
Signed-off-by: Martin Perina <mperina@redhat.com>
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mwperina
=> Add python-dateutil to required packages

source/community/events/archives/workshop/global-workshops.html.md
- Open Virtualization Alliance has dissolved since 2016, removed reference to it.
=> Removing reference to OVA in global workshop

source/index.html.haml
- Get started with oVirt 4.0.6 points to Download wiki page, resulting in a 404 error. Fixing the link pointing to website download page.
=> Fix home page link to Download

source/index.html.haml
- Update Home page pointing to 4.1.0
=> Update Home page pointing to 4.1.0

source/documentation/index.html.haml
In ovirt.org/documentation quickstart link is broken.
- fix quickstart link in documentation
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (@dougsland)
This pull request needs review by: (@sbonazzo)
=> documentation: fix quickstart link

source/documentation/how-to/virtual-machines/enable-usb2-linux-vm.html.md
- add file enable-usb2-linux-vm.html.md in how-tos. 
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @mention yourself to sign) @jwoytek
=> added how-to for enabling usb2 on linux vms

source/node/index.md
- Added links to latest installation iso and the jenkins job for ovirt-node-ng for ovirt-4.1
@yuvalturg
=> Added links to downloading ovirt-4.1

source/develop/release-management/features/virt/headless-vm.html.md
Fixes issue from BZ1425076 by adding a limitation for setting grub to boot in console mode since otherwise it may hang.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @sgratch
This pull request needs review by: @jelkosz
=> Headless VM - adding a limitation for setting grub to boot in console mode

source/index.html.haml
- Update home page pointing to 4.1.1
=> Update home page pointing to 4.1.1

source/develop/release-management/features/hot-unplug-memory.html.md
- Memory hot unplug works on current RHEL/CentOS guests, not on most Linux systems.
- Manual guest OS configuration is not needed, new ovirt-guest-agent handles it.
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @mz-pdm
This pull request needs review by: @jniederm
=> Memory hot unplug documentation updated

source/index.html.haml
- On home page, changed "News" heading to "Blog"
-Middleman didn't respond, so unable to see change in test site. The site says "oVirt News" so where is the "oVirt"
-
This pull request needs review by: @bproffitt @mykaul
=> changed News heading to Blog

source/develop/release-management/features/network/import-vm-net-changes.html.md
The "storage_domain" parameter seems not to be present in the API.
See https://gerrit.ovirt.org/#/c/72896/1 for a recent change which touched the relevant part of code today.
=> import-vm-net-changes: remove "storage_domain"

setup.sh
- added a test of the linux distro to the setup.sh file and added commands to setup for Debian 
I tested the script on Fedora 25 (workstation edition) and on Mint Serena 18.1 (based on Ubuntu Xenial), and it worked on both. 
After running the setup.sh file on both systems, the run-server.sh script worked in both cases, so I didn't change it. 
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @lgh2
This pull request needs review by: @jasonbrooks
=> added setup commands for Debian

source/documentation/quickstart/quickstart-guide.html.md
Fixes issue #879 
- Update image references. Image names had been changed (in a lot of cases, the filename now began with a capital letter). Their formats were different as well (in the original, they were referenced as .jpg, but in the ovirt-site/source/images/wiki folder, most of the images are .png files)
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): @leni1
This pull request needs review by: @jasonbrooks
=> Update Image Links in oVirt's Quick Start Guide

source/develop/developer-guide/vdsm/on-ubuntu.html.md
Fixed typo: guntils-bin to gnutils-bin
- Fixing a typo in package name "guntils-bin" (changed to gnutils-bin)
@dgramop
=> Fixed Typo in package name

source/javascripts/lib/headings_anchors.js, source/stylesheets/application.css.sass, source/stylesheets/lib/headings_anchors.css
Solution borrowed from:
https://milanaryal.com/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/
Fixes issue #775
=> Added anchors to all headings

source/develop/dev-process/install-nightly-snapshot.html.md
- Removed instructions for installing 3.6 and 4.0 nightly snapshot, gone EOL long ago and not available anymore
=> nightly-snapshot: removed 3.6 and 4.0

source/documentation/index.html.haml
- Changed h tag above "previous release notes" from H3 to H4.
http://www.ovirt.org/documentation/
-
-
=> changed h tag above previous release notes

source/develop/release-management/releases/3.6.z/release-management.html.md
- 3.6 gone EOL a long time ago and nightly builds are not available anymore. Removed the section
=> Remove 3.6 nightly builds references

source/documentation/index.html.haml
- Developer Documentation Deleted from main Documentation Page
- Other sections on page reordered to accommodate the change
- All links have been tested
- Middleman screenshot attached 
(https://cloud.githubusercontent.com/assets/25613123/25813250/805fd9c6-3421-11e7-9ab6-c687759e3294.png)
I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md) @jmarks
This pull request needs review by: (please @duck-rh @doron-fediuck @dankenigsberg @mykaul
=> Developer Documentation removed from Documentation Page, Page Reordered

source/develop/developer-guide/vdsm/developers.html.md
Trying to install both Fedora 24 and 25 packages on Fedora 25 is a bad idea,
users should use the relevant packages.fcXX file.
@dankenigsberg, @mykaul please review.
=> Fix instructions so they work for Fedora 25

lib/site_helpers.rb, source/develop/release-management/releases/3.5.2/index.html.md
Links may not have a title, so the regex was wrong.
Fixes issue #953
=> fix link magic in markdown_to_html

source/documentation/how-to/migrate-pki-to-sha256.html.md
Without this, '```sh' is treated as part of the text, and '#' comments
inside the commands are treated as section headers.
-
-
-
=> how-to/migrate-pki-to-sha256.html.md: Fix style

config.rb
see https://github.com/middleman-contrib/middleman-deploy/issues/51
-
-
-
=> 'development' env should not be loaded for deploy action

source/release/4.1.2/index.html.md
Corrected 2 broken links 
-[Installation Guide](/documentation/install-guide/Installation_Guide/).
-[release notes for previous versions](/documentation/#previous-release-notes).
in both instances the full stop was placed in the square brackets [Installation Guide.]
- The following two broken links have not be resolved (and are being reused in the template)
If you're going to install oVirt as Hosted Engine on a clean system please follow *Hosted_Engine_Howto#Fresh_Install guide* or the corresponding section in *Self Hosted Engine Guide*
If you're upgrading an existing Hosted Engine setup, please follow *Hosted_Engine_Howto#Upgrade_Hosted_Engine* guide or the corresponding section within the *Upgrade Guide*
I confirm that this pull request was …
=> 4.1.2 release notes broken links

source/community/index.html.md
This PR is a reorganization of the content on the main [oVirt community](https://www.ovirt.org/community/) page. The changes are:
1. Get Involved: Because this is an introduction it has been formatted so that it takes up the full length of page. The two-column format starts below it.
2. The page contained repeated information. This has been removed.
3. All the topic paragraphs (find and file bugs, documentation, etc) have been re-written, so that they are clearer, contain the relevant information, and more engaging.
4. The wording has been adjusted so that the headings in both columns line up with each other. It's visually more appealing that way.
-I confirm that this pull request was submitted according to the [contribution guidelines](/CONTRIBUTING.md): (please @jmarks
This pull request …
=> changes to structure and content of community page

source/community/user-stories/users-and-providers.html.md
Fixes issue **page too long**
The page has been reformatted:
- Currently, the individual companies / orgs are separated by the tag: **div class="parner-block"**
The layout is cumbersome and takes up too much space. Therefore, I have replaced **div class="parner-block"** with **div class="case-study"** as used on the case studies page.
Companies and orgs removed:
- To make the page shorter and avoid overalp, I have removed descriptions of organizations that already have a case study. For example: Brussels Airport and Keele University. Instead, I have added a short text and a link to the case study.
Edits
- I have edited the page to make all the description shorter and tighter
I confirm that this pull request was submitted according to the …
=> changes to users and providers page

source/documentation/introduction/about-ovirt.html.md
The opening paragraph on the [About oVirt](http://0.0.0.0:4567/documentation/introduction/about-ovirt/) page, featured two broken links. There also seemed to be a mismatch between the wording and the intended links.
Page:
http://www.ovirt.org/documentation/introduction/about-ovirt/
- I have updated the links and modified the sentence in which they are contained.
This pull request needs review by: @sandrobonazzola @mykaul
=> About oVirt intro paragraph and text

source/documentation/index.html.haml
- Updated links to release notes on my Documentation page: 4.1.3. 4.1.2
- Is 3.0 still relevant?
=> Updated links to release notes

source/develop/release-management/features/engine/metrics-store-collected-metrics.html.md
Changing the feature name meta tag also changes link text so that it reads Metrics Store Collected Data.
- This will make it easier to distinguish between this feature and the other two features names "Metrics Store"
=> Change Metrics Store Collected Data Feature Name Meta Tag

source/layouts/feature.html.haml, source/stylesheets/lib/site.sass
Status colors on [feature page ](https://www.ovirt.org/develop/release-management/features/) make the page hard on the eyes and the color codes don't really add value as the viewer wouldn't necessarily know what they represent
- Remove status color coding so that all links will be in green - like elsewhere on site
- Bold green for selected feature remains unchanged 
This pull request needs review by: @mykaul @duck-rh
=> Remove status colors from feature list

Gemfile.lock
Minimum changes I could find to have gems install properly on F26.
=> Fedora 26 support

Gemfile.lock
Older bundler removes this information while doing a bundle install,
while this operation has no reason to tamper with this file. This in
turn causes problems when updating the repository on the web builder.
=> Remove 'BUNDLED WITH' in Gemfile.lock

source/documentation/index.html.haml
Fixes issue #1045
- Dropped obsolete videos referring to unsupported releases and unsupported all-in-one deployments.
This pull request needs review by: @mykaul @doron-fediuck
=> Drop obsolete videos

source/index.html.haml
- Update home page pointing to 4.1.6 released today
=> Update home page with 4,1.6

source/documentation/gluster-hyperconverged/Gluster_Hyperconverged_Guide.html.md, source/documentation/gluster-hyperconverged/chap-Additional_Steps.html.md, source/documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html.md, source/documentation/gluster-hyperconverged/chap-Introduction.html.md, source/documentation/gluster-hyperconverged/chap-Maintenance_and_Upgrading_Resources.html.md, source/documentation/gluster-hyperconverged/chap-Troubleshooting.html.md
Currently, links on the Gluster-hyperconverged page are broken:
https://www.ovirt.org/documentation/gluster-hyperconverged/Gluster_Hyperconverged_Guide/
This patch fixes links to make navigation between pages possible again.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jekader
=> fix links to Gluster-Hyperconverged documentation

source/download/index.html.haml
- Removed references to oVirt Live from download page: it's deprecated and partially broken in 4.1, removed in 4.2.
=> Remove references to oVirt Live

source/download/index.html.haml
this patch updates the list of supported guest operating systems based on the list in the VM properties menu
- RHEL7 - 32-bit removed as this version only comes as 64-bit
- added win10
- added win2k16
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jekader
This pull request needs review by: @sandrobonazzola @JohnMarksRH
=> update list of supported guest OSes

source/develop/release-management/features/sla/hosted-engine-new-deployment.html.md
updated ansible-playbook hosted-engine.yml to the current file name in code :    hosted_engine.yml   (underscore) 
I confirm that this pull request was submitted according to the contribution guidelines: @yanirq
=> updated file name in installation instructions

source/develop/release-management/features/ux/plugins.html.md, source/develop/release-management/features/ux/uipluginsoriginaldesignnotes.html.md
- In line with plan to reorganize feature categories, the two plugin features have been moved under "UX"
=> Move Plugin features to UX Category

docker-run.sh
If selinux was enabled, volume defined in script docker-run.sh was
mounted but inaccessible. 'z' volume flag instructs docker to fix the
labeling.
Reference doc: https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-the-selinux-label
Details: https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
@garrett please review
=> SELinux labeling fix for container setup

source/blog/2017-12-04-lvm-configuration-the-easy-way.html.md
- New blog posy
- One comment - at the beginning of the post we say "The new command, `vdsm-tool config-lvm-filter` analyzes the current LVM configuration to decide
whether a filter should be configured. Then, **whenever possible**, a filter is automatically generated.
Can we say something more concrete than "whenever possible"?
-
This pull request needs review by: @nirs @mykaul
=> Blog Post - LVM Configuration

source/index.html.haml
- Update home page pointing to 4.2.0 release
=> Update home page pointing to 4.2.0 release

source/community/about/contact.html.md
- Add link to official list of mailing lists related to oVirt
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @mention yourself to sign) @sammcj
Helps #1228
=> fix link for mailing list info

source/layouts/index.haml
Remove the header in certain pages that says: "X pages under...". Those are not result pages, they contain ony list of other child pages - no need of search/result semantic
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @eldan yourself to sign)
This pull request needs review by: (please @rollandf  the reviewer if relevant)
=> Remove the header in certain pages that says: "X pages under...".

source/documentation/draft/video-ram.html.md, source/documentation/internal/video-ram.html.md
video-ram.html.md is the last file remaining in source/documentation/draft/, let's move it to a better place.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @mz-pdm
=> Move video ram

source/develop/release-management/features/virt/virt-sparsify.html.md
* Adding hints for making virt-sparsify to work on iSCSI.
* Adding note about bug 1489262 that prevents virt-sparsify from working
on NFS partitions under RHEL 7.4.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @smelamud
=> Updating virt-sparsify feature page parts related to iSCSI and NFS

source/develop/release-management/features/infra/cli.html.md
It was difficult to read the auto-completion outputs because they were not in a code block. There were many inconsistencies with indentation. Some parameters were not in code blocks that needed it to prevent being turned into an emdash.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @duckbrain
=> Cleanup CLI code blocks and indentation

source/documentation/how-to/hosted-engine.html.md
cockpit daemon is static so cannot be enabled, therefore enabling cockpit.socket instead
@tiraboschi @sandrobonazzola
=> enable cockpit service by enabling cockpit.socket

lib/site_helpers.rb
The regex would probably never be perfect enough. This causes link
breakage, and hide problems or lack of proper formatting.
fixes #1503
=> remove URL magic in markdown_to_html()

source/documentation/self-hosted/chap-Installing_Additional_Hosts_to_a_Self-Hosted_Environment.html.md
- Add a note on the installing additional hosts page stating that you must reinstall oVirt via the web-UI if you wish to add the ability to run the self-hosted engine (e.g. if it wasn't selected when first installed).
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sammcj
=> add note on adding self-hosted engine to already installed host

source/documentation/index.html.haml
Fixes issue #1632
- Dropped dangling link to  "Additional Documentation" -> "Drafts" 
This pull request needs review by: @shaunix
=> Update Documentation index

source/documentation/gluster-hyperconverged/chap-Deploying_Hyperconverged.html.md
- Add a step indicating that gluster-vdsm has to be installed on enterprise linux hosts.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rohantmp
This pull request needs review by: @sabose
=> Update Doc: Deploying oVirt and Gluster Hyperconverged. Add missing dependency installation step.

source/documentation/how-to/ovirt-and-containers/Using-oVirt-Engine-with-ManageIQ-container.html.md, source/documentation/how-to/ovirt-and-containers/Using-oVirt-Engine-with-a-PostgreSQL-container.html.md, source/documentation/how-to/ovirt-and-containers/about-containerized.html.md
As part of the Outreachy project for oVirt, we are trying to document using oVirt with several other open source software components in software containers as outlined [here](http://www.ovirt.org/community/activities/outreachy/).
- Addition of a folder to hold the documentation proposed above. 
- Document detailing the aims behind the proposed documentation
- Sample documentation for using PostgreSQL in a container with the oVirt Engine. 
- Sample documentation for using ManageIQ in a container with the oVirt Engine.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):  @leni1
This pull request needs review by: @jasonbrooks
=> Documentation for using containers with oVirt

source/download/index.html.haml
SSL everywhere is a good idea overall, but is a MUST condition for installation instructions to use sudo to install packages.
While we're at it, might as well update all the links to good ol' resources.ovirt.org .
I recommend updating the other links for the mirrors, but did not find a viable HTTPS endpoint (I didn't look further than to attempt to load the page as https://). The mirrors that did have a valid HTTPS endpoint were updated in this PR. Perhaps you can request your mirror providers to use an SSL certificate now that e.g. Let's Encrypt is ubiquitous, useful, automatable, etc.
Modify project URLs to use HTTPS
Modify mirror URLs to use HTTPS where available
I confirm that this pull request was submitted according to the contribution …
=> SSL for install instructions (was #1626)

source/documentation/how-to/hosted-engine.html.md, source/documentation/self-hosted/chap-Installing_Additional_Hosts_to_a_Self-Hosted_Environment.html.md, source/documentation/upgrade-guide/chap-Updates_between_Minor_Releases.html.md
Clean up and clarify hosted-engine upgrade process
- Favour the main upgrade guide over an individual howto for the hosted-engine
- Add hosted-engine section to the upgrade guide
- Add link to upgrade guide from (legacy) how to
- Add missing step of running `engine-setup` within the hosted engine VM
- Clarify what commands are run on the host vs the hosted-engine VM
- Code quote commands
- Remove link referencing old bugs
- Cleanup formatting
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sammcj
=> clean up hosted-engine upgrade how-to

source/develop/developer-guide/engine/engine-development-environment.html.md
- escape quotes so that command can be copy-pasted directly into cmd line
@vjuranek
=> Escape quotes

source/develop/developer-guide/vdsm/developers.html.md
- move existing instructions how to run VDSM tests locally into dedicated subsection
- create new subsection with instruction how to run VDSM tests with `pytest` and `tox`
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @vjuranek 
well, almost: I wasn't able to test changes locally as `./run-server.sh` fails on my machine
=> Update instructions how to run VDSM tests

data/authors.yml, source/documentation/upgrade-guide/chap-Updates_between_Minor_Releases.html.md
- Fixed broken link to downstream Red Hat link: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html/upgrade_guide/updates_between_minor_releases
- Added myself as author
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @crutonjohn
=> Fixed outdated link to downstream RH content.

source/documentation/index.html.haml
- Add 4.3.0 Alpha to release notes links
This pull request needs review by: @gregsheremeta
=> Add 4.3.0 Alpha to release notes links

source/develop/developer-guide/vdsm/sanlock.html.md
- update obsolete sanlock link
- remove wdmd link as wdmd info is part of newly linked sanlock README
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @vjuranek
=> Update obsolete sanlock link

source/documentation/install-guide/chap-oVirt_Nodes.html.md
The oVirt nodes page had a 404 link to Adding a Host. Fixed.
=> documentation: fix 404 on documentation/install-guide/chap-oVirt_Nodes

source/.htaccess.haml
the blog generator doesn't put a proper index.html file in
/blog, so redirect /blog/ -> blog.html
=> add redirect to fix blog link

config.rb, source/layouts/developer_outdated.html.haml
add warning message to all old developer documentation
that it is outdated and the official documentation should
be consulted.
=> docuementation: add warning to old developer documentation

source/develop/index.html.md
documentation: add warning to developers page about outdated docs
=> documentation: add warning to developers page about outdated docs

source/documentation/vmm-guide/appe-Reference_Settings_in_Administration_Portal_and_User_Portal_Windows.html.md
documentation: fix broken link in vmm reference
=> documentation: fix broken link in vmm reference

source/blog/2019-01-06-ovirt-openshift-part-1.html.md
The needed label for router was just a bug in the inventory that is fixed now, so I removed the part which mentions that.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rgolangh 
@rollandf
=> Removing the wrong comment in OKD post

source/release/4.2.8/index.html.md
- Project released a new ovirt-engine-metrics package fixing compatibility with new oVirt Node NG 4.3 to ease upgrades.
=> Update 4.2.8 with new metrics package fixes

source/stylesheets/_application-custom.css.sass
mobile: fix nav menu on mobile
navigation menu was broken on mobile. Correctly positioned it
and shrunk the font size.
=> mobile: fix nav menu on mobile

source/documentation/admin-guide/chap-Proxies.html.md
- Added option to Squid Proxy configuration `cache_peer`, otherwise it won't send Basic Auth headers to peer
This pull request needs review by: @gregsheremeta
=> Fixed Squid Proxy auth bug in documentation

source/download/index.html.md
add 'sudo' to subscription-manager commands. Now matching all of the other commands on the page, which have it.
=> add 'sudo' to subscription-manager commands

source/layouts/_footer.haml, source/stylesheets/lib/site.sass
change footer pencil icon to github icon
=> change footer pencil icon to github icon

source/layouts/_footer.haml
fix the documentation issue template link on the
documentation page footers.
=> issue template enhancements part 2

source/layouts/_footer.haml
change footer pencil icon to github icon (again)
=> change footer pencil icon to github icon (again)

source/layouts/_footer.haml
tweak footer links
- Remove reference to gitbub from footer issue links
- change page issue link to clarify that _this_ page has
the issue
=> tweak footer links

source/documentation/admin-guide/appe-oVirt_and_SSL.html.md
- SSL_CERTIFICATE should point to the file in `certs` folder
-  the websocket proxy should be restarted too.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @yeya
This pull request needs review by: @gregsheremeta
=> Fix typo and additional required step

CODEOWNERS
remove gregsheremeta from codeowners
=> remove gregsheremeta from codeowners

.github/ISSUE_TEMPLATE/issue_template_documentation.md
remove gregsheremeta from default reviewer on docs issues
=> remove gregsheremeta from default reviewer on docs issues

source/develop/release-management/features/network/ipv6_subnets.html.md
Add support for stateless DHCPv6 address configuration.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @maiqueb 
@mmirecki 
@mburman5 
@MosheSheena
=> Update IPv6 OVN subnet feature page supporting RAs

source/develop/developer-guide/vdsm/developers.html.md
This change depends on the new --enable-timestamp configure option added
in https://gerrit.ovirt.org/c/98830.
With this option, a developer can use "dnf upgrade *.rpm" to install the
latest build.
@dankenigsberg @rollandf please review.
=> Update vdsm build instructions for developers

source/documentation/admin-guide/appe-oVirt_and_SSL.html.md
---
title: Add 3rd-party SSL certificates for imageio-proxy
authors: pmartin
---
Without the 3rd party certificates in place to match those in apache, the certificate authentication can fail.
By matching with the apache certificates it passes the same certificates and authentication, allowing admins to upload ISOs.
- Add references for 3rd party certificates for imageio 
@paulmartincsi
This pull request needs review by: anyone
=> Add 3rd-party SSL certificates for imageio-proxy

source/develop/release-management/features/integration/websocketproxy-on-a-separate-host.html.md, source/develop/release-management/releases/3.5.2/index.html.md
<http://> generates an empty link, not very useful.
Btw the right way to escape <this> is like \<that>. So this also fix the
display of the variable part of the URLs in the examples.
=> fix broken links

.travis.yml, source/develop/release-management/features/infra/link-following.html.md, source/develop/release-management/features/sla/affinity-labels-management-via-admin-portal.html.md
=> ci: fail build if obsolete wiki headers are reintroduced

source/documentation/vmm-guide/chap-Installing_Linux_Virtual_Machines.html.md
No information is easily available for getting the ovirt-guest-agent running on Atomic (or any other container distributions) - having these pointer commands may help others save a couple of hours.
*Note*: at the time of writing, the guest agent doesn't start since the OCI spec is old.  I'm not sure how to file a bug for this.  Basically, it seems the Docker Hub image at https://hub.docker.com/r/ovirtguestagent/centos7-atomic/ isn't up-to-date with the repo. Specifically, the config.json file isn't in-line with https://github.com/projectatomic/atomic-system-containers/blame/master/ovirt-guest-agent-centos/config.json.template
- add small section for ovirt guest agent on atomic hosts
I confirm that this pull request was submitted according to the …
=> Add ovirt guest agent info for Atomic hosts

source/documentation/admin-guide/appe-oVirt_and_SSL.html.md
This patch fixes wrong filepath in the example code
from 10-setup.conf to ovirt-imageio-proxy.conf
Closes-Bug: #2005
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @mkowalski
=> Fix incorrect example for ovirt-imageio-proxy.conf

source/release/4.3.6/index.html.md
- Add workaround for getting sanlock while waiting for CentOS 7.7
=> Update 4.3.6 rc2 notes

source/layouts/_footer.haml, source/stylesheets/lib/site.sass
Display was disabled but the code was still there and ran `git log` for
each and every page, which was crazy time consuming.
=> Remove page last modified info feature

Gemfile, Gemfile.lock
we do not use this format and its underlying engine, therubyracer, is
crashing under more recent Ruby versions, preventing from upgrading the
builde.
=> remove unnecessary 'less' format support

setup.sh
install nodejs instead of the crashing and unmaintained therubyracer
gem.
=> a JS engine is still needed for coffee scripts

run-server.sh, setup.sh
- specify bundle path avoiding to require sudo rights.
=> Specify bundle path on setup

Gemfile, Gemfile.lock, _config.yml
Reverts oVirt/ovirt-site#2089
This was marked WIP (Work In Progress) and it is not ready.
=> Revert "WIP: add asciidoc support"

source/documentation/metrics-install-guide/Deploying_Collectd_and_Rsyslog.md, source/documentation/metrics-install-guide/Upgrading_Metrics_Store.html.md
ovirt 4.3: fluentd replacement with rsyslog procedure.
Signed-off-by: Evgeny Slutsky <eslutsky@redhat.com>
=> Add Metrics 4.3 Upgrade Manual

source/index.haml
- Removing banner for oVirt conference, successfully completed yesterday
=> Remove oVirt conference banner from home page

Dockerfile
With Centos8 now the default centos image in docker hub, the existing setup doesn't work.  Easiest fix is to force docker to use centos 7.  Another option would be to find the right set of packages to get it working on centos 8.
Fixes #2117
- `Dockerfile` to use `centos:7` instead of `centos` / `centos:latest`
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sjd78
=> Update Dockerfile to use Centos 7

source/_includes/feature.haml
- Adding  missing spaces in Feature Pages warning
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @rollandf 
This pull request needs review by: @duck-rh @sandrobonazzola
=> Add missing spaces in Feature Pages warning

source/develop/security/security.md
Fixes issue #2003
- Fix broken link to security advisories page
=> Fix link to security advisories

source/develop/release-management/features/sla/self-hosted-engine-gluster-support.md, source/documentation/admin-guide/chap-Working_with_Gluster_Storage.md, source/documentation/self-hosted/chap-Deploying_Self-Hosted_Engine.md, source/documentation/self-hosted/chap-Migrating_from_Bare_Metal_to_an_EL-Based_Self-Hosted_Environment.md
Signed-off-by: Sahina Bose <sabose@redhat.com>
- Updated the options that need to be set on gluster volumes when used as storage domain in oVirt
This pull request needs review by: @nirs @gobindadas
=> Updated gluster volume options for gluster storage domains

source/develop/release-management/features/storage/editing-floating-disks.md
To extend a disk from the REST API, the parameter that should
be sent is 'provisioned_size' and not 'size' as previously described.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @sleviim 
This pull request needs review by: @rollandf @danielerez
=> Change 'size' to 'provisioned_size' on command's description

source/download/alpha.md
- Update Alpha download page pointing to CentOS 8.1
=> Update alpha download page

source/community/get-involved/repository-mirrors.md, source/community/index.md
Signed-off-by: Evgheni Dereveanchin <ederevea@redhat.com>
Fixes OVIRT-2916
- move repository-mirrors to the Community section from the deprecated Documentation section
- update email to automatically create JIRA tickets
- link to RTD page for admins on setting up mirrors
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jekader 
This pull request needs review by: @marchukov
=> Move repository-mirrors to the Community section

source/download/node.md
- Updated node page pointing to new references in oVirt 4.3 installation guides.
- Added references to 4.4 beta ISO.
=> node: update page to match 4.3 docs and 4.4 beta

source/_includes/nav.haml
- In generated pages page-top anchor doesn't exist. Using page-wrap instead.
This fixes 1111 broken links.
=> nav: fix link to page-top

source/_sass/lib/events.sass, source/_sass/lib/site.sass
Fixes issue #2077
-  Reduced events z-indexes from 500 to 99 so they'll go under the top bar when scrolling (fixes #2077)
- Raised z-index of the top header to 110 since other elements have z-index 100 and we don't want them to overlap the header bar
=> Adjust z-indexes

source/documentation/upgrade_guide/index.adoc
- Added section on upgrading self-hosted engine to ovirt 4.4 beta.
=> upgrade-guide_he_4.4-beta Added Self-hosted engine section

source/develop/release-management/features/storage/incremental-backup.md, source/documentation/incremental-backup-guide/incremental-backup-guide.md
The incremental-backup-guide.md is not up to date, unify the documentation
according to incremental-backup.md.
Also, fix some documentation errors is incremental-backup.md.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md):@shenitzky
=> Unify incremental-backup.md and incremental-backup-guide.md

source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_Cockpit.adoc
Minor change to the docs, I've been trying to setup the hosted engine with a user I created during ovirt-node install. That does not work and provides an error message that is not really helpful "Deployment failed" with an error about permission denied in /var/lib/ovirt-hosted-engine-setup/cockpit/
I was not the only one not getting that root needs to be used: https://lists.ovirt.org/archives/list/users@ovirt.org/message/G452P2BN7Z7SBIGX3V6PB2RKDZJ72KKI/
So here is an explicit mention that the root user is to be used for cockpit.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @Klaas-
=> Docs: Use root user for hosted engine deployment via cockpit

source/_includes/feature.haml
Current spaces around strong text are ignored. Use &nbsp; to add space
around strong text in feature pages warning.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @vjuranek
=> features warning: add spaces around strong text

source/documentation/common/collateral_files/ovirt-attributes.adoc
Fixes issue #2332
- update documentation for displaying 4.4 instead of 4.4-beta. Adapted from downstream documentation patch 8ca2d191ac757d4019d34038b27b656e10c07a0e by @rolfedh 
This pull request needs review by: @rolfedh
=> Update the value of `:vernum_rhv:` from `4.4-beta` to `4.4`

source/documentation/common/collateral_files/ovirt-attributes.adoc
ovirt-attributes contained:
URL_virt_product_docs: https://ovirt.org/documentation
which caused the generation of broken links like:
https://ovirt.org/documentationvmm-guide/Virtual_Machine_Management_Guide.html#Importing_a_Virtual_Machine_from_Xen
in /documentation/administration_guide/index.html
changing it to:
:URL_virt_product_docs: /documentation/
so the broken url should become:
/documentation/vmm-guide/Virtual_Machine_Management_Guide.html#Importing_a_Virtual_Machine_from_Xen
and be also available when running the site locally.
This pull request needs review by: @stoobie , @rolfedh , @pmkovar
=> docs: use relative urls

source/documentation/administration_guide/topics/Red_Hat_Virtualization_Hosts.adoc, source/documentation/common/she/proc-Booting_a_self-hosted_engine_in_rescue_mode.adoc
- admin guide: fix broken links to RHEL docs
=> admin guide: fix broken links to RHEL docs

.travis.yml, test.rb
Fixes: #1228
- Enable external site url check with 6 weeks caching.
Example from: https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis
This completes all url testing within the website.
=> automation: enable external site url check

source/develop/release-management/features/infra/python-sdk.md
Fixes issue #728
- made it clear that the page is related to version 3 of the API
- Added link to version 4 documentation
=> python-sdk: marked as v3 API and linked v4

source/documentation/data_warehouse_guide/chap-Installing_and_Configuring_Data_Warehouse.adoc, source/documentation/data_warehouse_guide/topics/Overview_of_Configuring_Data_Warehouse.adoc
- fixes:
`asciidoctor: WARNING: topics/Overview_of_Configuring_Data_Warehouse.adoc: line 2: section title out of sequence: expected level 2, got level 3`
=> docs: DWH Guide: fix title sequence

source/documentation/virtual_machine_management_guide/assembly-Installing_Red_Hat_Enterprise_Linux_Virtual_Machines.adoc, source/documentation/virtual_machine_management_guide/chap-Additional_Configuration.adoc, source/documentation/virtual_machine_management_guide/chap-Installing_Windows_Virtual_Machines.adoc, source/documentation/virtual_machine_management_guide/topics/Configuring_operating_systems_with_osinfo.adoc, source/documentation/virtual_machine_management_guide/topics/Installing_Windows_on_Virtio_Optimized_Hardware.adoc, source/documentation/virtual_machine_management_guide/topics/Opening_a_Console_to_a_Virtual_Machine.adoc, source/documentation/virtual_machine_management_guide/topics/Opening_a_console_to_a_virtual_machine.adoc, source/documentation/virtual_machine_management_guide/topics/Powering_on_a_virtual_machine.adoc
- Fixes:
```
asciidoctor: WARNING: topics/Powering_on_a_virtual_machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Opening_a_console_to_a_virtual_machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Automatically_connecting_to_a_Virtual_Machine.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: WARNING: topics/Installing_Windows_on_Virtio_Optimized_Hardware.adoc: line 2: section title out of sequence: expected level 3, got level 4
asciidoctor: …
```
=> virtual_machine_management_guide: fix title levels

source/documentation/admin-guide/virt/console-client-resources.md
There is no software remote-viewer available. Given that the linked page only lists a "virt-viewer" I guess that this is the software the author wanted to link to.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @modir
=> Wrong software name

source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc, source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc
- A few leftovers still mentioned to install Engine on EL7. Fixed referencing EL8.
This pull request needs review by: @santos1709
=> docs: install: fix reference to EL 8 instead of EL7

source/develop/dev-process/working-with-gerrit.md
On Fedora 33, there is a problem to reach Gerrit.
This has been confirmed by multiple Fedora 33 users.
The following error occurs:
"<your name>@code.engineering.redhat.com: Permission denied (publickey)"
Adding "PubkeyAcceptedKeyTypes=+rsa-sha2-512" to ~/.ssh/config
solves this issue.
=> Add solution to permission denied issue on Fedora

source/documentation/common/prereqs/ref-Manager_Hardware_Requirements.adoc
- Make engine hardwdare requirements explicit about needing x86_64 architecture.
Bug-Url: https://bugzilla.redhat.com/1910847
This pull request needs review by: @stoobie @emarcusRH
=> engine hw reqs: explicit x86_64 arch

source/documentation/common/install/appe-Set_up_Cinderlib.adoc
`python3-cinderlib` is the required package for cinderlib, of which openstack-cinder is a dependency
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @bennyz
=> change openstack-cinder to python3-cinderlib

source/documentation/administration_guide/chap-monitoring_and_observability.adoc, source/documentation/administration_guide/topics/Aggregation.adoc, source/documentation/administration_guide/topics/CPU.adoc, source/documentation/administration_guide/topics/DF.adoc, source/documentation/administration_guide/topics/Disks.adoc, source/documentation/administration_guide/topics/Entropy.adoc, source/documentation/administration_guide/topics/Gauge.adoc, source/documentation/administration_guide/topics/Interface.adoc, source/documentation/administration_guide/topics/Load.adoc, source/documentation/administration_guide/topics/Memory.adoc, source/documentation/administration_guide/topics/Metrics_Schema.adoc, source/documentation/administration_guide/topics/NFS.adoc, source/documentation/administration_guide/topics/Processes.adoc, source/documentation/administration_guide/topics/StatsD.adoc, source/documentation/administration_guide/topics/Swap.adoc, source/documentation/administration_guide/topics/Virt.adoc, source/documentation/administration_guide/topics/postgresql.adoc
- adding metrics schema files to upstream library in order to include in the Administration_guide/chap-monitoring_and_observability chapter
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @emarcusRH
This pull request needs review by: @sradco / @sandrobonazzola
=> schema - adding metrics schema files to upstream

source/_includes/developer_outdated.haml
- strong element used in haml removed pre and post whitespaces. Converted that part to plain html in order to have proper spacing.
=> fix outdated notice lack of spaces on strong

source/documentation/common/install/proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc
replace screen with tmux in proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc
- replace screen with tmux in proc-Deploying_the_Self-Hosted_Engine_Using_the_CLI.adoc
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @spameier
=> fix old screen mention

source/documentation/administration_guide/topics/Replacing_the_Manager_CA_Certificate.adoc
- Updating administration guide on Replacing the Manager CA Certificate topic to ensure the certificate has correct ownership and permissions.
=> updating admin guide for replacing CA

source/_includes/nav.haml, source/_sass/lib/site.sass
Unfortunately, the navigation menu does not display correctly on different screens.
The changes made here have been tested on my own computer.
I used Windows WSL2 for testing. Step by step manual here: https://gist.github.com/bencurio/2e82dc0a845fe1b786aca261ab92aaed
- Minor changes to the HTML structure of the main menu.
- Several CSS code changes and removals.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/7604637/116466644-0d207800-a86f-11eb-9b11-add915db579c.png"></td>
<td><img src="https://user-images.githubusercontent.com/7604637/116466729-275a5600-a86f-11eb-8e14-26cf09cc005e.png"></td>
</tr>
<tr>
<td colspan=2><img src="https://user-images.githubusercontent.com/7604637/116467178-b36c7d80-a86f-11eb-824f-a884fd08cd04.png"></td>
</tr>
<tr>
<td colspan=2><img …
=> Improve the appearance of the navigation menu on desktop and mobile.

source/develop/index.md, source/develop/infra/infrastructure.md, source/develop/integration/index.md
- link team pages in develop section
=> link team pages in develop section

run-server.sh, setup.sh
- Solves:
```
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across
bundler invocations, which bundler will no longer do in future versions.
Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
```
=> handle deprecation notice for bundler options

source/develop/release-management/features/sla/optaplanner.md
- optaplanner: mark as removed in 4.4
=> optaplanner: mark as removed in 4.4

source/release/4.4.7/index.md
- Add note about Bug 1979624 - imgbase should not copy selinux binary policy file
=> Add known issue to 4.4.7 notes

source/develop/release-management/features/integration/centos-9-stream-support.md
- Proposal to support CentOS Stream 9 for oVirt Project.
This pull request needs review by: @shenitzky @michalskrivanek @ahadas @mwperina
=> feature: CentOS Stream 9 support for oVirt

source/develop/developer-guide/engine/engine-supported-time-zones.md
This pull request updates the engine-supported-time-zones tutorial to support latest functionality change that was done here since version 4.4.8 [here](https://gerrit.ovirt.org/c/ovirt-engine/+/115342)
@ahadas @sandrobonazzola
=> update engine-supported-time-zones tutorial

source/develop/developer-guide/engine/engine-supported-time-zones.md
This PR fixes the missing in the engine supported time zones guide: https://www.ovirt.org/develop/developer-guide/engine/engine-supported-time-zones.html
=> add missing space to engine supported time zones guide

source/index.haml
- Remove link to conference registration in home page
=> Remove link to conference registration in home page

source/develop/release-management/features/virt/dedicated-cpu.md
- fixing name of `vdsmToCpuAffinity` in `Host.getCapabilities`
- better define content of `cpus` in `VM.migrate`
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
This pull request needs review by: @mz-pdm, @liranr23, @ahadas
=> dedicated-cpu: update page to match API implementation

source/documentation/common/install/proc-Adding_standard_hosts_to_the_Manager.adoc
The OvS cluster switch type is available on RHEL8 for some time.
@mwperina
=> admin guide: Remove note about OvS and RHEL8 hosts

source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-4.adoc, source/documentation/common/upgrade/snip_NOTE-CPU_passthrough.adoc, source/documentation/virtual_machine_management_guide/topics/Automatic_virtual_machine_migration.adoc, source/documentation/virtual_machine_management_guide/topics/Manually_migrating_virtual_machines.adoc
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2002146
- Adds note about why migrating VMs with CPU passthrough from RHV 4.3 to 4.4 might not work.
Previews:
Upgrade guide: same note for each relevant upgrade option:
http://file.emea.redhat.com/rhoch/20112021/upgrade/html-single/#Upgrading_hosts_to_4-4_4-3_local_db
http://file.emea.redhat.com/rhoch/20112021/upgrade/html-single/#Upgrading_hosts_to_4-4_4-3_remote_db
http://file.emea.redhat.com/rhoch/20112021/upgrade/html-single/#Upgrading_hosts_to_4-4_4-3_SHE
This pull request needs review by the reporter of the BZ.
=> Add note about migrating VMs with CPU Passthrough

source/documentation/upgrade_guide/index.adoc, source/documentation/upgrade_guide/master.adoc, source/documentation/upgrade_guide/topics/installing_virtual_product_hypervisors_from_local_repository.adoc
Fixes issue # (delete if not relevant) https://bugzilla.redhat.com/show_bug.cgi?id=1857398
- Adds an appendix to the Upgrade Grade that describes how to keep a local RHV-H repository for disconnected installation
Preview: http://file.emea.redhat.com/rhoch/18112021/BZ%231857398/html-single/#Installing_virtual_product_hypervisors_on_local_RHEL_appendices
=> Keeping a local RHV-H repository for disconnected installations

_config.yml
The stats VM will be moved from PHX so changing the URL accordingly.
Note: Please do not merge until we complete the migration to avoid data loss.
Jira-ticket: https://issues.redhat.com/browse/CPDEVOPS-338
Signed-off-by: Evgheni Dereveanchin <ederevea@redhat.com>
- change stats.phx.ovirt.org to stats.ovirt.org
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @jekader 
=> Update stats URL

source/documentation/index.haml
Fixes issue [BZ#2020448](https://bugzilla.redhat.com/show_bug.cgi?id=2020448)
Milestone: RHV 4.4.9 release
- Remove link to "Installing SHE using Cockpit" in the index.haml for the oVirt site 
I confirm that this pull request was submitted according to the contribution guidelines: (@emarcusRH )
This pull request needs review by: (please @sandrobonazzola )
=> removing link to cockpit installation file

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc, source/documentation/common/install/snip-RHVM_repo_steps.adoc, source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc
Fixes issue [BZ#1968384](https://bugzilla.redhat.com/show_bug.cgi?id=1968483)
** Do not release before: RHV 4.4.9 release
- update EAP repository channel to 7.4
- add note in Upgrade guide regarding the EAP 7.4 requirement
- update repo listings in Release Notes and JAVA SDK document (downstream only docs) - see  [MR#2087](https://gitlab.cee.redhat.com/rhci-documentation/docs-Red_Hat_Enterprise_Virtualization/-/merge_requests/2087)
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @emarcusRH 
=> BZ#1968483 update to EAP 7.4 channel in installation and upgrade guides

source/documentation/common/install/appe-Set_up_Cinderlib.adoc, source/documentation/common/install/proc-Configuring_the_Red_Hat_Virtualization_Manager.adoc, source/documentation/common/install/proc-Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories.adoc, source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc, source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_cockpit_web_interface/master.adoc, source/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/master.adoc, source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.adoc, source/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/master.adoc, source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/index.adoc, source/documentation/installing_ovirt_as_a_standalone_manager_with_remote_databases/master.adoc
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=1974729 and https://bugzilla.redhat.com/show_bug.cgi?id=1997666
- remove reference to two channels -osd- and -mon- as described in https://bugzilla.redhat.com/show_bug.cgi?id=1997666
- change references cinderlib from 16.1 to 16.2 - rename channel openstack-16.1-cinderlib-for-rhel-8-x86_64-rpms to openstack-16.2-cinderlib-for-rhel-8-x86_64-rpms
- https://bugzilla.redhat.com/show_bug.cgi?id=1974729#c2 - i.e. remove appendix C and move part of the content to install section (i.e. add the cinderlib and ceph-tools channels) for both manager and engine
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING. …
=> DRAFT: BZ1974729 - Update Cinderlib installation instructions

source/documentation/administration_guide/topics/Restoring_a_Backup_with_the_engine-backup_Command.adoc, source/documentation/common/backup-restore/assembly-Backing_up_and_Restoring_a_Self-Hosted_Engine.adoc
Fixes issue [BZ#1991914](https://bugzilla.redhat.com/show_bug.cgi?id=1991914)
update note regarding matching version of backup and engine environment version - 
- in Admin Guide under "Restoring a Backup with the engine-backup Command"
- in Upgrade Guide under "Backing up and restoring a Self-hosted engine" > prerequisites
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@emarcusRH )
This pull request needs review by: (@didib )
=> BZ#1991914 note regarding minor version compatibility for backup restore

.github/workflows/preview.yml
This change fixes the preview links in the final message after the preview build is complete.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @janosdebugs 
=> Fixed preview link

source/documentation/administration_guide/chap-Automating_RHV_Configuration_using_Ansible.adoc
Bug fix
This PR addresses https://bugzilla.redhat.com/show_bug.cgi?id=1979811)
- Changed verbiage to indicate that the version of Ansible included with oVirt/RHV is limited, not the full product.
Preview: https://ovirt.github.io/ovirt-site/previews/2637/documentation/administration_guide/index.html#chap-Automating_RHV_Configuration_using_Ansible
=> BZ1979811: Clarify Ansible scope

.github/workflows/dashpanel.yml, source/community/index.md
Adds a [dashpanel](https://github.com/marketplace/actions/dashpanel) for oVirt that:
* Runs each day at 00:08 (can also be triggered manually)
* Produces a file called `dashpanel-ovirt.md` that lists all public oVirt repositories that have open issues and/or PRs
* Commits the output file into source/community
* Links to the .md file directly on the Community main page (we can change this later if we find we need it, the output file would then need a preamble to be used correctly by the site builder)
Successfully tested on a test repository.
=> Add oVirt dashpanel

source/develop/developer-guide/migrating_to_github.md
- Add instructions for requiring CI to pass before merging
This pull request needs review by: @sanjacodes
=> migrating_to_github: require CI +1

source/community/becoming-an-infrastructure-team-member.md, source/develop/infra/infrastructure.md
- the oVirt jira on atlassian server is not monitored anymore by the oVirt DevOps team. Updating the documentation pointing to the new Jira tracker. Issue: https://issues.redhat.com/browse/CPDEVOPS-327
This pull request needs review by: @jekader @marchukov
=> oVirt DevOps: point to right tracker

source/develop/developer-guide/migrating_to_github.md
- This patch adds sections that create a DNF repository from the built RPMs in the example pipeline. Having the repo data in the zip archive will make it very easy to use it with OST.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @tinez
=> Add sections about creating a DNF repository

source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-3.adoc, source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc, source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-2.adoc, source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-2.adoc, source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/assembly-Upgrading_from_4-2.adoc, source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/chap-Red_Hat_Virtualization_Upgrade_Overview.adoc, source/documentation/upgrade_guide/index.adoc, source/documentation/upgrade_guide/master.adoc
Fixes issue [BZ#1946403](https://bugzilla.redhat.com/show_bug.cgi?id=1946403) and [BZ#1992729](https://bugzilla.redhat.com/show_bug.cgi?id=1992729) and [BZ#1903170](https://bugzilla.redhat.com/show_bug.cgi?id=1903170)
-Updates to Upgrade Guide for SHE upgrade from 4.3 to 4.4 - 
- to allign with procedure in [RHV Upgrade Helper App](https://access.redhat.com/labs/rhvupgradehelper/)
- restore the introduction/overview section to the Upgrade Guide
- update Upgrade Guide chapter titles for consistency
This pull request needs review by: (please @stoobie )
=> Updates to Upgrade Guide for SHE upgrade from 4.3 to 4.4 

.github/workflows/dashpanel.yml, .github/workflows/preview.yml, .github/workflows/remove-preview.yml
- This change adds the permissions key to make sure the ovirt-site repo retains permissions after org-wide enforcement for GHA policies.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @janosdebugs 
=> Added permissions key to grant permissions to repos

source/develop/release-management/features/sla/external-scheduling-proxy.md, source/develop/release-management/features/sla/ovirtschedulerapi.md, source/develop/sla/external-scheduler-samples.md, source/develop/sla/host-memory-balance.md
- Marked sections related to oVirt Scheduler Proxy as project discontinued starting from version 4.5
This pull request needs review by: @stoobie @michalskrivanek @ahadas @MarSik
=> external scheduler proxy: mark as dropped in 4.5

source/documentation/common/collateral_files/legal-notice.adoc, source/documentation/common/upgrade/proc-Upgrading_hypervisor_preserve_gluster_storage.adoc
Fixes issue  sync problems in downstream/Pantheon compilation due to illegal code block parameter
Changes proposed in this pull request:  remove [code, 
This pull request needs review by: (please @stoobie mention the reviewer if relevant)
=> fixing compilation sync errors - remove illegal code block param

.gitignore, source/documentation/administration_guide/topics/Manually_fencing_or_isolating_a_nonresponsive_host.adoc, source/documentation/disaster_recovery_guide/assembly/asm_ActiveActiveDR.adoc, source/documentation/disaster_recovery_guide/assembly/asm_ActivePassiveDR.adoc, source/documentation/disaster_recovery_guide/concept/cpt_DisasterRecoverySolutions.adoc, source/documentation/disaster_recovery_guide/concept/cpt_NetworkConsiderationsAA.adoc, source/documentation/disaster_recovery_guide/concept/cpt_NetworkConsiderationsAP.adoc, source/documentation/disaster_recovery_guide/concept/cpt_OverviewActiveActive.adoc, source/documentation/disaster_recovery_guide/concept/cpt_OverviewActivePassive.adoc, source/documentation/disaster_recovery_guide/concept/cpt_StorageConsiderationsAA.adoc, source/documentation/disaster_recovery_guide/concept/cpt_StorageConsiderationsAP.adoc, source/documentation/disaster_recovery_guide/concept/cpt_StretchPrerequisites.adoc, source/documentation/disaster_recovery_guide/index.adoc, source/documentation/disaster_recovery_guide/master.adoc, source/documentation/disaster_recovery_guide/reference/ref_UsingOvirtDrScript.adoc, source/documentation/disaster_recovery_guide/reference/rfr_MappingFileAttributes.adoc, source/documentation/disaster_recovery_guide/reference/rfr_TestingAP.adoc, source/documentation/disaster_recovery_guide/reference/rfr_discreet_failover.adoc, source/documentation/disaster_recovery_guide/reference/rfr_discreet_failover_failback.adoc, source/documentation/disaster_recovery_guide/reference/rfr_non_discreet_failover_failback.adoc, source/documentation/disaster_recovery_guide/task/task_Clean.adoc, source/documentation/disaster_recovery_guide/task/task_CommonStepsConfigureStretchCluster.adoc, source/documentation/disaster_recovery_guide/task/task_ConfigureStretchCluster.adoc, source/documentation/disaster_recovery_guide/task/task_CreateAnsiblePlaybooks.adoc, source/documentation/disaster_recovery_guide/task/task_CreateCleanupPlaybook.adoc, source/documentation/disaster_recovery_guide/task/task_CreateFailoverFailbackPlaybooks.adoc, source/documentation/disaster_recovery_guide/task/task_ExecuteFailback.adoc, source/documentation/disaster_recovery_guide/task/task_ExecuteFailover.adoc, source/documentation/disaster_recovery_guide/task/task_GenerateMapping.adoc
Bug fix
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2014790
- Updated topics on Storage consideration as per https://bugzilla.redhat.com/show_bug.cgi?id=2014790#c1:
- https://github.com/oVirt/ovirt-site/pull/2653/files#diff-f07c76203bba9d6afcb62d5b09264276dd2e011fc6b39b98057025ccf5d4415e 
- https://github.com/oVirt/ovirt-site/pull/2653/files#diff-840c2951c1ffae1691ee0fa5bf02f1e75fb24f0aeefde0abeeafc7e1dd8c3e86
- Lots of other editing fixes, not connected to technical content.
Preview
https://ovirt.github.io/ovirt-site/previews/2653/documentation/disaster_recovery_guide/index.html#storage_considerations_active_active
I confirm that this pull request was submitted according to the [contribution …
=> BZ2014790: [Docs] [DisasterRecovery] highlight that failovers cannot occur if the SPM is the point of failure if Power Management is not configured

source/documentation/virtual_machine_management_guide/topics/Configuring_Time_Zones.adoc
Add restart the engine step that was missing
to configuring tz document.
This pull request needs review by: @ahadas @dcdacosta @sandrobonazzola
=> Add missing step from configuring tz doc

source/documentation/virtual_machine_management_guide/topics/Configuring_Time_Zones.adoc
Fixes formatting issue in Configuring Time Zones topic
- Added closing ---- for the example in Step 3
- Used the {engine-package} attribute in Step 3 so the term resolves correctly for both upstream and downstream
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (@dcdacosta)
This pull request needs review by: (please @emarcusRH)
**Direct link to preview of changes:**
https://ovirt.github.io/ovirt-site/previews/2679/documentation/virtual_machine_management_guide/index.html#Configuring_timezones
=> Fixed formatting issue in Configuring Time Zone topic

source/documentation/common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc
Fixes issue #1822023
- "Migrating from a standalone manager to SHE" guide, section 6. "Restoring the Backup on a New Self-Hosted Engine" 
- add note regarding non operational host in SHE restore
- add link (RHV-docs only) to KCS article
Preview: https://ovirt.github.io/ovirt-site/previews/2680/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/index.html#Restoring_the_Backup_on_a_New_Self-hosted_Engine_migrating_to_SHE
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @emarcusRH 
=> BZ#1822023 add note regarding non operational host in SHE restore

source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc
Fixes issue #1867062
-add prerequisite for upgrading Manager 4.3 > 4.4: all VMs must have cluster compatibility level 4.3
Preview is here: https://ovirt.github.io/ovirt-site/previews/2677/documentation/upgrade_guide/index.html#Upgrading_the_Manager_to_4-4_4-3_SHE
This pull request needs review by: (please @RichardHoch )
=> BZ#1867062 add prerequisite for VMs to be set to cluster compatibility level 4.3

source/documentation/common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc
Fixes issue #1822023
- fix formatting error in ifdef statement - causes erroneous plus sign in downstream doc
downstream preview : https://jenkins.dxp.redhat.com/job/CCS/job/ccs-mr-preview/16417/artifact/assembly-Migrating_from_a_Standalone_Manager_to_a_Self-Hosted_Engine/preview/index.html#Restoring_the_Backup_on_a_New_Self-hosted_Engine_migrating_to_SHE
=> 1822023A fix formatting error

source/documentation/administration_guide/chap-Storage.adoc, source/documentation/administration_guide/topics/Uploading_Images_to_a_Data_Storage_Domain.adoc, source/documentation/common/prereqs/ref-Database_Server_Firewall_Requirements.adoc, source/documentation/common/prereqs/ref-Host_Firewall_Requirements.adoc, source/documentation/common/prereqs/ref-Manager_Firewall_Requirements.adoc
Fixes BZ1881864: https://bugzilla.redhat.com/show_bug.cgi?id=1881864
- Changing *ImageIO Proxy server* to *ovirt-imageio*
Previews:
https://ovirt.github.io/ovirt-site/previews/2682/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html#RHV-manager-firewall-requirements_SHE_cli_deploy
https://ovirt.github.io/ovirt-site/previews/2682/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html#host-firewall-requirements_SHE_cli_deploy
https://ovirt.github.io/ovirt-site/previews/2682/documentation/administration_guide/index.html#Uploading_Images_to_a_Data_Storage_Domain_storage_tasks
I confirm that this pull request was submitted according to the [contribution …
=> BZ1881864: [Docs] [Prereq] [Admin]  Image I/O Proxy replaced by ovirt-imageio

CODEOWNERS
Fixes issue #2688
- Removed ovirt-documentation from CODEOWNERS file.
This pull request needs review by: @sandrobonazzola @oVirt/ovirt-documentation
=> fix-issue2688 Removed ovirt-documentation from CODEOWNERS file.

source/develop/dev-process/working-with-github.md, source/develop/developer-guide/migrating_to_github.md
Creates links between "Working with oVirt on GitHub" and "Migrating to
GitHub" pages.
Signed-off-by: Martin Perina <mperina@redhat.com>
-
-
-
=> Create links between oVirt on GH related pages

source/develop/developer-guide/migrating_to_github.md
Update the github action example to use upload-rpms-action[1]
that takes a directory, creates an RPM repository if needed 
and uploads the resulting RPM repository.
[1] https://github.com/oVirt/upload-rpms-action
This pull request needs review by: @tinez @almusil
=> github migrating doc: Update the upload rpm action

source/documentation/administration_guide/topics/ref-Sample-SNMPv3-traps-configuration-file.adoc
Bug fix: Typos in SNMP topics, from BZ170211.
- Fixed typos and missing italics in user-replacebale text formatting
- Added text indicating the SNMP community only applies to version 2.
Preview:
https://ovirt.github.io/ovirt-site/previews/2701/documentation/administration_guide/index.html#SNMPv3-traps-configuration-file
=> 1702011.1 Fixing typos, indicating that community only applies to SNMPv2

source/documentation/common/prereqs/ref-Host_Storage_Requirements.adoc
[ Bug fix]
- /var/tmp should be larger than 8 GB the image is 6.8GB so there is not enough space on /var/tmp if its with the recommended 5 GB
=> /var/tmp should not be smaller than 8 GB

source/documentation/common/backup-restore/proc-Restoring_the_Backup_on_a_New_Self-hosted_Engine.adoc
Fixes issue # | [<BZ#1867911>(https://bugzilla.redhat.com/show_bug.cgi?id=1867911)
-modify note regarding non operational state in restoring SHE backup
Previews: 
https://ovirt.github.io/ovirt-site/previews/2702/documentation/administration_guide/index.html#Backing_up_and_Restoring_a_Self-hosted_Engine
https://ovirt.github.io/ovirt-site/previews/2702/documentation/migrating_from_a_standalone_manager_to_a_self-hosted_engine/index.html#Restoring_the_Backup_on_a_New_Self-hosted_Engine_migrating_to_SHE
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): ( @emarcusRH )
This pull request needs review by: (please @didib )
=> BZ#1867911 update note regarding non operational state in restoring SHE backup

source/documentation/administration_guide/chap-Log_Files.adoc, source/documentation/administration_guide/topics/proc_Enabling_SyslogHandler_RHV_Manager_logs.adoc
Fixes issue # | [BZ#2045913](https://bugzilla.redhat.com/show_bug.cgi?id=2045913)
- Administration Guide : 
replace entire enabling log4j chapter with new chapter: enabling SyslogHandler
- Preview: https://ovirt.github.io/ovirt-site/previews/2703/documentation/administration_guide/index.html#Enabling_SyslogHandler_RHV_Manager_logs
This pull request needs review by: (please @santos1709)
=> BZ#2045913 new chapter to replace log4j implementation with SyslogHandler

source/documentation/administration_guide/topics/Adding_an_External_Network_Provider.adoc
Bug fix
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2049446
1. Removes problematic sentence from the RHV 4.4 Administration Guide.
2. Replaces the lead-in to the procedure with the word 'procedure," properly formatted, as per current documentation standards.  
This pull request needs review by: @emarcusRH .
=> Resolves BZ2049446 -- removes problematic sentence from Admin Guide

source/index.haml
This reverts commit 797c1b494945cbe764b2a94375e37702113aba78.
The conference is long time over and there's no need to keep it announced on home page.
=> Revert "announce oVirt conference 2021"

source/documentation/administration_guide/topics/proc-adding-kubevirt-openshift-as-an-external-provider.adoc
Bug fix
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2048444. 
1. Replaces the phrase "master nodes" with the phrase "control plane nodes" in accordance with OpenShift documentation standards. 
2. Fixes formatting of the note in the verification steps.
Preview: https://ovirt.github.io/ovirt-site/previews/2724/documentation/administration_guide/index.html#proc-adding-kubevirt-openshift-as-an-external-provider_external_providers
This pull request needs review by @apinnick
=> Terminology and formatting fix

source/documentation/virtual_machine_management_guide/topics/Importing_an_OVA_file_from_a_host.adoc
Bug fix
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1967772
Replaces the ambiguous "VMware OVAs" with the clearer "OVAs created by VMware" in a note. 
This pull request needs review by: Robert McSwain and @apinnick.
=> BZ#1967772--Clarify statement about vMware OVAs

source/.htaccess
[Bug fix]
console-client-resources page is linked from the engine and from several
BZs and sites. Providing a redirect to the dropped page.
Using 302 instead of 301 as there's not yet a final decision on where
this content should be located within the site.
=> redirect page for console-client-resources

source/documentation/upgrade_guide/chap-Red_Hat_Virtualization_Upgrade_Overview.adoc, source/documentation/upgrade_guide/index.adoc, source/documentation/upgrade_guide/master.adoc
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2054250
- Change order of assemblies so that 4.3 upgrade appears before 4.2 upgrade
- Changed order of table in overview so 4.3 is before 4.2
Direct link to preview document:
https://ovirt.github.io/ovirt-site/previews/2778/documentation/upgrade_guide/index.html
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @dcdacosta)
This pull request needs review by: (@emarcusRH )
=> BZ2054250 - rearranged Upgrade Guide

source/documentation/common/install/proc-Installing_Red_Hat_Virtualization_Hosts.adoc
Fixes issue https://github.com/oVirt/ovirt-site/issues/2786
- Used conditional text to correct the link reference for the upstream doc. It now points to https://ovirt.org/documentation/installing_ovirt_as_a_standalone_manager_with_local_databases/index.html#host-requirements
=> PR2786 - Corrected link reference for upstream

source/documentation/common/she/proc_Manually_installing_the_appliance.adoc
Broken variable in https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/installing_red_hat_virtualization_as_a_self-hosted_engine_using_the_command_line/index#proc_Manually_installing_the_appliance_install_RHVM (Step 2)
- Fixed broken variable in step 2 using conditional text to render correctly in both upstream and downstream doc.-
=> PR2784_1 - Fixed variable issue in Install via command line doc

source/documentation/virtual_machine_management_guide/topics/Importing_an_OVA_file_from_a_host.adoc
Fixes issue # | \[BZ#1993237](https://bugzilla.redhat.com/show_bug.cgi?id=1993237  (delete if not relevant)
- Add note regarding location of OVA import directory - NOT directly under /root
Preview - https://ovirt.github.io/ovirt-site/previews/2777/documentation/virtual_machine_management_guide/index.html#Importing_a_virtual_machine_from_a_host
This pull request needs review by: (please @ahadas )
=> Add note to OVA import instructions re: directory location NOT /root

source/documentation/administration_guide/chap-Virtual_Disks.adoc, source/documentation/administration_guide/topics/The_ISO_Uploader_Tool.adoc, source/documentation/administration_guide/topics/Uploading_the_VirtIO_and_Guest_Tool_Image_Files_to_an_ISO_Storage_Domain.adoc, source/documentation/administration_guide/topics/proc_Copy_image_to_ISO_domain.adoc
- replacing a number of identical xrefs (Uploading_Images_to_a_Data_Storage_Domain) with a direct link URL to the guide
due to error logs in Pantheon publishing tool pointing to a specific xref
This pull request needs review by: (please @ )
=> admin_xref replacing xref with direct link in Admin Guide

_config.yml
[Bug fix]
Fixes issue #2822
- skip generation of chap, asm and topics for new books
=> config: skip generation of asm, chap and topics

source/develop/developer-guide/migrating_to_github.md, source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
[Feature]
[BZ 2021497](https://bugzilla.redhat.com/show_bug.cgi?id=2021497)
Add note about enabling mod_auth_openidc:2.3
See also: https://github.com/oVirt/ovirt-release/pull/166
This pull request needs review by: @arso @mwperina @oVirt/ovirt-documentation
=> 4.5 now requires mod_auth_openidc:2.3

source/documentation/common/install/assembly-Installing_Hosts_for_RHV.adoc
[Bug fix]
Fixes issue #2785
- drop link to RHV lifecycle page on oVirt site. There's no equivalent to RHV lifecycle page for oVirt.
=> point to lifecycle page only for RHV

source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc, source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=2042398
- Added ovirt-scheduler-proxy to table of removed features.
- Removed ovirt-scheduler-proxy from table of deprecated features.-
This pull request needs peer review by: (@emarcusRH )
=> BZ2042398 - Remove functionality: oVirt Scheduler Proxy

source/documentation/common/install/snip-Enable_virt_module.adoc
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2036835
- Use virt:rhel module instead of virt:av in RHEL 8.6+ to get advanced virtualization packages
Changes can be verified using the following preview links:
1. https://ovirt.github.io/ovirt-site/previews/2740/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html#proc_Manually_installing_the_appliance_install_RHVM
2. https://ovirt.github.io/ovirt-site/previews/2740/documentation/upgrade_guide/index.html#Manually_Updating_Hosts_minor_updates
3. https://ovirt.github.io/ovirt-site/previews/2740/documentation/administration_guide/index.html#Updating_a_host_between_minor_releases
I confirm that this pull request was submitted according to the [contribution …
=> BZ2036835 - Update advanced virtualization to virt:rhel

source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc, source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc
Fixes issue # | [BZ#2028192](https://bugzilla.redhat.com/show_bug.cgi?id=2028192) (delete if not relevant)
Add ovirt scheduler proxy to Deprecated Functionality table in Rel Notes
comment out same notice from Removed Functionality table in Rel Notes
=> BZ#2028192 add deprecation notce for ovirt scheduler proxy

source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc
Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2071496
- Add -E to grep in Step 5 Make sure that the self-hosted engine is shut down.
hosted-engine --vm-status | grep 'Engine status|Hostname'
This pull request needs review by: (@ahadas )
=> BZ2071496 - Added -E option to the grep command in the example

_config.yml
Bug fix
Related-To: https://github.com/oVirt/ovirt-site/issues/2842#issuecomment-1096778313
- skip building Product Guide and Technical Notes for oVirt as they are relevant for RHV only.
This pull request needs review by: @apinnick
=> Don't build Product Guide and Technical Notes

source/documentation/common/install/con-Recommended_practices_for_configuring_host_networks.adoc
[Bug fix]
Fixes issue #2597
- Fix typo ivp4 -> ipv4
=> Fix typo ivp4 -> ipv4

source/download/node.md
[Bug fix]
Fixes issue #2864 
- Move 4.4 stable release to under "Old releases" section, and change to link to ISO file directly as in 4.3.
- Add 4.5 stable release section
- I didn't remove 4.5 pre release section since it was left [in this page for 4.4 release](https://github.com/oVirt/ovirt-site/blob/9a933191f8938477066f5abff0e3ca0805416a4a/source/download/node.md).
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @kurokobo
This pull request needs review by: no idea, but it would be helpful if @sandrobonazzola, who created the PR to release 4.5 docs, could confirm this. Please add mentions if you know appropreate reviewers.
=> Add download link for 4.5 stable release

source/documentation/doc-Release_Notes/update-beta.sh, source/documentation/doc-Release_Notes/update-ga.sh, source/documentation/doc-Release_Notes/update-zstream.sh
Removing prompts for username and password in the downstream RN scripts because BZ uses API key.
=> Removing prompts for user/pw

source/release/4.5.0/index.md
- Update 4.5.0 notes with ovirt-engine 4.5.0.5 notes
=> 4.5.0: add engine 4.5.0.5 notes

source/documentation/administration_guide/chap-External_Providers.adoc, source/documentation/administration_guide/topics/Add_Provider_General_Settings_Explained.adoc, source/documentation/administration_guide/topics/Adding_OVN_as_an_External_Network_Provider.adoc, source/documentation/administration_guide/topics/Configuring_Hosts_for_an_OVN_tunnel_network.adoc, source/documentation/administration_guide/topics/Installing_a_new_OVN_network_provider.adoc, source/documentation/common/upgrade/snip-upgrade_considerations.adoc
This PR is a duplicate of https://github.com/oVirt/ovirt-site/pull/2739. The admin guide changes were previously reviewed and approved. The main difference here is the update to the Upgrade Guide. I created a new PR based on merge conflict issue with original PR that I was unable to untangle. 
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2006228
Fixes issue: https://bugzilla.redhat.com/show_bug.cgi?id=2006228
Section 14.2.7: Removed CloudForms support note.
Section 14.2.7.1: Removed the warning about openvswitch version.
Section 14.2.7.2: Removed
Section 14.2.7.3: Removed
Section 14.2.7.4: Keep only the part under "Updating the OVN Tunnel Network on a Single Host", everything else can be removed.
The …
=> BZ2006228 - Updates for OVN/OVS upgrade to the Admin and Upgrade Guides

source/documentation/administration_guide/topics/Cluster_General_Settings_Explained.adoc, source/documentation/administration_guide/topics/Creating_a_New_Cluster.adoc, source/documentation/virtual_machine_management_guide/topics/Virtual_Machine_System_Settings_Explained.adoc
Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=1919809
- Added FIPS Mode property to General Cluster Settings and Creating a New Cluster topics.
Direct links to the preview of changes:
- https://ovirt.github.io/ovirt-site/previews/2774/documentation/administration_guide/index.html#Creating_a_New_Cluster
- https://ovirt.github.io/ovirt-site/previews/2774/documentation/administration_guide/index.html#Cluster_General_Settings_Explained
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): (please @dcdacosta )
=> BZ1919809 - Added new FIPS Mode property for clusters

source/documentation/common/upgrade/proc-Updating_the_Red_Hat_Virtualization_Manager.adoc
[ Bug fix]
Fixes issue # | \[BZ#2059877](https://bugzilla.redhat.com/show_bug.cgi?id=2059877)  (delete if not relevant)
-add --nobest switch to yum update command in RHVM upgrade
Previews: 
https://ovirt.github.io/ovirt-site/previews/2875/documentation/upgrade_guide/index.html#Updating_the_Red_Hat_Virtualization_Manager_4-3_remote_db
https://ovirt.github.io/ovirt-site/previews/2875/documentation/upgrade_guide/index.html#Updating_the_Red_Hat_Virtualization_Manager_4-2_remote_db
https://ovirt.github.io/ovirt-site/previews/2875/documentation/upgrade_guide/index.html#Updating_the_Red_Hat_Virtualization_Manager_4-4_SHE
https://ovirt.github.io/ovirt-site/previews/2875/documentation/upgrade_guide/index.html#Updating_the_Red_Hat_Virtualization_Manager_4-3_SHE …
=> BZ#2059877 add --nobest switch to yum update command in RHVM upgrade 

source/documentation/doc-Release_Notes/topics/Additional_Packages_from_Red_Hat_Network.adoc
… RHV Host Build for RHEL 8
[ Bug fix]
Fixes issue # | \[BZ#2060085](https://bugzilla.redhat.com/show_bug.cgi?id=2060085) 
-remove row in additional packages table - RHV Host build for RHEL 8
=> BZ#2060085  remove deprecated RHV Host build RHEL 8 from Rel Notes table

source/documentation/common/database/proc-disabling-the-data-warehouse-service.adoc
Fixes issue # | \[BZ#2080192](https://bugzilla.redhat.com/show_bug.cgi?id=2080192)  (delete if not relevant)
Removed extra space in the command for disabling DWH service - but needed to add escape character (backslash) in the ASCIIDOC so that the asterisk is not ignored, and the line is not rendered as bold text.
=> BZ#2080192 remove extra space from command Disabling DWH Service

source/documentation/administration_guide/topics/Red_Hat_Virtualization_Hosts.adoc
[Feature]
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2036586
- Added a statement that starting in RHV 4.4 SP1 system-coredump will be used by the hypervisor for coredumps.
This pull request needs review by: (@hbraha )
=> BZ2036586 - Added information about the system-coredump service

source/community/index.md
- previously we were saying we develop most of the projects on gerrit. We are now on GitHub.
This pull request needs review by: @oVirt/developers
=> community: point to github

source/develop/dev-process/install-nightly-snapshot.md
I keep accidentally copying the instructions for CS9 on my CS8 machines.
Hopefully putting 8 first will help...
Also add a note that 9 is WIP.
=> Nightly snapshot: Put CentOS Stream 8 first

source/documentation/doc-REST_API_Guide/model.adoc
Bug fix
Fixes:
- asciidoctor: WARNING: model.adoc: line 3080: id assigned to section already in use: services
- asciidoctor: WARNING: model.adoc: line 33586: id assigned to section already in use: types
=> REST_API_Guide: fix duplicate ids

source/documentation/doc-Release_Notes/topics/ref-Deprecated_Features_RHV.adoc, source/documentation/doc-Release_Notes/topics/ref-Removed_Features_RHV.adoc
…eprecated, now both in Removed Functionality table
Fixes issue # | \[BZ#2056937](https://bugzilla.redhat.com/show_bug.cgi?id=2056937)  (delete if not relevant)
- move ovirt scheduler proxy and RHVM appliance from Deprecated to Removed-
=> BZ#2056937  move ovirt scheduler proxy and RHVM appliance from Deprecated to Removed

source/documentation/common/prereqs/ref-Host_Storage_Requirements.adoc
[Bug fix]
Fixes issue https://bugzilla.redhat.com/show_bug.cgi?id=2066055
- Changed /var to 5GB and  /var/tmp to 10GB
=> BZ2066055 - updated partition sizes in host storage reqs info

source/download/install_on_rhel.md
- add workaround for installing on Rocky Linux solving: `Error: Failed to download metadata for repo 'centos-nfv-openvswitch': Cannot prepare internal mirrorlist: No URLs in mirrorlist`
This pull request needs review by: @rocky-linux @NeilHanlon
=> add rocky workaround

source/documentation/doc-Technical_Reference/topics/Port_Mirroring.adoc
Hot linking vNICs with a profile that has port mirroring enabled is not
supported, and not hot plugging.
Signed-off-by: Eitan Raviv <eraviv@redhat.com>
Change-Id: I6e43ec7b91964cfefc6984f70588a0d7d6881990
-
-
-
=> networking - fix typo in port mirroring limitations

source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc
Fixes issue # | [BZ#1986834](https://bugzilla.redhat.com/show_bug.cgi?id=1986834)  and [BZ#2080505](https://bugzilla.redhat.com/show_bug.cgi?id=2080505)
- add nodejs:14 and maven to modules that are enabled  in the Installation Guide and Upgrade Guide
- Preview - https://ovirt.github.io/ovirt-site/previews/2922/documentation/installing_ovirt_as_a_self-hosted_engine_using_the_command_line/index.html#Enabling_the_Red_Hat_Virtualization_Manager_Repositories_install_RHVM
This pull request needs review by: (please @sandrobonazzola )
=> BZ#1986834 and BZ#2080505 add nodejs:14 and maven to modules that are enabled

source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.0-1.adoc
Fixes issue with incorrect title that is auto created by the RN script
- Changed title to reflect RHV 4.4 SP1 instead of RHV 4.5 and ovirt-4.5.0 instead of ovirt-4.5.0-1
=> RHV44569 - Fixed title for 4.4 SP1

source/documentation/administration_guide/topics/Grafana_dashboards.adoc
Fixes issue # | \[BZ#2041216](https://bugzilla.redhat.com/show_bug.cgi?id=2041216)  (delete if not relevant)
- add note regarding Grafana dashboard direct links to Admin Portal
Preview link - https://ovirt.github.io/ovirt-site/previews/2917/documentation/administration_guide/index.html#Grafana_dashboards
=> BZ#2041216 add note regarding Grafana dashboard direct links to Admin Portal

source/documentation/data_warehouse_guide/topics/Virtual_machine_disk_hourly_and_samples_history_views.adoc
Fixes issue # | \[BZ #2064259](https://bugzilla.redhat.com/show_bug.cgi?id=2064259)  (delete if not relevant)
- adding 2 params and removing 2 params in DWH virtual disk stats table
- Preview - https://ovirt.github.io/ovirt-site/previews/2918/documentation/data_warehouse_guide/index.html#Virtual_machine_disk_hourly_and_samples_history_views
=> BZ#2064259 adding 2 params / removing 2 params in DWH virtual disk stats table

source/documentation/upgrade_guide/assembly-Remote_Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/assembly-SHE_Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/assembly-Upgrading_from_4-3.adoc, source/documentation/upgrade_guide/chap-Updates_between_Minor_Releases.adoc
@erav Reported that the snippet "Upgrade Considerations" did not appear in the published RHV docs.
This PR fixes the "snip-upgrade-considerations" not displaying correctly and a typo in one of the "ifdefs".
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @apinnick
=> Fixed 'ifdefs' so that snip-upgrade-considerations appears

source/documentation/doc-Release_Notes/chap-RHEV_for_IBM_Power.adoc, source/documentation/virtual_machine_management_guide/topics/Powering_on_a_virtual_machine.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1886803
- Added steps to change risk level to 0 if VM fails to boot on Power9
This pull request needs review by: @mz-pdm, David Gibson
=> BZ1886803 - Added information regarding risk levels for IBM POWER9

source/develop/release-management/features/infra/engine-snmp3.md
This patch fix the following issues on SNMP doc:
1) Add the port to SNMP_MANAGERS settings.
2) Creates the right type required by SELinux for /var/log/snmptrapd.log
3) Fixes the user name from 'engine' to the defined 'ovirtengine' in 3rd
example
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/master/CONTRIBUTING.md): @emesika 
=> Fix SNMP 3 feature page

source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.0-1.adoc
- CVE issues are NOT supposed to be exposed in Release Notes, 
they only belong in RHSA security Errata
- I am commenting out all the CVE bugs in the current release notes
=> relnotes  - commenting out CVE bugs

source/documentation/index.haml
fix index.haml for upstream doc portal - redirect to correct doc folder
=> Rhv 46139  fix index.haml for upstream doc portal

_config.yml
Bug fix
- excluding adoc previously excluded by documentation directory regular expressions also in the dropped directory after docs content moved there.
=> config: exclude adoc from dropped dir

source/documentation/doc-Release_Notes/topics/ref-ovirt-4.5.0-1.adoc
Fixes issue # https://bugzilla.redhat.com/show_bug.cgi?id=2012830
- Added statement "Starting with RHEL 8.6, this will be the default for storage device management."-
=> LVMrn - added default statement for RHEL8.6

source/download/node.md
- update node download page explaining when to avoid using it and giving some notes aboud the CentOS Stream 9 based iso.
=> node: update download page

source/documentation/virtual_machine_management_guide/topics/Installing_Remote_Viewer_on_Windows.adoc, source/documentation/virtual_machine_management_guide/topics/Installing_usbdk_on_Windows.adoc
Bug fix
Fixes issue #2772
- Fix `Installing Console Components` section within `Virtual Machine Management Guide` for oVirt,
pointing to the upstream download pages for virt-manager adn usbdk.
=> Fix Installing Console Components section

source/develop/networking/infiniband.md
Fixes issue #2972
- Fix markdown and drop obsolete references to very old bugs
=> infiniband: fix markdown and drop obsolete refs

source/documentation/administration_guide/topics/Editing_Host_Network_Interfaces_and_Assigning_Logical_Networks_to_Hosts.adoc, source/documentation/doc-Release_Notes/topics/ref-Technology_Preview_Features_RHV.adoc
Bug fix
Fixes issue [2108055](https://bugzilla.redhat.com/show_bug.cgi?id=2108055)
- Remove "Dual stack not supported" notes for upstream only
This pull request needs review by: @arachmani 
Upstream [preview build](https://ovirt.github.io/ovirt-site/previews/3028/documentation/administration_guide/index.html#Editing_Host_Network_Interfaces_and_Assigning_Logical_Networks_to_Hosts)
=> BZ2108055: remove "dual stack not supported" notes

source/documentation/virtual_machine_management_guide/topics/Opening_a_Serial_Console_to_a_Virtual_Machine.adoc
[RHVDDF-50]](https://issues.redhat.com/browse/RHVDDF-50)
- RHV VMM Guide - remove comment switch from sample ssh-keygen command to avoid confusion
=> rhvddf-50 remove comment switch from sample keygen command

source/documentation/administration_guide/topics/Updating_SSL_certificates.adoc, source/documentation/common/upgrade/proc-Replacing_SHA-1_Certificates_with_SHA-256_Certificates.adoc
[[RHVDDF-51]](https://issues.redhat.com/browse/RHVDDF-51)
-add note regarding hard coded password value in authorization keys
- Administration Guide - Updating SSL certificates
-  Upgrade Guide - Replacing SHA-1 with SHA-256
=> rhvddf-51 adding note regarding mypass password in auth keys

source/develop/release-management/features/virt/zerocopy-migrations.md
- Fix the broken link to parallel migrations feature page.
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @mz-pdm
=> Fix the link in Zero-copy migrations feature page

source/documentation/administration_guide/topics/Renaming_the_Manager_with_the_Ovirt_Engine_Rename_Tool.adoc
Bug fix
Fixes [BZ#2021874](https://bugzilla.redhat.com/show_bug.cgi?id=2021874)
- add manual engine renaming procedure for remote DWH deploy
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @emarcusRH
=> BZ#2021874 add manual engine renaming procedure for remote DWH deploy

source/documentation/common/prereqs/ref-Manager_Operating_System_Requirements.adoc, source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc, source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-4.adoc, source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc, source/documentation/common/upgrade/proc_upgrading-the-remote-data-warehouse-service-and-database.adoc
Bug fix
Fixes [BZ 2115388](https://bugzilla.redhat.com/show_bug.cgi?id=2115388)
- fix formatting in chapter on updating RHV manager
add note in following regarding RHEL 8.6 limitation:
- source/documentation/common/prereqs/ref-Manager_Operating_System_Requirements.adoc
- source/documentation/common/upgrade/proc_upgrading-the-remote-data-warehouse-service-and-database.adoc
- source/documentation/common/upgrade/proc-Upgrading_hosts_to_4-4.adoc
- source/documentation/common/upgrade/proc-Upgrading_the_Manager_to_4-4.adoc
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @emarcusRH
This pull request needs review by: (please @mention the reviewer if …
=> BZ#2115388 Update RHEL 8.6 version limitation 

source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc
Fixes issue # |[BZ 2111254](https://bugzilla.redhat.com/show_bug.cgi?id=2111254) 
- fix formatting in manually updating hosts procedure ( enable virt section)
- add node js 14 enable instruction to Upgrade Guide manually updating hosts
PREVIEW: https://ovirt.github.io/ovirt-site/previews/3068/documentation/upgrade_guide/index.html#Manually_Updating_Hosts_minor_updates
=> BZ#2111254 add nodejs14 instructions to upgrade guide

source/documentation/upgrade_guide/docinfo.xml, source/documentation/upgrade_guide/index.adoc
Updating downstream version number. Upgrade Guide should be 4.3, not 4.4. 
Republishing doc on 4.3 splash page and removing from 4.4 splash page.
@sandrobonazzola  Please review.
=> Update downstream version number

source/documentation/virtual_machine_management_guide/topics/Cloning_a_Virtual_Machine.adoc
Bug fix
Fixes [BZ2155633](https://bugzilla.redhat.com/show_bug.cgi?id=2155633) 
- Remove admonition in [Cloning VMs](https://ovirt.github.io/ovirt-site/previews/3108/documentation/virtual_machine_management_guide/index.html#Cloning_a_Virtual_Machine)
-
-
=> BZ2155633: remove note from VM clone procedure

source/documentation/common/install/proc-Installing_Red_Hat_Enterprise_Linux_Hosts.adoc
- Moving el9 out of tech preview as it's supported since 4.5.4
This pull request needs review by: @oVirt/ovirt-documentation 
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
=> el9 is not tech preview anymore

source/documentation/common/install/proc-Enabling_the_Red_Hat_Enterprise_Linux_Host_Repositories.adoc, source/documentation/common/install/proc-Enabling_the_Red_Hat_Virtualization_Manager_Repositories.adoc, source/documentation/common/install/snip-RHVM_repo_steps.adoc, source/documentation/common/upgrade/proc-Manually_Updating_Hosts.adoc, source/documentation/common/upgrade/proc-Updating_Individual_Hosts.adoc
RHV install guides - update RHEL 8.6 EUS channel info
Fixes issue # | [BZ#2160486](https://bugzilla.redhat.com/show_bug.cgi?id=2160486) 
-  Change RHEL 8.6 EUS subscription channel in installation guides
DOWNSTREAM ONLY 
Previews need to be individually manually compiled... TBD
=> BZ#2160486  updates to RHEL 8.6 EUS subscription channel info

CONTRIBUTING.md
- Add a note about automatic preview creation in `CONTRIBUTING.md` document
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @didib 
Signed-off-by: Yedidyah Bar David <didi@redhat.com>
=> CONTRIBUTING: Add a note about automatic preview creation

source/documentation/administration_guide/topics/Using_host_power_management_functions.adoc
Fixes issue # | [BZ#2011159](https://bugzilla.redhat.com/show_bug.cgi?id=2011159)  
- add link to RHEL power management section in Admin Guide using host power management functions
=> BZ#2011159 add reference link to Admin Guide sec using host power management

source/documentation/virtual_machine_management_guide/topics/Configuring_operating_systems_with_osinfo.adoc
Fixes issue # | [BZ#2011218](https://bugzilla.redhat.com/show_bug.cgi?id=2011218)  
-In VMM GUIDE,  add note regarding Windows  Server 2016 config in a VM
=> BZ#2011218  add note regarding Windows  Server 2016 config in a VM

source/documentation/common/prereqs/asm-Host_Requirements.adoc, source/download/node.md
Bug fix
[Bug #2081648](https://bugzilla.redhat.com/show_bug.cgi?id=2081648) has been fixed and secure boot has been reported working on CentOS Stream 9.
Removing the notice about it.
See also: https://lists.ovirt.org/archives/list/users@ovirt.org/thread/BHFJHR73Z474JSOWHXDVZD4R6JXGUHCA/#BHFJHR73Z474JSOWHXDVZD4R6JXGUHCA
This pull request needs review by: @oVirt/developers
=> Drop note about bug 2081648

.markdownlint.json, source/community/about/contact.md, source/community/index.md, source/develop/developer-guide/readme_template.md, source/develop/developer-guide/vdsm/todo.md, source/develop/index.md, source/develop/integration/index.md, source/develop/qa/index.md
Bug fix
- Bugzilla oVirt classification is not accepting new tickets as the project migrated to GitHub issues tracking system.
=> Drop bugzilla references on developer guide

source/download/rpms_and_gpg.md
Added the details of the new signing key (24901D0C).
- Updated the GPG key(s) information with the details of the new key (24901D0C)
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): (@lveyde)
=> Updated the GPG key(s) infomation

source/develop/index.md
[Bug fix]
Fixes issue # 3169
- minor documentation changes to remove broken github link and add reference to list of public repos for oVirt
-
-
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @gocallag )
=> Removed broken github link and added link to public repos

source/develop/release-management/features/integration/ovirtappliance.md
[Bug fix]
Fixes issue #3156 
- Added instructions for getting the OVA from the rpm file
-
-
=> updated instructions on how to obtain the OVA from the rpm file

.github/workflows/preview.yml
dependabot suggested bumping download-artifact only but both need to have compatible versions.
=> Bump artifacts actions to v4

source/documentation/virtual_machine_management_guide/topics/Installing_Remote_Viewer_on_Windows.adoc
[Bug fix]
Fixes broken hyperlink in a documentation page. 
I confirm that this pull request was submitted according to the [contribution guidelines](https://github.com/oVirt/ovirt-site/blob/main/CONTRIBUTING.md): @arthurvr
=> Fix broken link in `Installing_Remote_Viewer_on_Windows.adoc`

.github/workflows/preview.yml, .github/workflows/remove-preview.yml
Bug fix
solves:
The following actions use a deprecated Node.js version and will be forced to run on node20:
* actions/checkout@v3,
* docker/setup-buildx-action@v2,
* docker/build-push-action@v3,
* actions/cache@v3.
=> gh actions: update gh actions

.github/workflows/preview.yml, data/authors.yml, source/community/about/community-guidelines.md, source/community/about/contact.md, source/community/index.md, source/develop/index.md, source/develop/localization.md, source/develop/qa/index.md, source/index.haml
- Removed Zanata due to being deprecated.
- Added Matrix as a new way of conversation.
- Added Weblate as new localization.
- Removed Gluster due to being deprecated
@JasperB-TeamBlue 
@sandrobonazzola @dupondje
=> add Matrix and Weblate to contact and localization

source/documentation/common/arch/con-Self-hosted_Engine_Architecture.adoc, source/documentation/common/arch/con-Standalone_Manager_Architecture.adoc, source/documentation/common/collateral_files/_attributes.adoc, source/documentation/common/prereqs/asm-Networking_Requirements.adoc, source/documentation/common/prereqs/ref-Database_Server_Firewall_Requirements.adoc, source/documentation/common/prereqs/ref-Host_PCI_Device_Requirements.adoc, source/documentation/common/prereqs/ref-Host_Storage_Requirements.adoc, source/documentation/common/prereqs/ref-MTU_Requirements.adoc, source/documentation/common/prereqs/ref-Manager_Client_Requirements.adoc, source/documentation/common/prereqs/ref-Manager_Firewall_Requirements.adoc, source/documentation/common/prereqs/ref-Manager_Hardware_Requirements.adoc, source/documentation/planning_and_prerequisites_guide/topics/con-Directory_Server_Support.adoc, source/documentation/planning_and_prerequisites_guide/topics/con-General_Recommendations.adoc, source/documentation/planning_and_prerequisites_guide/topics/con-Infrastructure_Considerations.adoc, source/documentation/planning_and_prerequisites_guide/topics/con-Storage_Types.adoc
Changes proposed in this pull request: 
- Remove reference to obsolete (and missing) sizing guide
- Updated reference from EL 8 to EL 9
- Replaced reference to Red Hat HA products
- Cleaned up references to RHEL
- Added references to CentOS Stream and AlmaLinux
- Fixed internal document section references for virt-viewer
- Updated attribute for supported Linux to be EL 9 or later, rather then 8.7
- Removed swap space reference to restricted red hat doco
- Fixed memory optimization section reference
- Added replacement links for Q35 machine type and PCI (PCIE) references
- Removed red hat link for disabling IPV6 and just left it as do not disable IPV6
- Removed RHV engine firewall section
- Fixed section link for kdump fencing for engine
- removed the RHV firewall section for the Database …
=> Cleanup PRG and related doco
